// Mocks generated by Mockito 5.4.6 from annotations
// in spots/test/integration/ui/navigation_flow_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;

import 'package:flutter_stripe/flutter_stripe.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i18;
import 'package:spots/core/models/business_account.dart' as _i10;
import 'package:spots/core/models/business_expert_preferences.dart' as _i23;
import 'package:spots/core/models/business_patron_preferences.dart' as _i24;
import 'package:spots/core/models/business_verification.dart' as _i11;
import 'package:spots/core/models/event_partnership.dart' as _i8;
import 'package:spots/core/models/expertise_event.dart' as _i6;
import 'package:spots/core/models/payment.dart' as _i5;
import 'package:spots/core/models/payment_intent.dart' as _i14;
import 'package:spots/core/models/payment_result.dart' as _i3;
import 'package:spots/core/models/revenue_split.dart' as _i4;
import 'package:spots/core/models/spot.dart' as _i17;
import 'package:spots/core/models/unified_user.dart' as _i16;
import 'package:spots/core/services/business_account_service.dart' as _i22;
import 'package:spots/core/services/business_service.dart' as _i21;
import 'package:spots/core/services/expertise_event_service.dart' as _i15;
import 'package:spots/core/services/partnership_matching_service.dart' as _i20;
import 'package:spots/core/services/partnership_service.dart' as _i19;
import 'package:spots/core/services/payment_event_service.dart' as _i9;
import 'package:spots/core/services/payment_service.dart' as _i12;
import 'package:spots/core/services/stripe_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeStripeService_0 extends _i1.SmartFake implements _i2.StripeService {
  _FakeStripeService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaymentResult_1 extends _i1.SmartFake implements _i3.PaymentResult {
  _FakePaymentResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRevenueSplit_2 extends _i1.SmartFake implements _i4.RevenueSplit {
  _FakeRevenueSplit_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePayment_3 extends _i1.SmartFake implements _i5.Payment {
  _FakePayment_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExpertiseEvent_4 extends _i1.SmartFake
    implements _i6.ExpertiseEvent {
  _FakeExpertiseEvent_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaymentIntent_5 extends _i1.SmartFake implements _i7.PaymentIntent {
  _FakePaymentIntent_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEventPartnership_6 extends _i1.SmartFake
    implements _i8.EventPartnership {
  _FakeEventPartnership_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaymentEventResult_7 extends _i1.SmartFake
    implements _i9.PaymentEventResult {
  _FakePaymentEventResult_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRefundResult_8 extends _i1.SmartFake implements _i9.RefundResult {
  _FakeRefundResult_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBusinessAccount_9 extends _i1.SmartFake
    implements _i10.BusinessAccount {
  _FakeBusinessAccount_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBusinessVerification_10 extends _i1.SmartFake
    implements _i11.BusinessVerification {
  _FakeBusinessVerification_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PaymentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentService extends _i1.Mock implements _i12.PaymentService {
  MockPaymentService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i2.StripeService get stripeService => (super.noSuchMethod(
        Invocation.getter(#stripeService),
        returnValue: _FakeStripeService_0(
          this,
          Invocation.getter(#stripeService),
        ),
      ) as _i2.StripeService);

  @override
  _i13.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<_i3.PaymentResult> purchaseEventTicket({
    required String? eventId,
    required String? userId,
    required double? ticketPrice,
    required int? quantity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #purchaseEventTicket,
          [],
          {
            #eventId: eventId,
            #userId: userId,
            #ticketPrice: ticketPrice,
            #quantity: quantity,
          },
        ),
        returnValue: _i13.Future<_i3.PaymentResult>.value(_FakePaymentResult_1(
          this,
          Invocation.method(
            #purchaseEventTicket,
            [],
            {
              #eventId: eventId,
              #userId: userId,
              #ticketPrice: ticketPrice,
              #quantity: quantity,
            },
          ),
        )),
      ) as _i13.Future<_i3.PaymentResult>);

  @override
  _i4.RevenueSplit calculateRevenueSplit({
    required double? totalAmount,
    required int? ticketsSold,
    required String? eventId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateRevenueSplit,
          [],
          {
            #totalAmount: totalAmount,
            #ticketsSold: ticketsSold,
            #eventId: eventId,
          },
        ),
        returnValue: _FakeRevenueSplit_2(
          this,
          Invocation.method(
            #calculateRevenueSplit,
            [],
            {
              #totalAmount: totalAmount,
              #ticketsSold: ticketsSold,
              #eventId: eventId,
            },
          ),
        ),
      ) as _i4.RevenueSplit);

  @override
  _i13.Future<_i5.Payment> confirmPayment({
    required String? paymentId,
    required String? paymentIntentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmPayment,
          [],
          {
            #paymentId: paymentId,
            #paymentIntentId: paymentIntentId,
          },
        ),
        returnValue: _i13.Future<_i5.Payment>.value(_FakePayment_3(
          this,
          Invocation.method(
            #confirmPayment,
            [],
            {
              #paymentId: paymentId,
              #paymentIntentId: paymentIntentId,
            },
          ),
        )),
      ) as _i13.Future<_i5.Payment>);

  @override
  _i13.Future<void> handlePaymentFailure({
    required String? paymentId,
    required String? errorMessage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #handlePaymentFailure,
          [],
          {
            #paymentId: paymentId,
            #errorMessage: errorMessage,
          },
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i5.Payment? getPayment(String? paymentId) =>
      (super.noSuchMethod(Invocation.method(
        #getPayment,
        [paymentId],
      )) as _i5.Payment?);

  @override
  void upsertPaymentForTests(_i5.Payment? payment) => super.noSuchMethod(
        Invocation.method(
          #upsertPaymentForTests,
          [payment],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i14.PaymentIntent? getPaymentIntent(String? paymentIntentId) =>
      (super.noSuchMethod(Invocation.method(
        #getPaymentIntent,
        [paymentIntentId],
      )) as _i14.PaymentIntent?);

  @override
  List<_i5.Payment> getPaymentsForEvent(String? eventId) => (super.noSuchMethod(
        Invocation.method(
          #getPaymentsForEvent,
          [eventId],
        ),
        returnValue: <_i5.Payment>[],
      ) as List<_i5.Payment>);

  @override
  _i5.Payment? getPaymentForEventAndUser(
    String? eventId,
    String? userId,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getPaymentForEventAndUser,
        [
          eventId,
          userId,
        ],
      )) as _i5.Payment?);

  @override
  List<_i5.Payment> getPaymentsForUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getPaymentsForUser,
          [userId],
        ),
        returnValue: <_i5.Payment>[],
      ) as List<_i5.Payment>);

  @override
  List<_i5.Payment> getPaymentsForUserInYear(
    String? userId,
    int? year,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaymentsForUserInYear,
          [
            userId,
            year,
          ],
        ),
        returnValue: <_i5.Payment>[],
      ) as List<_i5.Payment>);

  @override
  _i13.Future<bool> hasPartnership(String? eventId) => (super.noSuchMethod(
        Invocation.method(
          #hasPartnership,
          [eventId],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<_i4.RevenueSplit> calculatePartnershipRevenueSplit({
    required String? eventId,
    required double? totalAmount,
    required int? ticketsSold,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculatePartnershipRevenueSplit,
          [],
          {
            #eventId: eventId,
            #totalAmount: totalAmount,
            #ticketsSold: ticketsSold,
          },
        ),
        returnValue: _i13.Future<_i4.RevenueSplit>.value(_FakeRevenueSplit_2(
          this,
          Invocation.method(
            #calculatePartnershipRevenueSplit,
            [],
            {
              #eventId: eventId,
              #totalAmount: totalAmount,
              #ticketsSold: ticketsSold,
            },
          ),
        )),
      ) as _i13.Future<_i4.RevenueSplit>);

  @override
  _i13.Future<Map<String, double>> distributePartnershipPayment({
    required String? paymentId,
    required String? partnershipId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #distributePartnershipPayment,
          [],
          {
            #paymentId: paymentId,
            #partnershipId: partnershipId,
          },
        ),
        returnValue: _i13.Future<Map<String, double>>.value(<String, double>{}),
      ) as _i13.Future<Map<String, double>>);
}

/// A class which mocks [ExpertiseEventService].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpertiseEventService extends _i1.Mock
    implements _i15.ExpertiseEventService {
  MockExpertiseEventService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i6.ExpertiseEvent> createEvent({
    required _i16.UnifiedUser? host,
    required String? title,
    required String? description,
    required String? category,
    required _i6.ExpertiseEventType? eventType,
    required DateTime? startTime,
    required DateTime? endTime,
    List<_i17.Spot>? spots,
    String? location,
    double? latitude,
    double? longitude,
    int? maxAttendees = 20,
    double? price,
    bool? isPublic = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEvent,
          [],
          {
            #host: host,
            #title: title,
            #description: description,
            #category: category,
            #eventType: eventType,
            #startTime: startTime,
            #endTime: endTime,
            #spots: spots,
            #location: location,
            #latitude: latitude,
            #longitude: longitude,
            #maxAttendees: maxAttendees,
            #price: price,
            #isPublic: isPublic,
          },
        ),
        returnValue:
            _i13.Future<_i6.ExpertiseEvent>.value(_FakeExpertiseEvent_4(
          this,
          Invocation.method(
            #createEvent,
            [],
            {
              #host: host,
              #title: title,
              #description: description,
              #category: category,
              #eventType: eventType,
              #startTime: startTime,
              #endTime: endTime,
              #spots: spots,
              #location: location,
              #latitude: latitude,
              #longitude: longitude,
              #maxAttendees: maxAttendees,
              #price: price,
              #isPublic: isPublic,
            },
          ),
        )),
      ) as _i13.Future<_i6.ExpertiseEvent>);

  @override
  _i13.Future<_i6.ExpertiseEvent> duplicateEvent({
    required _i6.ExpertiseEvent? originalEvent,
    DateTime? newStartTime,
    bool? autoSuggestTime = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #duplicateEvent,
          [],
          {
            #originalEvent: originalEvent,
            #newStartTime: newStartTime,
            #autoSuggestTime: autoSuggestTime,
          },
        ),
        returnValue:
            _i13.Future<_i6.ExpertiseEvent>.value(_FakeExpertiseEvent_4(
          this,
          Invocation.method(
            #duplicateEvent,
            [],
            {
              #originalEvent: originalEvent,
              #newStartTime: newStartTime,
              #autoSuggestTime: autoSuggestTime,
            },
          ),
        )),
      ) as _i13.Future<_i6.ExpertiseEvent>);

  @override
  _i13.Future<void> registerForEvent(
    _i6.ExpertiseEvent? event,
    _i16.UnifiedUser? user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerForEvent,
          [
            event,
            user,
          ],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> cancelRegistration(
    _i6.ExpertiseEvent? event,
    _i16.UnifiedUser? user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelRegistration,
          [
            event,
            user,
          ],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<List<_i6.ExpertiseEvent>> getEventsByHost(
          _i16.UnifiedUser? host) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsByHost,
          [host],
        ),
        returnValue:
            _i13.Future<List<_i6.ExpertiseEvent>>.value(<_i6.ExpertiseEvent>[]),
      ) as _i13.Future<List<_i6.ExpertiseEvent>>);

  @override
  _i13.Future<List<_i6.ExpertiseEvent>> getEventsByAttendee(
          _i16.UnifiedUser? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsByAttendee,
          [user],
        ),
        returnValue:
            _i13.Future<List<_i6.ExpertiseEvent>>.value(<_i6.ExpertiseEvent>[]),
      ) as _i13.Future<List<_i6.ExpertiseEvent>>);

  @override
  _i13.Future<_i6.ExpertiseEvent?> getEventById(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventById,
          [eventId],
        ),
        returnValue: _i13.Future<_i6.ExpertiseEvent?>.value(),
      ) as _i13.Future<_i6.ExpertiseEvent?>);

  @override
  _i13.Future<List<_i6.ExpertiseEvent>> searchEvents({
    String? category,
    String? location,
    _i6.ExpertiseEventType? eventType,
    DateTime? startDate,
    DateTime? endDate,
    int? maxResults = 20,
    bool? includeCommunityEvents = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEvents,
          [],
          {
            #category: category,
            #location: location,
            #eventType: eventType,
            #startDate: startDate,
            #endDate: endDate,
            #maxResults: maxResults,
            #includeCommunityEvents: includeCommunityEvents,
          },
        ),
        returnValue:
            _i13.Future<List<_i6.ExpertiseEvent>>.value(<_i6.ExpertiseEvent>[]),
      ) as _i13.Future<List<_i6.ExpertiseEvent>>);

  @override
  _i13.Future<List<_i6.ExpertiseEvent>> getUpcomingEventsInCategory(
    String? category, {
    int? maxResults = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUpcomingEventsInCategory,
          [category],
          {#maxResults: maxResults},
        ),
        returnValue:
            _i13.Future<List<_i6.ExpertiseEvent>>.value(<_i6.ExpertiseEvent>[]),
      ) as _i13.Future<List<_i6.ExpertiseEvent>>);

  @override
  _i13.Future<List<_i6.ExpertiseEvent>> searchEventsWithConnectedLocalities({
    required _i16.UnifiedUser? user,
    String? category,
    String? location,
    _i6.ExpertiseEventType? eventType,
    DateTime? startDate,
    DateTime? endDate,
    int? maxResults = 20,
    bool? includeConnectedLocalities = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEventsWithConnectedLocalities,
          [],
          {
            #user: user,
            #category: category,
            #location: location,
            #eventType: eventType,
            #startDate: startDate,
            #endDate: endDate,
            #maxResults: maxResults,
            #includeConnectedLocalities: includeConnectedLocalities,
          },
        ),
        returnValue:
            _i13.Future<List<_i6.ExpertiseEvent>>.value(<_i6.ExpertiseEvent>[]),
      ) as _i13.Future<List<_i6.ExpertiseEvent>>);

  @override
  _i13.Future<void> updateEventStatus(
    _i6.ExpertiseEvent? event,
    _i6.EventStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEventStatus,
          [
            event,
            status,
          ],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);
}

/// A class which mocks [StripeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStripeService extends _i1.Mock implements _i2.StripeService {
  MockStripeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i13.Future<void> initializeStripe() => (super.noSuchMethod(
        Invocation.method(
          #initializeStripe,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<String> createPaymentIntent({
    required int? amount,
    String? currency = 'usd',
    Map<String, String>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPaymentIntent,
          [],
          {
            #amount: amount,
            #currency: currency,
            #metadata: metadata,
          },
        ),
        returnValue: _i13.Future<String>.value(_i18.dummyValue<String>(
          this,
          Invocation.method(
            #createPaymentIntent,
            [],
            {
              #amount: amount,
              #currency: currency,
              #metadata: metadata,
            },
          ),
        )),
      ) as _i13.Future<String>);

  @override
  _i13.Future<_i7.PaymentIntent> confirmPayment({
    required String? clientSecret,
    String? paymentMethodId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmPayment,
          [],
          {
            #clientSecret: clientSecret,
            #paymentMethodId: paymentMethodId,
          },
        ),
        returnValue: _i13.Future<_i7.PaymentIntent>.value(_FakePaymentIntent_5(
          this,
          Invocation.method(
            #confirmPayment,
            [],
            {
              #clientSecret: clientSecret,
              #paymentMethodId: paymentMethodId,
            },
          ),
        )),
      ) as _i13.Future<_i7.PaymentIntent>);

  @override
  _i13.Future<String> processRefund({
    required String? paymentIntentId,
    int? amount,
    String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #processRefund,
          [],
          {
            #paymentIntentId: paymentIntentId,
            #amount: amount,
            #reason: reason,
          },
        ),
        returnValue: _i13.Future<String>.value(_i18.dummyValue<String>(
          this,
          Invocation.method(
            #processRefund,
            [],
            {
              #paymentIntentId: paymentIntentId,
              #amount: amount,
              #reason: reason,
            },
          ),
        )),
      ) as _i13.Future<String>);

  @override
  String handlePaymentError(dynamic error) => (super.noSuchMethod(
        Invocation.method(
          #handlePaymentError,
          [error],
        ),
        returnValue: _i18.dummyValue<String>(
          this,
          Invocation.method(
            #handlePaymentError,
            [error],
          ),
        ),
      ) as String);
}

/// A class which mocks [PartnershipService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPartnershipService extends _i1.Mock
    implements _i19.PartnershipService {
  MockPartnershipService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i8.EventPartnership> createPartnership({
    required String? eventId,
    required String? userId,
    required String? businessId,
    _i8.PartnershipAgreement? agreement,
    _i8.PartnershipType? type = _i8.PartnershipType.eventBased,
    List<String>? sharedResponsibilities,
    String? venueLocation,
    double? vibeCompatibilityScore,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPartnership,
          [],
          {
            #eventId: eventId,
            #userId: userId,
            #businessId: businessId,
            #agreement: agreement,
            #type: type,
            #sharedResponsibilities: sharedResponsibilities,
            #venueLocation: venueLocation,
            #vibeCompatibilityScore: vibeCompatibilityScore,
          },
        ),
        returnValue:
            _i13.Future<_i8.EventPartnership>.value(_FakeEventPartnership_6(
          this,
          Invocation.method(
            #createPartnership,
            [],
            {
              #eventId: eventId,
              #userId: userId,
              #businessId: businessId,
              #agreement: agreement,
              #type: type,
              #sharedResponsibilities: sharedResponsibilities,
              #venueLocation: venueLocation,
              #vibeCompatibilityScore: vibeCompatibilityScore,
            },
          ),
        )),
      ) as _i13.Future<_i8.EventPartnership>);

  @override
  _i13.Future<List<_i8.EventPartnership>> getPartnershipsForEvent(
          String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPartnershipsForEvent,
          [eventId],
        ),
        returnValue: _i13.Future<List<_i8.EventPartnership>>.value(
            <_i8.EventPartnership>[]),
      ) as _i13.Future<List<_i8.EventPartnership>>);

  @override
  _i13.Future<_i8.EventPartnership?> getPartnershipById(
          String? partnershipId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPartnershipById,
          [partnershipId],
        ),
        returnValue: _i13.Future<_i8.EventPartnership?>.value(),
      ) as _i13.Future<_i8.EventPartnership?>);

  @override
  _i13.Future<_i8.EventPartnership> updatePartnershipStatus({
    required String? partnershipId,
    required _i8.PartnershipStatus? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePartnershipStatus,
          [],
          {
            #partnershipId: partnershipId,
            #status: status,
          },
        ),
        returnValue:
            _i13.Future<_i8.EventPartnership>.value(_FakeEventPartnership_6(
          this,
          Invocation.method(
            #updatePartnershipStatus,
            [],
            {
              #partnershipId: partnershipId,
              #status: status,
            },
          ),
        )),
      ) as _i13.Future<_i8.EventPartnership>);

  @override
  _i13.Future<_i8.EventPartnership> approvePartnership({
    required String? partnershipId,
    required String? approvedBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #approvePartnership,
          [],
          {
            #partnershipId: partnershipId,
            #approvedBy: approvedBy,
          },
        ),
        returnValue:
            _i13.Future<_i8.EventPartnership>.value(_FakeEventPartnership_6(
          this,
          Invocation.method(
            #approvePartnership,
            [],
            {
              #partnershipId: partnershipId,
              #approvedBy: approvedBy,
            },
          ),
        )),
      ) as _i13.Future<_i8.EventPartnership>);

  @override
  _i13.Future<bool> checkPartnershipEligibility({
    required String? userId,
    required String? businessId,
    required String? eventId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkPartnershipEligibility,
          [],
          {
            #userId: userId,
            #businessId: businessId,
            #eventId: eventId,
          },
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<double> calculateVibeCompatibility({
    required String? userId,
    required String? businessId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateVibeCompatibility,
          [],
          {
            #userId: userId,
            #businessId: businessId,
          },
        ),
        returnValue: _i13.Future<double>.value(0.0),
      ) as _i13.Future<double>);
}

/// A class which mocks [PaymentEventService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentEventService extends _i1.Mock
    implements _i9.PaymentEventService {
  MockPaymentEventService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i9.PaymentEventResult> processEventPayment({
    required _i6.ExpertiseEvent? event,
    required _i16.UnifiedUser? user,
    int? quantity = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #processEventPayment,
          [],
          {
            #event: event,
            #user: user,
            #quantity: quantity,
          },
        ),
        returnValue:
            _i13.Future<_i9.PaymentEventResult>.value(_FakePaymentEventResult_7(
          this,
          Invocation.method(
            #processEventPayment,
            [],
            {
              #event: event,
              #user: user,
              #quantity: quantity,
            },
          ),
        )),
      ) as _i13.Future<_i9.PaymentEventResult>);

  @override
  _i13.Future<_i9.RefundResult> refundEventPayment({
    required String? paymentId,
    required String? eventId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #refundEventPayment,
          [],
          {
            #paymentId: paymentId,
            #eventId: eventId,
            #userId: userId,
          },
        ),
        returnValue: _i13.Future<_i9.RefundResult>.value(_FakeRefundResult_8(
          this,
          Invocation.method(
            #refundEventPayment,
            [],
            {
              #paymentId: paymentId,
              #eventId: eventId,
              #userId: userId,
            },
          ),
        )),
      ) as _i13.Future<_i9.RefundResult>);
}

/// A class which mocks [PartnershipMatchingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPartnershipMatchingService extends _i1.Mock
    implements _i20.PartnershipMatchingService {
  MockPartnershipMatchingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<List<_i20.PartnershipSuggestion>> findMatchingPartners({
    required String? userId,
    required String? eventId,
    double? minCompatibility = 0.7,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findMatchingPartners,
          [],
          {
            #userId: userId,
            #eventId: eventId,
            #minCompatibility: minCompatibility,
          },
        ),
        returnValue: _i13.Future<List<_i20.PartnershipSuggestion>>.value(
            <_i20.PartnershipSuggestion>[]),
      ) as _i13.Future<List<_i20.PartnershipSuggestion>>);

  @override
  _i13.Future<double> calculateCompatibility({
    required String? userId,
    required String? businessId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateCompatibility,
          [],
          {
            #userId: userId,
            #businessId: businessId,
          },
        ),
        returnValue: _i13.Future<double>.value(0.0),
      ) as _i13.Future<double>);

  @override
  _i13.Future<List<_i20.PartnershipSuggestion>> getSuggestions(
          {required String? eventId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSuggestions,
          [],
          {#eventId: eventId},
        ),
        returnValue: _i13.Future<List<_i20.PartnershipSuggestion>>.value(
            <_i20.PartnershipSuggestion>[]),
      ) as _i13.Future<List<_i20.PartnershipSuggestion>>);
}

/// A class which mocks [BusinessService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBusinessService extends _i1.Mock implements _i21.BusinessService {
  MockBusinessService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i10.BusinessAccount> createBusinessAccount({
    required String? name,
    required String? email,
    required String? businessType,
    required String? createdBy,
    String? description,
    String? website,
    String? location,
    String? phone,
    List<String>? categories,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBusinessAccount,
          [],
          {
            #name: name,
            #email: email,
            #businessType: businessType,
            #createdBy: createdBy,
            #description: description,
            #website: website,
            #location: location,
            #phone: phone,
            #categories: categories,
          },
        ),
        returnValue:
            _i13.Future<_i10.BusinessAccount>.value(_FakeBusinessAccount_9(
          this,
          Invocation.method(
            #createBusinessAccount,
            [],
            {
              #name: name,
              #email: email,
              #businessType: businessType,
              #createdBy: createdBy,
              #description: description,
              #website: website,
              #location: location,
              #phone: phone,
              #categories: categories,
            },
          ),
        )),
      ) as _i13.Future<_i10.BusinessAccount>);

  @override
  _i13.Future<_i11.BusinessVerification> verifyBusiness({
    required String? businessId,
    String? businessLicenseUrl,
    String? taxIdDocumentUrl,
    String? proofOfAddressUrl,
    String? websiteVerificationUrl,
    String? socialMediaVerificationUrl,
    String? legalBusinessName,
    String? taxId,
    String? businessAddress,
    String? phoneNumber,
    String? websiteUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyBusiness,
          [],
          {
            #businessId: businessId,
            #businessLicenseUrl: businessLicenseUrl,
            #taxIdDocumentUrl: taxIdDocumentUrl,
            #proofOfAddressUrl: proofOfAddressUrl,
            #websiteVerificationUrl: websiteVerificationUrl,
            #socialMediaVerificationUrl: socialMediaVerificationUrl,
            #legalBusinessName: legalBusinessName,
            #taxId: taxId,
            #businessAddress: businessAddress,
            #phoneNumber: phoneNumber,
            #websiteUrl: websiteUrl,
          },
        ),
        returnValue: _i13.Future<_i11.BusinessVerification>.value(
            _FakeBusinessVerification_10(
          this,
          Invocation.method(
            #verifyBusiness,
            [],
            {
              #businessId: businessId,
              #businessLicenseUrl: businessLicenseUrl,
              #taxIdDocumentUrl: taxIdDocumentUrl,
              #proofOfAddressUrl: proofOfAddressUrl,
              #websiteVerificationUrl: websiteVerificationUrl,
              #socialMediaVerificationUrl: socialMediaVerificationUrl,
              #legalBusinessName: legalBusinessName,
              #taxId: taxId,
              #businessAddress: businessAddress,
              #phoneNumber: phoneNumber,
              #websiteUrl: websiteUrl,
            },
          ),
        )),
      ) as _i13.Future<_i11.BusinessVerification>);

  @override
  _i13.Future<_i10.BusinessAccount> updateBusinessInfo({
    required String? businessId,
    String? name,
    String? description,
    String? website,
    String? location,
    String? phone,
    List<String>? categories,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBusinessInfo,
          [],
          {
            #businessId: businessId,
            #name: name,
            #description: description,
            #website: website,
            #location: location,
            #phone: phone,
            #categories: categories,
          },
        ),
        returnValue:
            _i13.Future<_i10.BusinessAccount>.value(_FakeBusinessAccount_9(
          this,
          Invocation.method(
            #updateBusinessInfo,
            [],
            {
              #businessId: businessId,
              #name: name,
              #description: description,
              #website: website,
              #location: location,
              #phone: phone,
              #categories: categories,
            },
          ),
        )),
      ) as _i13.Future<_i10.BusinessAccount>);

  @override
  _i13.Future<List<_i10.BusinessAccount>> findBusinesses({
    String? category,
    String? location,
    bool? verifiedOnly = false,
    int? maxResults = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findBusinesses,
          [],
          {
            #category: category,
            #location: location,
            #verifiedOnly: verifiedOnly,
            #maxResults: maxResults,
          },
        ),
        returnValue: _i13.Future<List<_i10.BusinessAccount>>.value(
            <_i10.BusinessAccount>[]),
      ) as _i13.Future<List<_i10.BusinessAccount>>);

  @override
  _i13.Future<bool> checkBusinessEligibility(String? businessId) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkBusinessEligibility,
          [businessId],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<_i10.BusinessAccount?> getBusinessById(String? businessId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBusinessById,
          [businessId],
        ),
        returnValue: _i13.Future<_i10.BusinessAccount?>.value(),
      ) as _i13.Future<_i10.BusinessAccount?>);

  @override
  _i13.Future<_i11.BusinessVerification?> getVerification(String? businessId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVerification,
          [businessId],
        ),
        returnValue: _i13.Future<_i11.BusinessVerification?>.value(),
      ) as _i13.Future<_i11.BusinessVerification?>);
}

/// A class which mocks [BusinessAccountService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBusinessAccountService extends _i1.Mock
    implements _i22.BusinessAccountService {
  MockBusinessAccountService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i10.BusinessAccount> createBusinessAccount({
    required _i16.UnifiedUser? creator,
    required String? name,
    required String? email,
    required String? businessType,
    String? description,
    String? website,
    String? location,
    String? phone,
    String? logoUrl,
    List<String>? categories,
    List<String>? requiredExpertise,
    List<String>? preferredCommunities,
    _i23.BusinessExpertPreferences? expertPreferences,
    _i24.BusinessPatronPreferences? patronPreferences,
    String? preferredLocation,
    int? minExpertLevel,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBusinessAccount,
          [],
          {
            #creator: creator,
            #name: name,
            #email: email,
            #businessType: businessType,
            #description: description,
            #website: website,
            #location: location,
            #phone: phone,
            #logoUrl: logoUrl,
            #categories: categories,
            #requiredExpertise: requiredExpertise,
            #preferredCommunities: preferredCommunities,
            #expertPreferences: expertPreferences,
            #patronPreferences: patronPreferences,
            #preferredLocation: preferredLocation,
            #minExpertLevel: minExpertLevel,
          },
        ),
        returnValue:
            _i13.Future<_i10.BusinessAccount>.value(_FakeBusinessAccount_9(
          this,
          Invocation.method(
            #createBusinessAccount,
            [],
            {
              #creator: creator,
              #name: name,
              #email: email,
              #businessType: businessType,
              #description: description,
              #website: website,
              #location: location,
              #phone: phone,
              #logoUrl: logoUrl,
              #categories: categories,
              #requiredExpertise: requiredExpertise,
              #preferredCommunities: preferredCommunities,
              #expertPreferences: expertPreferences,
              #patronPreferences: patronPreferences,
              #preferredLocation: preferredLocation,
              #minExpertLevel: minExpertLevel,
            },
          ),
        )),
      ) as _i13.Future<_i10.BusinessAccount>);

  @override
  _i13.Future<_i10.BusinessAccount> updateBusinessAccount(
    _i10.BusinessAccount? account, {
    String? name,
    String? description,
    String? website,
    String? location,
    String? phone,
    String? logoUrl,
    List<String>? categories,
    List<String>? requiredExpertise,
    List<String>? preferredCommunities,
    _i23.BusinessExpertPreferences? expertPreferences,
    _i24.BusinessPatronPreferences? patronPreferences,
    String? preferredLocation,
    int? minExpertLevel,
    bool? isVerified,
    bool? isActive,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBusinessAccount,
          [account],
          {
            #name: name,
            #description: description,
            #website: website,
            #location: location,
            #phone: phone,
            #logoUrl: logoUrl,
            #categories: categories,
            #requiredExpertise: requiredExpertise,
            #preferredCommunities: preferredCommunities,
            #expertPreferences: expertPreferences,
            #patronPreferences: patronPreferences,
            #preferredLocation: preferredLocation,
            #minExpertLevel: minExpertLevel,
            #isVerified: isVerified,
            #isActive: isActive,
          },
        ),
        returnValue:
            _i13.Future<_i10.BusinessAccount>.value(_FakeBusinessAccount_9(
          this,
          Invocation.method(
            #updateBusinessAccount,
            [account],
            {
              #name: name,
              #description: description,
              #website: website,
              #location: location,
              #phone: phone,
              #logoUrl: logoUrl,
              #categories: categories,
              #requiredExpertise: requiredExpertise,
              #preferredCommunities: preferredCommunities,
              #expertPreferences: expertPreferences,
              #patronPreferences: patronPreferences,
              #preferredLocation: preferredLocation,
              #minExpertLevel: minExpertLevel,
              #isVerified: isVerified,
              #isActive: isActive,
            },
          ),
        )),
      ) as _i13.Future<_i10.BusinessAccount>);

  @override
  _i13.Future<_i10.BusinessAccount?> getBusinessAccount(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBusinessAccount,
          [id],
        ),
        returnValue: _i13.Future<_i10.BusinessAccount?>.value(),
      ) as _i13.Future<_i10.BusinessAccount?>);

  @override
  _i13.Future<List<_i10.BusinessAccount>> getBusinessAccountsByUser(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBusinessAccountsByUser,
          [userId],
        ),
        returnValue: _i13.Future<List<_i10.BusinessAccount>>.value(
            <_i10.BusinessAccount>[]),
      ) as _i13.Future<List<_i10.BusinessAccount>>);

  @override
  _i13.Future<_i10.BusinessAccount> addExpertConnection(
    _i10.BusinessAccount? account,
    String? expertId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addExpertConnection,
          [
            account,
            expertId,
          ],
        ),
        returnValue:
            _i13.Future<_i10.BusinessAccount>.value(_FakeBusinessAccount_9(
          this,
          Invocation.method(
            #addExpertConnection,
            [
              account,
              expertId,
            ],
          ),
        )),
      ) as _i13.Future<_i10.BusinessAccount>);

  @override
  _i13.Future<_i10.BusinessAccount> requestExpertConnection(
    _i10.BusinessAccount? account,
    String? expertId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestExpertConnection,
          [
            account,
            expertId,
          ],
        ),
        returnValue:
            _i13.Future<_i10.BusinessAccount>.value(_FakeBusinessAccount_9(
          this,
          Invocation.method(
            #requestExpertConnection,
            [
              account,
              expertId,
            ],
          ),
        )),
      ) as _i13.Future<_i10.BusinessAccount>);
}
