name: SPOTS
repository: https://github.com/yourusername/spots

packages:
  - packages/**

command:
  version:
    workspaceChangelog: true
  bootstrap:
    usePubspecOverrides: true
    hooks:
      pre: echo "🚀 Bootstrapping SPOTS workspace..."
      post: echo "✅ Bootstrap complete!"

scripts:
  # Analysis
  analyze:
    run: flutter analyze
    description: Analyze all packages
    exec:
      concurrency: 6
  
  # Testing
  test:
    run: flutter test
    description: Test all packages
    exec:
      concurrency: 4
  
  test:network:
    run: flutter test
    description: Test network module only
    packageFilters:
      scope: "spots_network"
  
  test:core:
    run: flutter test
    description: Test core module only
    packageFilters:
      scope: "spots_core"
  
  test:data:
    run: flutter test
    description: Test data module only
    packageFilters:
      scope: "spots_data"
  
  test:ai:
    run: flutter test
    description: Test AI module only
    packageFilters:
      scope: "spots_ai"
  
  test:ml:
    run: flutter test
    description: Test ML module only
    packageFilters:
      scope: "spots_ml"
  
  # Building
  build:
    run: flutter build apk
    description: Build main app
    packageFilters:
      scope: "spots_app"
  
  # Dependency management
  deps:get:
    run: flutter pub get
    description: Get dependencies for all packages
    exec:
      concurrency: 6
  
  deps:upgrade:
    run: flutter pub upgrade
    description: Upgrade dependencies for all packages
    exec:
      concurrency: 6
  
  # Code generation
  codegen:
    run: dart run build_runner build --delete-conflicting-outputs
    description: Generate code for all packages
    exec:
      concurrency: 2
  
  # Cleanup
  clean:
    run: flutter clean
    description: Clean all packages
    exec:
      concurrency: 6
