// Mocks generated by Mockito 5.4.6 from annotations
// in avrai/test/unit/services/ai_command_processor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:avrai/core/services/llm_service.dart' as _i6;
import 'package:connectivity_plus/connectivity_plus.dart' as _i3;
import 'package:flutter/foundation.dart' as _i5;
import 'package:flutter/src/widgets/framework.dart' as _i4;
import 'package:flutter/src/widgets/notification_listener.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSupabaseClient_0 extends _i1.SmartFake
    implements _i2.SupabaseClient {
  _FakeSupabaseClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConnectivity_1 extends _i1.SmartFake implements _i3.Connectivity {
  _FakeConnectivity_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWidget_2 extends _i1.SmartFake implements _i4.Widget {
  _FakeWidget_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i5.DiagnosticLevel? minLevel = _i5.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeInheritedWidget_3 extends _i1.SmartFake
    implements _i4.InheritedWidget {
  _FakeInheritedWidget_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i5.DiagnosticLevel? minLevel = _i5.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeDiagnosticsNode_4 extends _i1.SmartFake
    implements _i5.DiagnosticsNode {
  _FakeDiagnosticsNode_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({
    _i5.TextTreeConfiguration? parentConfiguration,
    _i5.DiagnosticLevel? minLevel = _i5.DiagnosticLevel.info,
  }) =>
      super.toString();
}

/// A class which mocks [LLMService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLLMService extends _i1.Mock implements _i6.LLMService {
  MockLLMService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SupabaseClient get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeSupabaseClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.SupabaseClient);

  @override
  _i3.Connectivity get connectivity => (super.noSuchMethod(
        Invocation.getter(#connectivity),
        returnValue: _FakeConnectivity_1(
          this,
          Invocation.getter(#connectivity),
        ),
      ) as _i3.Connectivity);

  @override
  _i7.Future<String> chat({
    required List<_i6.ChatMessage>? messages,
    _i6.LLMContext? context,
    double? temperature = 0.7,
    int? maxTokens = 500,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #chat,
          [],
          {
            #messages: messages,
            #context: context,
            #temperature: temperature,
            #maxTokens: maxTokens,
            #timeout: timeout,
          },
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #chat,
            [],
            {
              #messages: messages,
              #context: context,
              #temperature: temperature,
              #maxTokens: maxTokens,
              #timeout: timeout,
            },
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> generateRecommendation({
    required String? userQuery,
    _i6.LLMContext? userContext,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateRecommendation,
          [],
          {
            #userQuery: userQuery,
            #userContext: userContext,
          },
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #generateRecommendation,
            [],
            {
              #userQuery: userQuery,
              #userContext: userContext,
            },
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> continueConversation({
    required List<_i6.ChatMessage>? conversationHistory,
    required String? userMessage,
    _i6.LLMContext? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #continueConversation,
          [],
          {
            #conversationHistory: conversationHistory,
            #userMessage: userMessage,
            #context: context,
          },
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #continueConversation,
            [],
            {
              #conversationHistory: conversationHistory,
              #userMessage: userMessage,
              #context: context,
            },
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<List<String>> suggestListNames({
    required String? userIntent,
    _i6.LLMContext? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #suggestListNames,
          [],
          {
            #userIntent: userIntent,
            #context: context,
          },
        ),
        returnValue: _i7.Future<List<String>>.value(<String>[]),
      ) as _i7.Future<List<String>>);

  @override
  _i7.Future<String> generateSpotRecommendations({
    required String? query,
    _i6.LLMContext? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateSpotRecommendations,
          [],
          {
            #query: query,
            #context: context,
          },
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #generateSpotRecommendations,
            [],
            {
              #query: query,
              #context: context,
            },
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> generateWithContext({
    required String? query,
    required String? userId,
    List<_i6.ChatMessage>? messages,
    double? temperature = 0.7,
    int? maxTokens = 500,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateWithContext,
          [],
          {
            #query: query,
            #userId: userId,
            #messages: messages,
            #temperature: temperature,
            #maxTokens: maxTokens,
          },
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #generateWithContext,
            [],
            {
              #query: query,
              #userId: userId,
              #messages: messages,
              #temperature: temperature,
              #maxTokens: maxTokens,
            },
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Stream<String> chatStream({
    required List<_i6.ChatMessage>? messages,
    _i6.LLMContext? context,
    double? temperature = 0.7,
    int? maxTokens = 500,
    bool? useRealSSE = true,
    bool? autoFallback = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #chatStream,
          [],
          {
            #messages: messages,
            #context: context,
            #temperature: temperature,
            #maxTokens: maxTokens,
            #useRealSSE: useRealSSE,
            #autoFallback: autoFallback,
          },
        ),
        returnValue: _i7.Stream<String>.empty(),
      ) as _i7.Stream<String>);
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i3.Connectivity {
  MockConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<List<_i3.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onConnectivityChanged),
        returnValue: _i7.Stream<List<_i3.ConnectivityResult>>.empty(),
      ) as _i7.Stream<List<_i3.ConnectivityResult>>);

  @override
  _i7.Future<List<_i3.ConnectivityResult>> checkConnectivity() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkConnectivity,
          [],
        ),
        returnValue: _i7.Future<List<_i3.ConnectivityResult>>.value(
            <_i3.ConnectivityResult>[]),
      ) as _i7.Future<List<_i3.ConnectivityResult>>);
}

/// A class which mocks [BuildContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuildContext extends _i1.Mock implements _i4.BuildContext {
  MockBuildContext() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Widget get widget => (super.noSuchMethod(
        Invocation.getter(#widget),
        returnValue: _FakeWidget_2(
          this,
          Invocation.getter(#widget),
        ),
      ) as _i4.Widget);

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  bool get debugDoingBuild => (super.noSuchMethod(
        Invocation.getter(#debugDoingBuild),
        returnValue: false,
      ) as bool);

  @override
  _i4.InheritedWidget dependOnInheritedElement(
    _i4.InheritedElement? ancestor, {
    Object? aspect,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #dependOnInheritedElement,
          [ancestor],
          {#aspect: aspect},
        ),
        returnValue: _FakeInheritedWidget_3(
          this,
          Invocation.method(
            #dependOnInheritedElement,
            [ancestor],
            {#aspect: aspect},
          ),
        ),
      ) as _i4.InheritedWidget);

  @override
  void visitAncestorElements(_i4.ConditionalElementVisitor? visitor) =>
      super.noSuchMethod(
        Invocation.method(
          #visitAncestorElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void visitChildElements(_i4.ElementVisitor? visitor) => super.noSuchMethod(
        Invocation.method(
          #visitChildElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispatchNotification(_i9.Notification? notification) =>
      super.noSuchMethod(
        Invocation.method(
          #dispatchNotification,
          [notification],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.DiagnosticsNode describeElement(
    String? name, {
    _i5.DiagnosticsTreeStyle? style = _i5.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeElement,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_4(
          this,
          Invocation.method(
            #describeElement,
            [name],
            {#style: style},
          ),
        ),
      ) as _i5.DiagnosticsNode);

  @override
  _i5.DiagnosticsNode describeWidget(
    String? name, {
    _i5.DiagnosticsTreeStyle? style = _i5.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeWidget,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_4(
          this,
          Invocation.method(
            #describeWidget,
            [name],
            {#style: style},
          ),
        ),
      ) as _i5.DiagnosticsNode);

  @override
  List<_i5.DiagnosticsNode> describeMissingAncestor(
          {required Type? expectedAncestorType}) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeMissingAncestor,
          [],
          {#expectedAncestorType: expectedAncestorType},
        ),
        returnValue: <_i5.DiagnosticsNode>[],
      ) as List<_i5.DiagnosticsNode>);

  @override
  _i5.DiagnosticsNode describeOwnershipChain(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeOwnershipChain,
          [name],
        ),
        returnValue: _FakeDiagnosticsNode_4(
          this,
          Invocation.method(
            #describeOwnershipChain,
            [name],
          ),
        ),
      ) as _i5.DiagnosticsNode);
}
