// Mocks generated by Mockito 5.4.6 from annotations
// in spots/test/unit/services/event_recommendation_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:spots/core/models/expertise_event.dart' as _i4;
import 'package:spots/core/models/spot.dart' as _i8;
import 'package:spots/core/models/unified_user.dart' as _i6;
import 'package:spots/core/services/event_matching_service.dart' as _i3;
import 'package:spots/core/services/expertise_event_service.dart' as _i7;
import 'package:spots/core/services/user_preference_learning_service.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserPreferences_0 extends _i1.SmartFake
    implements _i2.UserPreferences {
  _FakeUserPreferences_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMatchingSignals_1 extends _i1.SmartFake
    implements _i3.MatchingSignals {
  _FakeMatchingSignals_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExpertiseEvent_2 extends _i1.SmartFake
    implements _i4.ExpertiseEvent {
  _FakeExpertiseEvent_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserPreferenceLearningService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserPreferenceLearningService extends _i1.Mock
    implements _i2.UserPreferenceLearningService {
  MockUserPreferenceLearningService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.UserPreferences> learnUserPreferences(
          {required _i6.UnifiedUser? user}) =>
      (super.noSuchMethod(
        Invocation.method(
          #learnUserPreferences,
          [],
          {#user: user},
        ),
        returnValue:
            _i5.Future<_i2.UserPreferences>.value(_FakeUserPreferences_0(
          this,
          Invocation.method(
            #learnUserPreferences,
            [],
            {#user: user},
          ),
        )),
      ) as _i5.Future<_i2.UserPreferences>);

  @override
  _i5.Future<_i2.UserPreferences> getUserPreferences(
          {required _i6.UnifiedUser? user}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserPreferences,
          [],
          {#user: user},
        ),
        returnValue:
            _i5.Future<_i2.UserPreferences>.value(_FakeUserPreferences_0(
          this,
          Invocation.method(
            #getUserPreferences,
            [],
            {#user: user},
          ),
        )),
      ) as _i5.Future<_i2.UserPreferences>);

  @override
  _i5.Future<List<_i2.ExplorationOpportunity>> suggestExplorationEvents({
    required _i6.UnifiedUser? user,
    int? maxSuggestions = 5,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #suggestExplorationEvents,
          [],
          {
            #user: user,
            #maxSuggestions: maxSuggestions,
          },
        ),
        returnValue: _i5.Future<List<_i2.ExplorationOpportunity>>.value(
            <_i2.ExplorationOpportunity>[]),
      ) as _i5.Future<List<_i2.ExplorationOpportunity>>);
}

/// A class which mocks [EventMatchingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventMatchingService extends _i1.Mock
    implements _i3.EventMatchingService {
  MockEventMatchingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<double> calculateMatchingScore({
    required _i6.UnifiedUser? expert,
    required _i6.UnifiedUser? user,
    required String? category,
    required String? locality,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateMatchingScore,
          [],
          {
            #expert: expert,
            #user: user,
            #category: category,
            #locality: locality,
          },
        ),
        returnValue: _i5.Future<double>.value(0.0),
      ) as _i5.Future<double>);

  @override
  _i5.Future<_i3.MatchingSignals> getMatchingSignals({
    required _i6.UnifiedUser? expert,
    required _i6.UnifiedUser? user,
    required String? category,
    required String? locality,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMatchingSignals,
          [],
          {
            #expert: expert,
            #user: user,
            #category: category,
            #locality: locality,
          },
        ),
        returnValue:
            _i5.Future<_i3.MatchingSignals>.value(_FakeMatchingSignals_1(
          this,
          Invocation.method(
            #getMatchingSignals,
            [],
            {
              #expert: expert,
              #user: user,
              #category: category,
              #locality: locality,
            },
          ),
        )),
      ) as _i5.Future<_i3.MatchingSignals>);
}

/// A class which mocks [ExpertiseEventService].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpertiseEventService extends _i1.Mock
    implements _i7.ExpertiseEventService {
  MockExpertiseEventService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i4.ExpertiseEvent> createEvent({
    required _i6.UnifiedUser? host,
    required String? title,
    required String? description,
    required String? category,
    required _i4.ExpertiseEventType? eventType,
    required DateTime? startTime,
    required DateTime? endTime,
    List<_i8.Spot>? spots,
    String? location,
    double? latitude,
    double? longitude,
    int? maxAttendees = 20,
    double? price,
    bool? isPublic = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEvent,
          [],
          {
            #host: host,
            #title: title,
            #description: description,
            #category: category,
            #eventType: eventType,
            #startTime: startTime,
            #endTime: endTime,
            #spots: spots,
            #location: location,
            #latitude: latitude,
            #longitude: longitude,
            #maxAttendees: maxAttendees,
            #price: price,
            #isPublic: isPublic,
          },
        ),
        returnValue: _i5.Future<_i4.ExpertiseEvent>.value(_FakeExpertiseEvent_2(
          this,
          Invocation.method(
            #createEvent,
            [],
            {
              #host: host,
              #title: title,
              #description: description,
              #category: category,
              #eventType: eventType,
              #startTime: startTime,
              #endTime: endTime,
              #spots: spots,
              #location: location,
              #latitude: latitude,
              #longitude: longitude,
              #maxAttendees: maxAttendees,
              #price: price,
              #isPublic: isPublic,
            },
          ),
        )),
      ) as _i5.Future<_i4.ExpertiseEvent>);

  @override
  _i5.Future<_i4.ExpertiseEvent> duplicateEvent({
    required _i4.ExpertiseEvent? originalEvent,
    DateTime? newStartTime,
    bool? autoSuggestTime = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #duplicateEvent,
          [],
          {
            #originalEvent: originalEvent,
            #newStartTime: newStartTime,
            #autoSuggestTime: autoSuggestTime,
          },
        ),
        returnValue: _i5.Future<_i4.ExpertiseEvent>.value(_FakeExpertiseEvent_2(
          this,
          Invocation.method(
            #duplicateEvent,
            [],
            {
              #originalEvent: originalEvent,
              #newStartTime: newStartTime,
              #autoSuggestTime: autoSuggestTime,
            },
          ),
        )),
      ) as _i5.Future<_i4.ExpertiseEvent>);

  @override
  _i5.Future<void> registerForEvent(
    _i4.ExpertiseEvent? event,
    _i6.UnifiedUser? user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerForEvent,
          [
            event,
            user,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cancelRegistration(
    _i4.ExpertiseEvent? event,
    _i6.UnifiedUser? user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelRegistration,
          [
            event,
            user,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i4.ExpertiseEvent>> getEventsByHost(_i6.UnifiedUser? host) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsByHost,
          [host],
        ),
        returnValue:
            _i5.Future<List<_i4.ExpertiseEvent>>.value(<_i4.ExpertiseEvent>[]),
      ) as _i5.Future<List<_i4.ExpertiseEvent>>);

  @override
  _i5.Future<List<_i4.ExpertiseEvent>> getEventsByAttendee(
          _i6.UnifiedUser? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsByAttendee,
          [user],
        ),
        returnValue:
            _i5.Future<List<_i4.ExpertiseEvent>>.value(<_i4.ExpertiseEvent>[]),
      ) as _i5.Future<List<_i4.ExpertiseEvent>>);

  @override
  _i5.Future<_i4.ExpertiseEvent?> getEventById(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventById,
          [eventId],
        ),
        returnValue: _i5.Future<_i4.ExpertiseEvent?>.value(),
      ) as _i5.Future<_i4.ExpertiseEvent?>);

  @override
  _i5.Future<List<_i4.ExpertiseEvent>> searchEvents({
    String? category,
    String? location,
    _i4.ExpertiseEventType? eventType,
    DateTime? startDate,
    DateTime? endDate,
    int? maxResults = 20,
    bool? includeCommunityEvents = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEvents,
          [],
          {
            #category: category,
            #location: location,
            #eventType: eventType,
            #startDate: startDate,
            #endDate: endDate,
            #maxResults: maxResults,
            #includeCommunityEvents: includeCommunityEvents,
          },
        ),
        returnValue:
            _i5.Future<List<_i4.ExpertiseEvent>>.value(<_i4.ExpertiseEvent>[]),
      ) as _i5.Future<List<_i4.ExpertiseEvent>>);

  @override
  _i5.Future<List<_i4.ExpertiseEvent>> getUpcomingEventsInCategory(
    String? category, {
    int? maxResults = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUpcomingEventsInCategory,
          [category],
          {#maxResults: maxResults},
        ),
        returnValue:
            _i5.Future<List<_i4.ExpertiseEvent>>.value(<_i4.ExpertiseEvent>[]),
      ) as _i5.Future<List<_i4.ExpertiseEvent>>);

  @override
  _i5.Future<List<_i4.ExpertiseEvent>> searchEventsWithConnectedLocalities({
    required _i6.UnifiedUser? user,
    String? category,
    String? location,
    _i4.ExpertiseEventType? eventType,
    DateTime? startDate,
    DateTime? endDate,
    int? maxResults = 20,
    bool? includeConnectedLocalities = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEventsWithConnectedLocalities,
          [],
          {
            #user: user,
            #category: category,
            #location: location,
            #eventType: eventType,
            #startDate: startDate,
            #endDate: endDate,
            #maxResults: maxResults,
            #includeConnectedLocalities: includeConnectedLocalities,
          },
        ),
        returnValue:
            _i5.Future<List<_i4.ExpertiseEvent>>.value(<_i4.ExpertiseEvent>[]),
      ) as _i5.Future<List<_i4.ExpertiseEvent>>);

  @override
  _i5.Future<void> updateEventStatus(
    _i4.ExpertiseEvent? event,
    _i4.EventStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEventStatus,
          [
            event,
            status,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
