// Mocks generated by Mockito 5.4.6 from annotations
// in avrai/test/unit/services/ideal_state_learning_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:avrai/core/models/expertise_event.dart' as _i8;
import 'package:avrai/core/services/quantum/quantum_outcome_learning_service.dart'
    as _i4;
import 'package:avrai_core/models/atomic_timestamp.dart' as _i2;
import 'package:avrai_core/models/quantum_entity_state.dart' as _i7;
import 'package:avrai_core/services/atomic_clock_service.dart' as _i5;
import 'package:avrai_quantum/services/quantum/quantum_entanglement_service.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAtomicTimestamp_0 extends _i1.SmartFake
    implements _i2.AtomicTimestamp {
  _FakeAtomicTimestamp_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_1 extends _i1.SmartFake implements Duration {
  _FakeDuration_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEntangledQuantumState_2 extends _i1.SmartFake
    implements _i3.EntangledQuantumState {
  _FakeEntangledQuantumState_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuantumLearningData_3 extends _i1.SmartFake
    implements _i4.QuantumLearningData {
  _FakeQuantumLearningData_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePreferenceDriftResult_4 extends _i1.SmartFake
    implements _i4.PreferenceDriftResult {
  _FakePreferenceDriftResult_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AtomicClockService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAtomicClockService extends _i1.Mock
    implements _i5.AtomicClockService {
  MockAtomicClockService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void configure({_i6.Future<DateTime> Function()? serverTimeProvider}) =>
      super.noSuchMethod(
        Invocation.method(
          #configure,
          [],
          {#serverTimeProvider: serverTimeProvider},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> syncWithServer() => (super.noSuchMethod(
        Invocation.method(
          #syncWithServer,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i2.AtomicTimestamp> getAtomicTimestamp() => (super.noSuchMethod(
        Invocation.method(
          #getAtomicTimestamp,
          [],
        ),
        returnValue:
            _i6.Future<_i2.AtomicTimestamp>.value(_FakeAtomicTimestamp_0(
          this,
          Invocation.method(
            #getAtomicTimestamp,
            [],
          ),
        )),
      ) as _i6.Future<_i2.AtomicTimestamp>);

  @override
  Duration getTimeOffset() => (super.noSuchMethod(
        Invocation.method(
          #getTimeOffset,
          [],
        ),
        returnValue: _FakeDuration_1(
          this,
          Invocation.method(
            #getTimeOffset,
            [],
          ),
        ),
      ) as Duration);

  @override
  bool isSynchronized() => (super.noSuchMethod(
        Invocation.method(
          #isSynchronized,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i2.TimePrecision getPrecision() => (super.noSuchMethod(
        Invocation.method(
          #getPrecision,
          [],
        ),
        returnValue: _i2.TimePrecision.nanosecond,
      ) as _i2.TimePrecision);

  @override
  _i6.Future<_i2.AtomicTimestamp> getTicketPurchaseTimestamp() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTicketPurchaseTimestamp,
          [],
        ),
        returnValue:
            _i6.Future<_i2.AtomicTimestamp>.value(_FakeAtomicTimestamp_0(
          this,
          Invocation.method(
            #getTicketPurchaseTimestamp,
            [],
          ),
        )),
      ) as _i6.Future<_i2.AtomicTimestamp>);

  @override
  _i6.Future<_i2.AtomicTimestamp> getAI2AIConnectionTimestamp() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAI2AIConnectionTimestamp,
          [],
        ),
        returnValue:
            _i6.Future<_i2.AtomicTimestamp>.value(_FakeAtomicTimestamp_0(
          this,
          Invocation.method(
            #getAI2AIConnectionTimestamp,
            [],
          ),
        )),
      ) as _i6.Future<_i2.AtomicTimestamp>);

  @override
  _i6.Future<_i2.AtomicTimestamp> getLiveTrackingTimestamp() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLiveTrackingTimestamp,
          [],
        ),
        returnValue:
            _i6.Future<_i2.AtomicTimestamp>.value(_FakeAtomicTimestamp_0(
          this,
          Invocation.method(
            #getLiveTrackingTimestamp,
            [],
          ),
        )),
      ) as _i6.Future<_i2.AtomicTimestamp>);

  @override
  _i6.Future<_i2.AtomicTimestamp> getAdminOperationTimestamp() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAdminOperationTimestamp,
          [],
        ),
        returnValue:
            _i6.Future<_i2.AtomicTimestamp>.value(_FakeAtomicTimestamp_0(
          this,
          Invocation.method(
            #getAdminOperationTimestamp,
            [],
          ),
        )),
      ) as _i6.Future<_i2.AtomicTimestamp>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [QuantumEntanglementService].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuantumEntanglementService extends _i1.Mock
    implements _i3.QuantumEntanglementService {
  MockQuantumEntanglementService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.EntangledQuantumState> createEntangledState({
    required List<_i7.QuantumEntityState>? entityStates,
    List<double>? coefficients,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEntangledState,
          [],
          {
            #entityStates: entityStates,
            #coefficients: coefficients,
          },
        ),
        returnValue: _i6.Future<_i3.EntangledQuantumState>.value(
            _FakeEntangledQuantumState_2(
          this,
          Invocation.method(
            #createEntangledState,
            [],
            {
              #entityStates: entityStates,
              #coefficients: coefficients,
            },
          ),
        )),
      ) as _i6.Future<_i3.EntangledQuantumState>);

  @override
  _i6.Future<double> calculateFidelity(
    _i3.EntangledQuantumState? state1,
    _i3.EntangledQuantumState? state2,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateFidelity,
          [
            state1,
            state2,
          ],
        ),
        returnValue: _i6.Future<double>.value(0.0),
      ) as _i6.Future<double>);

  @override
  _i6.Future<double> calculateKnotCompatibilityBonus(
    List<_i7.QuantumEntityState>? entityStates, {
    DateTime? targetTime,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateKnotCompatibilityBonus,
          [entityStates],
          {#targetTime: targetTime},
        ),
        returnValue: _i6.Future<double>.value(0.0),
      ) as _i6.Future<double>);

  @override
  _i6.Future<bool> shareEntanglementInsightsViaMesh({
    required _i3.EntangledQuantumState? entangledState,
    double? fidelity,
    double? knotCompatibility,
    required String? sourceAgentId,
    required List<String>? entityTypes,
    required dynamic messageType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #shareEntanglementInsightsViaMesh,
          [],
          {
            #entangledState: entangledState,
            #fidelity: fidelity,
            #knotCompatibility: knotCompatibility,
            #sourceAgentId: sourceAgentId,
            #entityTypes: entityTypes,
            #messageType: messageType,
          },
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}

/// A class which mocks [QuantumOutcomeLearningService].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuantumOutcomeLearningService extends _i1.Mock
    implements _i4.QuantumOutcomeLearningService {
  MockQuantumOutcomeLearningService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.QuantumLearningData> learnFromOutcome({
    required String? eventId,
    required _i8.ExpertiseEvent? event,
    required List<_i7.QuantumEntityState>? entities,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #learnFromOutcome,
          [],
          {
            #eventId: eventId,
            #event: event,
            #entities: entities,
          },
        ),
        returnValue: _i6.Future<_i4.QuantumLearningData>.value(
            _FakeQuantumLearningData_3(
          this,
          Invocation.method(
            #learnFromOutcome,
            [],
            {
              #eventId: eventId,
              #event: event,
              #entities: entities,
            },
          ),
        )),
      ) as _i6.Future<_i4.QuantumLearningData>);

  @override
  _i6.Future<_i4.PreferenceDriftResult> detectPreferenceDrift(
          {required String? idealStateKey}) =>
      (super.noSuchMethod(
        Invocation.method(
          #detectPreferenceDrift,
          [],
          {#idealStateKey: idealStateKey},
        ),
        returnValue: _i6.Future<_i4.PreferenceDriftResult>.value(
            _FakePreferenceDriftResult_4(
          this,
          Invocation.method(
            #detectPreferenceDrift,
            [],
            {#idealStateKey: idealStateKey},
          ),
        )),
      ) as _i6.Future<_i4.PreferenceDriftResult>);

  @override
  _i6.Future<_i4.QuantumIdealState?> getIdealState(
          {required String? idealStateKey}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIdealState,
          [],
          {#idealStateKey: idealStateKey},
        ),
        returnValue: _i6.Future<_i4.QuantumIdealState?>.value(),
      ) as _i6.Future<_i4.QuantumIdealState?>);
}
