// Mocks generated by Mockito 5.4.6 from annotations
// in spots/test/unit/services/identity_verification_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:spots/core/models/tax_document.dart' as _i2;
import 'package:spots/core/models/tax_profile.dart' as _i3;
import 'package:spots/core/services/tax_compliance_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTaxDocument_0 extends _i1.SmartFake implements _i2.TaxDocument {
  _FakeTaxDocument_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTaxProfile_1 extends _i1.SmartFake implements _i3.TaxProfile {
  _FakeTaxProfile_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TaxComplianceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaxComplianceService extends _i1.Mock
    implements _i4.TaxComplianceService {
  MockTaxComplianceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> needsTaxDocuments(
    String? userId,
    int? year,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #needsTaxDocuments,
          [
            userId,
            year,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i2.TaxDocument> generate1099(
    String? userId,
    int? year,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #generate1099,
          [
            userId,
            year,
          ],
        ),
        returnValue: _i5.Future<_i2.TaxDocument>.value(_FakeTaxDocument_0(
          this,
          Invocation.method(
            #generate1099,
            [
              userId,
              year,
            ],
          ),
        )),
      ) as _i5.Future<_i2.TaxDocument>);

  @override
  _i5.Future<List<_i2.TaxDocument>> generateAll1099sForYear(int? year) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateAll1099sForYear,
          [year],
        ),
        returnValue:
            _i5.Future<List<_i2.TaxDocument>>.value(<_i2.TaxDocument>[]),
      ) as _i5.Future<List<_i2.TaxDocument>>);

  @override
  _i5.Future<void> requestW9(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #requestW9,
          [userId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.TaxProfile> submitW9({
    required String? userId,
    required String? ssn,
    required _i3.TaxClassification? classification,
    String? ein,
    String? businessName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitW9,
          [],
          {
            #userId: userId,
            #ssn: ssn,
            #classification: classification,
            #ein: ein,
            #businessName: businessName,
          },
        ),
        returnValue: _i5.Future<_i3.TaxProfile>.value(_FakeTaxProfile_1(
          this,
          Invocation.method(
            #submitW9,
            [],
            {
              #userId: userId,
              #ssn: ssn,
              #classification: classification,
              #ein: ein,
              #businessName: businessName,
            },
          ),
        )),
      ) as _i5.Future<_i3.TaxProfile>);

  @override
  _i5.Future<_i3.TaxProfile> getTaxProfile(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTaxProfile,
          [userId],
        ),
        returnValue: _i5.Future<_i3.TaxProfile>.value(_FakeTaxProfile_1(
          this,
          Invocation.method(
            #getTaxProfile,
            [userId],
          ),
        )),
      ) as _i5.Future<_i3.TaxProfile>);

  @override
  _i5.Future<_i2.TaxDocument?> getTaxDocument(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTaxDocument,
          [documentId],
        ),
        returnValue: _i5.Future<_i2.TaxDocument?>.value(),
      ) as _i5.Future<_i2.TaxDocument?>);

  @override
  _i5.Future<List<_i2.TaxDocument>> getTaxDocuments(
    String? userId,
    int? year,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTaxDocuments,
          [
            userId,
            year,
          ],
        ),
        returnValue:
            _i5.Future<List<_i2.TaxDocument>>.value(<_i2.TaxDocument>[]),
      ) as _i5.Future<List<_i2.TaxDocument>>);

  @override
  _i5.Future<Map<String, dynamic>> getTaxStatus(
    String? userId,
    int? year,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTaxStatus,
          [
            userId,
            year,
          ],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);
}
