// Mocks generated by Mockito 5.4.6 from annotations
// in avrai/test/unit/services/meaningful_connection_metrics_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i15;

import 'package:avrai/core/ai/personality_learning.dart' as _i5;
import 'package:avrai/core/ai/vibe_analysis_engine.dart' as _i7;
import 'package:avrai/core/models/multi_path_expertise.dart' as _i17;
import 'package:avrai/core/models/outcome_result.dart' as _i18;
import 'package:avrai/core/models/unified_user.dart' as _i19;
import 'package:avrai/core/models/user_vibe.dart' as _i6;
import 'package:avrai/core/services/agent_id_service.dart' as _i21;
import 'package:avrai/core/services/supabase_service.dart' as _i20;
import 'package:avrai_core/models/atomic_timestamp.dart' as _i2;
import 'package:avrai_core/models/personality_knot.dart' as _i23;
import 'package:avrai_core/models/personality_profile.dart' as _i4;
import 'package:avrai_core/models/quantum_entity_state.dart' as _i16;
import 'package:avrai_core/services/atomic_clock_service.dart' as _i14;
import 'package:avrai_knot/models/knot/braided_knot.dart' as _i26;
import 'package:avrai_knot/models/knot/bridge_strand.dart' as _i28;
import 'package:avrai_knot/models/knot/fabric_cluster.dart' as _i27;
import 'package:avrai_knot/models/knot/fabric_evolution.dart' as _i13;
import 'package:avrai_knot/models/knot/fabric_invariants.dart' as _i12;
import 'package:avrai_knot/models/knot/fabric_snapshot.dart' as _i30;
import 'package:avrai_knot/models/knot/knot_fabric.dart' as _i10;
import 'package:avrai_knot/models/knot/knot_worldsheet.dart' as _i25;
import 'package:avrai_knot/services/knot/knot_evolution_string_service.dart'
    as _i9;
import 'package:avrai_knot/services/knot/knot_fabric_service.dart' as _i11;
import 'package:avrai_knot/services/knot/knot_storage_service.dart' as _i29;
import 'package:avrai_knot/services/knot/knot_worldsheet_service.dart' as _i24;
import 'package:avrai_quantum/services/quantum/quantum_entanglement_service.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i22;
import 'package:supabase_flutter/supabase_flutter.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAtomicTimestamp_0 extends _i1.SmartFake
    implements _i2.AtomicTimestamp {
  _FakeAtomicTimestamp_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_1 extends _i1.SmartFake implements Duration {
  _FakeDuration_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEntangledQuantumState_2 extends _i1.SmartFake
    implements _i3.EntangledQuantumState {
  _FakeEntangledQuantumState_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePersonalityProfile_3 extends _i1.SmartFake
    implements _i4.PersonalityProfile {
  _FakePersonalityProfile_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePersonalityReadiness_4 extends _i1.SmartFake
    implements _i5.PersonalityReadiness {
  _FakePersonalityReadiness_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAnonymizedPersonalityData_5 extends _i1.SmartFake
    implements _i5.AnonymizedPersonalityData {
  _FakeAnonymizedPersonalityData_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserVibe_6 extends _i1.SmartFake implements _i6.UserVibe {
  _FakeUserVibe_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVibeCompatibilityResult_7 extends _i1.SmartFake
    implements _i7.VibeCompatibilityResult {
  _FakeVibeCompatibilityResult_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCommunityVibeInsights_8 extends _i1.SmartFake
    implements _i7.CommunityVibeInsights {
  _FakeCommunityVibeInsights_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVibeAuthenticityResult_9 extends _i1.SmartFake
    implements _i7.VibeAuthenticityResult {
  _FakeVibeAuthenticityResult_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseClient_10 extends _i1.SmartFake
    implements _i8.SupabaseClient {
  _FakeSupabaseClient_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_11 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthResponse_12 extends _i1.SmartFake implements _i8.AuthResponse {
  _FakeAuthResponse_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEvolutionAnalysis_13 extends _i1.SmartFake
    implements _i9.EvolutionAnalysis {
  _FakeEvolutionAnalysis_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKnotFabric_14 extends _i1.SmartFake implements _i10.KnotFabric {
  _FakeKnotFabric_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKnotLinkNetwork_15 extends _i1.SmartFake
    implements _i11.KnotLinkNetwork {
  _FakeKnotLinkNetwork_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFabricInvariants_16 extends _i1.SmartFake
    implements _i12.FabricInvariants {
  _FakeFabricInvariants_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFabricEvolution_17 extends _i1.SmartFake
    implements _i13.FabricEvolution {
  _FakeFabricEvolution_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AtomicClockService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAtomicClockService extends _i1.Mock
    implements _i14.AtomicClockService {
  MockAtomicClockService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void configure({_i15.Future<DateTime> Function()? serverTimeProvider}) =>
      super.noSuchMethod(
        Invocation.method(
          #configure,
          [],
          {#serverTimeProvider: serverTimeProvider},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i15.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  _i15.Future<void> syncWithServer() => (super.noSuchMethod(
        Invocation.method(
          #syncWithServer,
          [],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  _i15.Future<_i2.AtomicTimestamp> getAtomicTimestamp() => (super.noSuchMethod(
        Invocation.method(
          #getAtomicTimestamp,
          [],
        ),
        returnValue:
            _i15.Future<_i2.AtomicTimestamp>.value(_FakeAtomicTimestamp_0(
          this,
          Invocation.method(
            #getAtomicTimestamp,
            [],
          ),
        )),
      ) as _i15.Future<_i2.AtomicTimestamp>);

  @override
  Duration getTimeOffset() => (super.noSuchMethod(
        Invocation.method(
          #getTimeOffset,
          [],
        ),
        returnValue: _FakeDuration_1(
          this,
          Invocation.method(
            #getTimeOffset,
            [],
          ),
        ),
      ) as Duration);

  @override
  bool isSynchronized() => (super.noSuchMethod(
        Invocation.method(
          #isSynchronized,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i2.TimePrecision getPrecision() => (super.noSuchMethod(
        Invocation.method(
          #getPrecision,
          [],
        ),
        returnValue: _i2.TimePrecision.nanosecond,
      ) as _i2.TimePrecision);

  @override
  _i15.Future<_i2.AtomicTimestamp> getTicketPurchaseTimestamp() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTicketPurchaseTimestamp,
          [],
        ),
        returnValue:
            _i15.Future<_i2.AtomicTimestamp>.value(_FakeAtomicTimestamp_0(
          this,
          Invocation.method(
            #getTicketPurchaseTimestamp,
            [],
          ),
        )),
      ) as _i15.Future<_i2.AtomicTimestamp>);

  @override
  _i15.Future<_i2.AtomicTimestamp> getAI2AIConnectionTimestamp() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAI2AIConnectionTimestamp,
          [],
        ),
        returnValue:
            _i15.Future<_i2.AtomicTimestamp>.value(_FakeAtomicTimestamp_0(
          this,
          Invocation.method(
            #getAI2AIConnectionTimestamp,
            [],
          ),
        )),
      ) as _i15.Future<_i2.AtomicTimestamp>);

  @override
  _i15.Future<_i2.AtomicTimestamp> getLiveTrackingTimestamp() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLiveTrackingTimestamp,
          [],
        ),
        returnValue:
            _i15.Future<_i2.AtomicTimestamp>.value(_FakeAtomicTimestamp_0(
          this,
          Invocation.method(
            #getLiveTrackingTimestamp,
            [],
          ),
        )),
      ) as _i15.Future<_i2.AtomicTimestamp>);

  @override
  _i15.Future<_i2.AtomicTimestamp> getAdminOperationTimestamp() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAdminOperationTimestamp,
          [],
        ),
        returnValue:
            _i15.Future<_i2.AtomicTimestamp>.value(_FakeAtomicTimestamp_0(
          this,
          Invocation.method(
            #getAdminOperationTimestamp,
            [],
          ),
        )),
      ) as _i15.Future<_i2.AtomicTimestamp>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [QuantumEntanglementService].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuantumEntanglementService extends _i1.Mock
    implements _i3.QuantumEntanglementService {
  MockQuantumEntanglementService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.Future<_i3.EntangledQuantumState> createEntangledState({
    required List<_i16.QuantumEntityState>? entityStates,
    List<double>? coefficients,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEntangledState,
          [],
          {
            #entityStates: entityStates,
            #coefficients: coefficients,
          },
        ),
        returnValue: _i15.Future<_i3.EntangledQuantumState>.value(
            _FakeEntangledQuantumState_2(
          this,
          Invocation.method(
            #createEntangledState,
            [],
            {
              #entityStates: entityStates,
              #coefficients: coefficients,
            },
          ),
        )),
      ) as _i15.Future<_i3.EntangledQuantumState>);

  @override
  _i15.Future<double> calculateFidelity(
    _i3.EntangledQuantumState? state1,
    _i3.EntangledQuantumState? state2,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateFidelity,
          [
            state1,
            state2,
          ],
        ),
        returnValue: _i15.Future<double>.value(0.0),
      ) as _i15.Future<double>);

  @override
  _i15.Future<double> calculateKnotCompatibilityBonus(
    List<_i16.QuantumEntityState>? entityStates, {
    DateTime? targetTime,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateKnotCompatibilityBonus,
          [entityStates],
          {#targetTime: targetTime},
        ),
        returnValue: _i15.Future<double>.value(0.0),
      ) as _i15.Future<double>);

  @override
  _i15.Future<bool> shareEntanglementInsightsViaMesh({
    required _i3.EntangledQuantumState? entangledState,
    double? fidelity,
    double? knotCompatibility,
    required String? sourceAgentId,
    required List<String>? entityTypes,
    required dynamic messageType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #shareEntanglementInsightsViaMesh,
          [],
          {
            #entangledState: entangledState,
            #fidelity: fidelity,
            #knotCompatibility: knotCompatibility,
            #sourceAgentId: sourceAgentId,
            #entityTypes: entityTypes,
            #messageType: messageType,
          },
        ),
        returnValue: _i15.Future<bool>.value(false),
      ) as _i15.Future<bool>);
}

/// A class which mocks [PersonalityLearning].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonalityLearning extends _i1.Mock
    implements _i5.PersonalityLearning {
  MockPersonalityLearning() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onPersonalityEvolved(
          dynamic Function(
            String,
            _i4.PersonalityProfile,
          )? _onPersonalityEvolved) =>
      super.noSuchMethod(
        Invocation.setter(
          #onPersonalityEvolved,
          _onPersonalityEvolved,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i15.Future<void> migrateProfilesToAgentId() => (super.noSuchMethod(
        Invocation.method(
          #migrateProfilesToAgentId,
          [],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  void setEvolutionCallback(
          dynamic Function(
            String,
            _i4.PersonalityProfile,
          )? callback) =>
      super.noSuchMethod(
        Invocation.method(
          #setEvolutionCallback,
          [callback],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i15.Future<_i4.PersonalityProfile> initializePersonality(
    String? userId, {
    String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initializePersonality,
          [userId],
          {#password: password},
        ),
        returnValue:
            _i15.Future<_i4.PersonalityProfile>.value(_FakePersonalityProfile_3(
          this,
          Invocation.method(
            #initializePersonality,
            [userId],
            {#password: password},
          ),
        )),
      ) as _i15.Future<_i4.PersonalityProfile>);

  @override
  _i15.Future<_i4.PersonalityProfile> initializePersonalityFromOnboarding(
    String? userId, {
    Map<String, dynamic>? onboardingData,
    Map<String, dynamic>? socialMediaData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initializePersonalityFromOnboarding,
          [userId],
          {
            #onboardingData: onboardingData,
            #socialMediaData: socialMediaData,
          },
        ),
        returnValue:
            _i15.Future<_i4.PersonalityProfile>.value(_FakePersonalityProfile_3(
          this,
          Invocation.method(
            #initializePersonalityFromOnboarding,
            [userId],
            {
              #onboardingData: onboardingData,
              #socialMediaData: socialMediaData,
            },
          ),
        )),
      ) as _i15.Future<_i4.PersonalityProfile>);

  @override
  _i15.Future<_i4.PersonalityProfile> evolveFromUserAction(
    String? userId,
    _i5.UserAction? action, {
    _i17.LocalExpertise? localExpertise,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #evolveFromUserAction,
          [
            userId,
            action,
          ],
          {#localExpertise: localExpertise},
        ),
        returnValue:
            _i15.Future<_i4.PersonalityProfile>.value(_FakePersonalityProfile_3(
          this,
          Invocation.method(
            #evolveFromUserAction,
            [
              userId,
              action,
            ],
            {#localExpertise: localExpertise},
          ),
        )),
      ) as _i15.Future<_i4.PersonalityProfile>);

  @override
  _i15.Future<_i4.PersonalityProfile> evolveFromAI2AILearning(
    String? userId,
    _i5.AI2AILearningInsight? insight, {
    _i18.OutcomeResult? outcome,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #evolveFromAI2AILearning,
          [
            userId,
            insight,
          ],
          {#outcome: outcome},
        ),
        returnValue:
            _i15.Future<_i4.PersonalityProfile>.value(_FakePersonalityProfile_3(
          this,
          Invocation.method(
            #evolveFromAI2AILearning,
            [
              userId,
              insight,
            ],
            {#outcome: outcome},
          ),
        )),
      ) as _i15.Future<_i4.PersonalityProfile>);

  @override
  _i15.Future<_i4.PersonalityProfile?> getCurrentPersonality(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentPersonality,
          [userId],
        ),
        returnValue: _i15.Future<_i4.PersonalityProfile?>.value(),
      ) as _i15.Future<_i4.PersonalityProfile?>);

  @override
  _i15.Future<List<_i5.PersonalityEvolutionEvent>> getEvolutionHistory(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEvolutionHistory,
          [userId],
        ),
        returnValue: _i15.Future<List<_i5.PersonalityEvolutionEvent>>.value(
            <_i5.PersonalityEvolutionEvent>[]),
      ) as _i15.Future<List<_i5.PersonalityEvolutionEvent>>);

  @override
  _i15.Future<_i5.PersonalityReadiness> calculateAI2AIReadiness(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateAI2AIReadiness,
          [userId],
        ),
        returnValue: _i15.Future<_i5.PersonalityReadiness>.value(
            _FakePersonalityReadiness_4(
          this,
          Invocation.method(
            #calculateAI2AIReadiness,
            [userId],
          ),
        )),
      ) as _i15.Future<_i5.PersonalityReadiness>);

  @override
  _i15.Future<void> resetPersonality(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #resetPersonality,
          [userId],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  _i15.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  _i15.Future<double> calculatePersonalityReadiness() => (super.noSuchMethod(
        Invocation.method(
          #calculatePersonalityReadiness,
          [],
        ),
        returnValue: _i15.Future<double>.value(0.0),
      ) as _i15.Future<double>);

  @override
  _i15.Future<Map<String, dynamic>> calculatePersonalityEvolution({
    Map<String, dynamic>? current,
    Map<String, dynamic>? currentProfile,
    List<Map<String, dynamic>>? actions = const [],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculatePersonalityEvolution,
          [],
          {
            #current: current,
            #currentProfile: currentProfile,
            #actions: actions,
          },
        ),
        returnValue:
            _i15.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i15.Future<Map<String, dynamic>>);

  @override
  _i15.Future<_i4.PersonalityProfile> evolvePersonality(
          _i5.UserAction? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #evolvePersonality,
          [action],
        ),
        returnValue:
            _i15.Future<_i4.PersonalityProfile>.value(_FakePersonalityProfile_3(
          this,
          Invocation.method(
            #evolvePersonality,
            [action],
          ),
        )),
      ) as _i15.Future<_i4.PersonalityProfile>);

  @override
  _i15.Future<List<_i5.BehavioralPattern>> recognizeBehavioralPatterns(
          List<_i5.UserAction>? actions) =>
      (super.noSuchMethod(
        Invocation.method(
          #recognizeBehavioralPatterns,
          [actions],
        ),
        returnValue: _i15.Future<List<_i5.BehavioralPattern>>.value(
            <_i5.BehavioralPattern>[]),
      ) as _i15.Future<List<_i5.BehavioralPattern>>);

  @override
  _i15.Future<Map<String, double>> predictFuturePreferences() =>
      (super.noSuchMethod(
        Invocation.method(
          #predictFuturePreferences,
          [],
        ),
        returnValue: _i15.Future<Map<String, double>>.value(<String, double>{}),
      ) as _i15.Future<Map<String, double>>);

  @override
  _i15.Future<void> updatePersonalityProfile(
          Map<String, dynamic>? personalityData) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePersonalityProfile,
          [personalityData],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  _i15.Future<double> calculatePersonalityCompatibility(
    Map<String, dynamic>? a,
    Map<String, dynamic>? b,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculatePersonalityCompatibility,
          [
            a,
            b,
          ],
        ),
        returnValue: _i15.Future<double>.value(0.0),
      ) as _i15.Future<double>);

  @override
  _i15.Future<_i5.AnonymizedPersonalityData> anonymizePersonality() =>
      (super.noSuchMethod(
        Invocation.method(
          #anonymizePersonality,
          [],
        ),
        returnValue: _i15.Future<_i5.AnonymizedPersonalityData>.value(
            _FakeAnonymizedPersonalityData_5(
          this,
          Invocation.method(
            #anonymizePersonality,
            [],
          ),
        )),
      ) as _i15.Future<_i5.AnonymizedPersonalityData>);
}

/// A class which mocks [UserVibeAnalyzer].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserVibeAnalyzer extends _i1.Mock implements _i7.UserVibeAnalyzer {
  MockUserVibeAnalyzer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.Future<_i6.UserVibe> compileUserVibe(
    String? userId,
    _i4.PersonalityProfile? personality,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #compileUserVibe,
          [
            userId,
            personality,
          ],
        ),
        returnValue: _i15.Future<_i6.UserVibe>.value(_FakeUserVibe_6(
          this,
          Invocation.method(
            #compileUserVibe,
            [
              userId,
              personality,
            ],
          ),
        )),
      ) as _i15.Future<_i6.UserVibe>);

  @override
  _i15.Future<_i7.VibeCompatibilityResult> analyzeVibeCompatibility(
    _i6.UserVibe? localVibe,
    _i6.UserVibe? remoteVibe, {
    _i19.UnifiedUser? localUser,
    _i19.UnifiedUser? remoteUser,
    List<String>? recentActions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #analyzeVibeCompatibility,
          [
            localVibe,
            remoteVibe,
          ],
          {
            #localUser: localUser,
            #remoteUser: remoteUser,
            #recentActions: recentActions,
          },
        ),
        returnValue: _i15.Future<_i7.VibeCompatibilityResult>.value(
            _FakeVibeCompatibilityResult_7(
          this,
          Invocation.method(
            #analyzeVibeCompatibility,
            [
              localVibe,
              remoteVibe,
            ],
            {
              #localUser: localUser,
              #remoteUser: remoteUser,
              #recentActions: recentActions,
            },
          ),
        )),
      ) as _i15.Future<_i7.VibeCompatibilityResult>);

  @override
  _i15.Future<_i6.UserVibe> refreshUserVibe(
    String? userId,
    _i4.PersonalityProfile? updatedPersonality,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshUserVibe,
          [
            userId,
            updatedPersonality,
          ],
        ),
        returnValue: _i15.Future<_i6.UserVibe>.value(_FakeUserVibe_6(
          this,
          Invocation.method(
            #refreshUserVibe,
            [
              userId,
              updatedPersonality,
            ],
          ),
        )),
      ) as _i15.Future<_i6.UserVibe>);

  @override
  _i15.Future<List<_i7.VibeEvolutionEvent>> getVibeEvolutionHistory(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVibeEvolutionHistory,
          [userId],
        ),
        returnValue: _i15.Future<List<_i7.VibeEvolutionEvent>>.value(
            <_i7.VibeEvolutionEvent>[]),
      ) as _i15.Future<List<_i7.VibeEvolutionEvent>>);

  @override
  _i15.Future<_i7.CommunityVibeInsights> analyzeCommunityVibePatterns() =>
      (super.noSuchMethod(
        Invocation.method(
          #analyzeCommunityVibePatterns,
          [],
        ),
        returnValue: _i15.Future<_i7.CommunityVibeInsights>.value(
            _FakeCommunityVibeInsights_8(
          this,
          Invocation.method(
            #analyzeCommunityVibePatterns,
            [],
          ),
        )),
      ) as _i15.Future<_i7.CommunityVibeInsights>);

  @override
  _i15.Future<_i7.VibeAuthenticityResult> validateVibeAuthenticity(
    _i6.UserVibe? vibe,
    _i4.PersonalityProfile? personality,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateVibeAuthenticity,
          [
            vibe,
            personality,
          ],
        ),
        returnValue: _i15.Future<_i7.VibeAuthenticityResult>.value(
            _FakeVibeAuthenticityResult_9(
          this,
          Invocation.method(
            #validateVibeAuthenticity,
            [
              vibe,
              personality,
            ],
          ),
        )),
      ) as _i15.Future<_i7.VibeAuthenticityResult>);
}

/// A class which mocks [SupabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseService extends _i1.Mock implements _i20.SupabaseService {
  MockSupabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.SupabaseClient get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeSupabaseClient_10(
          this,
          Invocation.getter(#client),
        ),
      ) as _i8.SupabaseClient);

  @override
  bool get isAvailable => (super.noSuchMethod(
        Invocation.getter(#isAvailable),
        returnValue: false,
      ) as bool);

  @override
  _i15.Future<bool> testConnection() => (super.noSuchMethod(
        Invocation.method(
          #testConnection,
          [],
        ),
        returnValue: _i15.Future<bool>.value(false),
      ) as _i15.Future<bool>);

  @override
  _i15.Future<DateTime> getServerTime() => (super.noSuchMethod(
        Invocation.method(
          #getServerTime,
          [],
        ),
        returnValue: _i15.Future<DateTime>.value(_FakeDateTime_11(
          this,
          Invocation.method(
            #getServerTime,
            [],
          ),
        )),
      ) as _i15.Future<DateTime>);

  @override
  _i15.Future<_i8.AuthResponse> signInWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmail,
          [
            email,
            password,
          ],
        ),
        returnValue: _i15.Future<_i8.AuthResponse>.value(_FakeAuthResponse_12(
          this,
          Invocation.method(
            #signInWithEmail,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i15.Future<_i8.AuthResponse>);

  @override
  _i15.Future<_i8.AuthResponse> signUpWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUpWithEmail,
          [
            email,
            password,
          ],
        ),
        returnValue: _i15.Future<_i8.AuthResponse>.value(_FakeAuthResponse_12(
          this,
          Invocation.method(
            #signUpWithEmail,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i15.Future<_i8.AuthResponse>);

  @override
  _i15.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  _i15.Future<Map<String, dynamic>> createSpot({
    required String? name,
    required double? latitude,
    required double? longitude,
    String? description,
    List<String>? tags,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSpot,
          [],
          {
            #name: name,
            #latitude: latitude,
            #longitude: longitude,
            #description: description,
            #tags: tags,
          },
        ),
        returnValue:
            _i15.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i15.Future<Map<String, dynamic>>);

  @override
  _i15.Future<List<Map<String, dynamic>>> getSpots() => (super.noSuchMethod(
        Invocation.method(
          #getSpots,
          [],
        ),
        returnValue: _i15.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i15.Future<List<Map<String, dynamic>>>);

  @override
  _i15.Future<List<Map<String, dynamic>>> getSpotsByUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSpotsByUser,
          [userId],
        ),
        returnValue: _i15.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i15.Future<List<Map<String, dynamic>>>);

  @override
  _i15.Future<Map<String, dynamic>> createSpotList({
    required String? name,
    String? description,
    List<String>? tags,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSpotList,
          [],
          {
            #name: name,
            #description: description,
            #tags: tags,
          },
        ),
        returnValue:
            _i15.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i15.Future<Map<String, dynamic>>);

  @override
  _i15.Future<List<Map<String, dynamic>>> getSpotLists() => (super.noSuchMethod(
        Invocation.method(
          #getSpotLists,
          [],
        ),
        returnValue: _i15.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i15.Future<List<Map<String, dynamic>>>);

  @override
  _i15.Future<Map<String, dynamic>> addSpotToList({
    required String? listId,
    required String? spotId,
    String? note,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addSpotToList,
          [],
          {
            #listId: listId,
            #spotId: spotId,
            #note: note,
          },
        ),
        returnValue:
            _i15.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i15.Future<Map<String, dynamic>>);

  @override
  _i15.Stream<List<Map<String, dynamic>>> getSpotsStream() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSpotsStream,
          [],
        ),
        returnValue: _i15.Stream<List<Map<String, dynamic>>>.empty(),
      ) as _i15.Stream<List<Map<String, dynamic>>>);

  @override
  _i15.Stream<List<Map<String, dynamic>>> getSpotListsStream() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSpotListsStream,
          [],
        ),
        returnValue: _i15.Stream<List<Map<String, dynamic>>>.empty(),
      ) as _i15.Stream<List<Map<String, dynamic>>>);

  @override
  _i15.Future<Map<String, dynamic>> updateUserProfile({
    String? name,
    String? bio,
    String? location,
    String? avatarUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [],
          {
            #name: name,
            #bio: bio,
            #location: location,
            #avatarUrl: avatarUrl,
          },
        ),
        returnValue:
            _i15.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i15.Future<Map<String, dynamic>>);

  @override
  _i15.Future<Map<String, dynamic>?> getUserProfile(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [userId],
        ),
        returnValue: _i15.Future<Map<String, dynamic>?>.value(),
      ) as _i15.Future<Map<String, dynamic>?>);
}

/// A class which mocks [AgentIdService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAgentIdService extends _i1.Mock implements _i21.AgentIdService {
  MockAgentIdService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.Future<String> getUserAgentId(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getUserAgentId,
          [userId],
        ),
        returnValue: _i15.Future<String>.value(_i22.dummyValue<String>(
          this,
          Invocation.method(
            #getUserAgentId,
            [userId],
          ),
        )),
      ) as _i15.Future<String>);

  @override
  _i15.Future<void> rotateMappingEncryptionKey(
    String? userId, {
    _i21.EncryptedMapping? existingEncryptedMapping,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rotateMappingEncryptionKey,
          [userId],
          {#existingEncryptedMapping: existingEncryptedMapping},
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i15.Future<void> flushAuditLogs() => (super.noSuchMethod(
        Invocation.method(
          #flushAuditLogs,
          [],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  _i15.Future<String> getBusinessAgentId(String? businessId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBusinessAgentId,
          [businessId],
        ),
        returnValue: _i15.Future<String>.value(_i22.dummyValue<String>(
          this,
          Invocation.method(
            #getBusinessAgentId,
            [businessId],
          ),
        )),
      ) as _i15.Future<String>);

  @override
  _i15.Future<String> getExpertAgentId(String? expertId) => (super.noSuchMethod(
        Invocation.method(
          #getExpertAgentId,
          [expertId],
        ),
        returnValue: _i15.Future<String>.value(_i22.dummyValue<String>(
          this,
          Invocation.method(
            #getExpertAgentId,
            [expertId],
          ),
        )),
      ) as _i15.Future<String>);
}

/// A class which mocks [KnotEvolutionStringService].
///
/// See the documentation for Mockito's code generation for more information.
class MockKnotEvolutionStringService extends _i1.Mock
    implements _i9.KnotEvolutionStringService {
  MockKnotEvolutionStringService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.Future<_i9.KnotString?> createStringFromHistory(String? agentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStringFromHistory,
          [agentId],
        ),
        returnValue: _i15.Future<_i9.KnotString?>.value(),
      ) as _i15.Future<_i9.KnotString?>);

  @override
  _i15.Future<_i23.PersonalityKnot?> getKnotAtTime(
    String? agentId,
    DateTime? t,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getKnotAtTime,
          [
            agentId,
            t,
          ],
        ),
        returnValue: _i15.Future<_i23.PersonalityKnot?>.value(),
      ) as _i15.Future<_i23.PersonalityKnot?>);

  @override
  _i15.Future<List<_i23.PersonalityKnot>> getEvolutionTrajectory({
    required String? agentId,
    required DateTime? start,
    required DateTime? end,
    required Duration? step,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEvolutionTrajectory,
          [],
          {
            #agentId: agentId,
            #start: start,
            #end: end,
            #step: step,
          },
        ),
        returnValue: _i15.Future<List<_i23.PersonalityKnot>>.value(
            <_i23.PersonalityKnot>[]),
      ) as _i15.Future<List<_i23.PersonalityKnot>>);

  @override
  _i15.Future<_i23.PersonalityKnot?> predictFutureKnot(
    String? agentId,
    DateTime? futureTime,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #predictFutureKnot,
          [
            agentId,
            futureTime,
          ],
        ),
        returnValue: _i15.Future<_i23.PersonalityKnot?>.value(),
      ) as _i15.Future<_i23.PersonalityKnot?>);

  @override
  _i15.Future<_i9.EvolutionAnalysis> analyzeEvolutionPatterns(
          String? agentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #analyzeEvolutionPatterns,
          [agentId],
        ),
        returnValue:
            _i15.Future<_i9.EvolutionAnalysis>.value(_FakeEvolutionAnalysis_13(
          this,
          Invocation.method(
            #analyzeEvolutionPatterns,
            [agentId],
          ),
        )),
      ) as _i15.Future<_i9.EvolutionAnalysis>);
}

/// A class which mocks [KnotWorldsheetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockKnotWorldsheetService extends _i1.Mock
    implements _i24.KnotWorldsheetService {
  MockKnotWorldsheetService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.Future<_i25.KnotWorldsheet?> createWorldsheet({
    required String? groupId,
    required List<String>? userIds,
    DateTime? startTime,
    DateTime? endTime,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createWorldsheet,
          [],
          {
            #groupId: groupId,
            #userIds: userIds,
            #startTime: startTime,
            #endTime: endTime,
          },
        ),
        returnValue: _i15.Future<_i25.KnotWorldsheet?>.value(),
      ) as _i15.Future<_i25.KnotWorldsheet?>);

  @override
  _i15.Future<_i10.KnotFabric?> getFabricAtTime({
    required String? groupId,
    required DateTime? time,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFabricAtTime,
          [],
          {
            #groupId: groupId,
            #time: time,
          },
        ),
        returnValue: _i15.Future<_i10.KnotFabric?>.value(),
      ) as _i15.Future<_i10.KnotFabric?>);

  @override
  _i15.Future<List<_i23.PersonalityKnot>> getCrossSectionAtTime({
    required String? groupId,
    required DateTime? time,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCrossSectionAtTime,
          [],
          {
            #groupId: groupId,
            #time: time,
          },
        ),
        returnValue: _i15.Future<List<_i23.PersonalityKnot>>.value(
            <_i23.PersonalityKnot>[]),
      ) as _i15.Future<List<_i23.PersonalityKnot>>);

  @override
  _i15.Future<_i9.KnotString?> getUserString({
    required String? groupId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserString,
          [],
          {
            #groupId: groupId,
            #userId: userId,
          },
        ),
        returnValue: _i15.Future<_i9.KnotString?>.value(),
      ) as _i15.Future<_i9.KnotString?>);
}

/// A class which mocks [KnotFabricService].
///
/// See the documentation for Mockito's code generation for more information.
class MockKnotFabricService extends _i1.Mock implements _i11.KnotFabricService {
  MockKnotFabricService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.Future<_i10.KnotFabric> generateMultiStrandBraidFabric({
    required List<_i23.PersonalityKnot>? userKnots,
    Map<String, double>? compatibilityScores,
    Map<String, _i26.RelationshipType>? relationships,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateMultiStrandBraidFabric,
          [],
          {
            #userKnots: userKnots,
            #compatibilityScores: compatibilityScores,
            #relationships: relationships,
          },
        ),
        returnValue: _i15.Future<_i10.KnotFabric>.value(_FakeKnotFabric_14(
          this,
          Invocation.method(
            #generateMultiStrandBraidFabric,
            [],
            {
              #userKnots: userKnots,
              #compatibilityScores: compatibilityScores,
              #relationships: relationships,
            },
          ),
        )),
      ) as _i15.Future<_i10.KnotFabric>);

  @override
  _i15.Future<_i11.KnotLinkNetwork> generateLinkNetworkFabric({
    required List<_i23.PersonalityKnot>? userKnots,
    required List<_i26.BraidedKnot>? relationshipKnots,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateLinkNetworkFabric,
          [],
          {
            #userKnots: userKnots,
            #relationshipKnots: relationshipKnots,
          },
        ),
        returnValue:
            _i15.Future<_i11.KnotLinkNetwork>.value(_FakeKnotLinkNetwork_15(
          this,
          Invocation.method(
            #generateLinkNetworkFabric,
            [],
            {
              #userKnots: userKnots,
              #relationshipKnots: relationshipKnots,
            },
          ),
        )),
      ) as _i15.Future<_i11.KnotLinkNetwork>);

  @override
  _i15.Future<_i12.FabricInvariants> calculateFabricInvariants(
          _i10.KnotFabric? fabric) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateFabricInvariants,
          [fabric],
        ),
        returnValue:
            _i15.Future<_i12.FabricInvariants>.value(_FakeFabricInvariants_16(
          this,
          Invocation.method(
            #calculateFabricInvariants,
            [fabric],
          ),
        )),
      ) as _i15.Future<_i12.FabricInvariants>);

  @override
  _i15.Future<List<_i27.FabricCluster>> identifyFabricClusters(
          _i10.KnotFabric? fabric) =>
      (super.noSuchMethod(
        Invocation.method(
          #identifyFabricClusters,
          [fabric],
        ),
        returnValue:
            _i15.Future<List<_i27.FabricCluster>>.value(<_i27.FabricCluster>[]),
      ) as _i15.Future<List<_i27.FabricCluster>>);

  @override
  _i15.Future<List<_i28.BridgeStrand>> identifyBridgeStrands(
          _i10.KnotFabric? fabric) =>
      (super.noSuchMethod(
        Invocation.method(
          #identifyBridgeStrands,
          [fabric],
        ),
        returnValue:
            _i15.Future<List<_i28.BridgeStrand>>.value(<_i28.BridgeStrand>[]),
      ) as _i15.Future<List<_i28.BridgeStrand>>);

  @override
  _i15.Future<double> measureFabricStability(_i10.KnotFabric? fabric) =>
      (super.noSuchMethod(
        Invocation.method(
          #measureFabricStability,
          [fabric],
        ),
        returnValue: _i15.Future<double>.value(0.0),
      ) as _i15.Future<double>);

  @override
  _i15.Future<_i13.FabricEvolution> trackFabricEvolution({
    required _i10.KnotFabric? currentFabric,
    required _i10.KnotFabric? previousFabric,
    required List<_i13.FabricChange>? changes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackFabricEvolution,
          [],
          {
            #currentFabric: currentFabric,
            #previousFabric: previousFabric,
            #changes: changes,
          },
        ),
        returnValue:
            _i15.Future<_i13.FabricEvolution>.value(_FakeFabricEvolution_17(
          this,
          Invocation.method(
            #trackFabricEvolution,
            [],
            {
              #currentFabric: currentFabric,
              #previousFabric: previousFabric,
              #changes: changes,
            },
          ),
        )),
      ) as _i15.Future<_i13.FabricEvolution>);
}

/// A class which mocks [KnotStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockKnotStorageService extends _i1.Mock
    implements _i29.KnotStorageService {
  MockKnotStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.Future<void> saveKnot(
    String? agentId,
    _i23.PersonalityKnot? knot,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveKnot,
          [
            agentId,
            knot,
          ],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  _i15.Future<_i23.PersonalityKnot?> loadKnot(String? agentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadKnot,
          [agentId],
        ),
        returnValue: _i15.Future<_i23.PersonalityKnot?>.value(),
      ) as _i15.Future<_i23.PersonalityKnot?>);

  @override
  _i15.Future<void> saveEvolutionHistory(
    String? agentId,
    List<_i23.KnotSnapshot>? history,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveEvolutionHistory,
          [
            agentId,
            history,
          ],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  _i15.Future<List<_i23.KnotSnapshot>> loadEvolutionHistory(String? agentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadEvolutionHistory,
          [agentId],
        ),
        returnValue:
            _i15.Future<List<_i23.KnotSnapshot>>.value(<_i23.KnotSnapshot>[]),
      ) as _i15.Future<List<_i23.KnotSnapshot>>);

  @override
  _i15.Future<void> addSnapshot(
    String? agentId,
    _i23.KnotSnapshot? snapshot,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addSnapshot,
          [
            agentId,
            snapshot,
          ],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  _i15.Future<void> deleteKnot(String? agentId) => (super.noSuchMethod(
        Invocation.method(
          #deleteKnot,
          [agentId],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  _i15.Future<bool> knotExists(String? agentId) => (super.noSuchMethod(
        Invocation.method(
          #knotExists,
          [agentId],
        ),
        returnValue: _i15.Future<bool>.value(false),
      ) as _i15.Future<bool>);

  @override
  _i15.Future<List<_i23.PersonalityKnot>> getAllKnots() => (super.noSuchMethod(
        Invocation.method(
          #getAllKnots,
          [],
        ),
        returnValue: _i15.Future<List<_i23.PersonalityKnot>>.value(
            <_i23.PersonalityKnot>[]),
      ) as _i15.Future<List<_i23.PersonalityKnot>>);

  @override
  _i15.Future<void> saveBraidedKnot({
    required String? connectionId,
    required _i26.BraidedKnot? braidedKnot,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveBraidedKnot,
          [],
          {
            #connectionId: connectionId,
            #braidedKnot: braidedKnot,
          },
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  _i15.Future<_i26.BraidedKnot?> getBraidedKnot(String? connectionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBraidedKnot,
          [connectionId],
        ),
        returnValue: _i15.Future<_i26.BraidedKnot?>.value(),
      ) as _i15.Future<_i26.BraidedKnot?>);

  @override
  _i15.Future<List<_i26.BraidedKnot>> getAllBraidedKnots() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllBraidedKnots,
          [],
        ),
        returnValue:
            _i15.Future<List<_i26.BraidedKnot>>.value(<_i26.BraidedKnot>[]),
      ) as _i15.Future<List<_i26.BraidedKnot>>);

  @override
  _i15.Future<List<_i26.BraidedKnot>> getBraidedKnotsForAgent(
          String? agentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBraidedKnotsForAgent,
          [agentId],
        ),
        returnValue:
            _i15.Future<List<_i26.BraidedKnot>>.value(<_i26.BraidedKnot>[]),
      ) as _i15.Future<List<_i26.BraidedKnot>>);

  @override
  _i15.Future<void> deleteBraidedKnot(String? connectionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBraidedKnot,
          [connectionId],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  _i15.Future<void> saveFabric(
    String? groupId,
    _i10.KnotFabric? fabric,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveFabric,
          [
            groupId,
            fabric,
          ],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  _i15.Future<_i10.KnotFabric?> loadFabric(String? groupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadFabric,
          [groupId],
        ),
        returnValue: _i15.Future<_i10.KnotFabric?>.value(),
      ) as _i15.Future<_i10.KnotFabric?>);

  @override
  _i15.Future<void> saveFabricSnapshot(
    String? groupId,
    _i30.FabricSnapshot? snapshot,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveFabricSnapshot,
          [
            groupId,
            snapshot,
          ],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  _i15.Future<List<_i30.FabricSnapshot>> loadFabricSnapshots(
    String? groupId, {
    DateTime? startTime,
    DateTime? endTime,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadFabricSnapshots,
          [groupId],
          {
            #startTime: startTime,
            #endTime: endTime,
          },
        ),
        returnValue: _i15.Future<List<_i30.FabricSnapshot>>.value(
            <_i30.FabricSnapshot>[]),
      ) as _i15.Future<List<_i30.FabricSnapshot>>);

  @override
  _i15.Future<void> deleteFabric(String? groupId) => (super.noSuchMethod(
        Invocation.method(
          #deleteFabric,
          [groupId],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  _i15.Future<bool> fabricExists(String? groupId) => (super.noSuchMethod(
        Invocation.method(
          #fabricExists,
          [groupId],
        ),
        returnValue: _i15.Future<bool>.value(false),
      ) as _i15.Future<bool>);
}
