// Mocks generated by Mockito 5.4.6 from annotations
// in spots/test/unit/services/partnership_profile_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:spots/core/models/brand_account.dart' as _i10;
import 'package:spots/core/models/business_account.dart' as _i4;
import 'package:spots/core/models/business_verification.dart' as _i5;
import 'package:spots/core/models/event_partnership.dart' as _i2;
import 'package:spots/core/models/expertise_event.dart' as _i6;
import 'package:spots/core/models/sponsorship.dart' as _i3;
import 'package:spots/core/models/spot.dart' as _i14;
import 'package:spots/core/models/unified_user.dart' as _i13;
import 'package:spots/core/services/business_service.dart' as _i11;
import 'package:spots/core/services/expertise_event_service.dart' as _i12;
import 'package:spots/core/services/partnership_service.dart' as _i7;
import 'package:spots/core/services/sponsorship_service.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEventPartnership_0 extends _i1.SmartFake
    implements _i2.EventPartnership {
  _FakeEventPartnership_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSponsorship_1 extends _i1.SmartFake implements _i3.Sponsorship {
  _FakeSponsorship_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBusinessAccount_2 extends _i1.SmartFake
    implements _i4.BusinessAccount {
  _FakeBusinessAccount_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBusinessVerification_3 extends _i1.SmartFake
    implements _i5.BusinessVerification {
  _FakeBusinessVerification_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExpertiseEvent_4 extends _i1.SmartFake
    implements _i6.ExpertiseEvent {
  _FakeExpertiseEvent_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PartnershipService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPartnershipService extends _i1.Mock
    implements _i7.PartnershipService {
  MockPartnershipService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.EventPartnership> createPartnership({
    required String? eventId,
    required String? userId,
    required String? businessId,
    _i2.PartnershipAgreement? agreement,
    _i2.PartnershipType? type = _i2.PartnershipType.eventBased,
    List<String>? sharedResponsibilities,
    String? venueLocation,
    double? vibeCompatibilityScore,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPartnership,
          [],
          {
            #eventId: eventId,
            #userId: userId,
            #businessId: businessId,
            #agreement: agreement,
            #type: type,
            #sharedResponsibilities: sharedResponsibilities,
            #venueLocation: venueLocation,
            #vibeCompatibilityScore: vibeCompatibilityScore,
          },
        ),
        returnValue:
            _i8.Future<_i2.EventPartnership>.value(_FakeEventPartnership_0(
          this,
          Invocation.method(
            #createPartnership,
            [],
            {
              #eventId: eventId,
              #userId: userId,
              #businessId: businessId,
              #agreement: agreement,
              #type: type,
              #sharedResponsibilities: sharedResponsibilities,
              #venueLocation: venueLocation,
              #vibeCompatibilityScore: vibeCompatibilityScore,
            },
          ),
        )),
      ) as _i8.Future<_i2.EventPartnership>);

  @override
  _i8.Future<List<_i2.EventPartnership>> getPartnershipsForEvent(
          String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPartnershipsForEvent,
          [eventId],
        ),
        returnValue: _i8.Future<List<_i2.EventPartnership>>.value(
            <_i2.EventPartnership>[]),
      ) as _i8.Future<List<_i2.EventPartnership>>);

  @override
  _i8.Future<_i2.EventPartnership?> getPartnershipById(String? partnershipId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPartnershipById,
          [partnershipId],
        ),
        returnValue: _i8.Future<_i2.EventPartnership?>.value(),
      ) as _i8.Future<_i2.EventPartnership?>);

  @override
  _i8.Future<_i2.EventPartnership> updatePartnershipStatus({
    required String? partnershipId,
    required _i2.PartnershipStatus? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePartnershipStatus,
          [],
          {
            #partnershipId: partnershipId,
            #status: status,
          },
        ),
        returnValue:
            _i8.Future<_i2.EventPartnership>.value(_FakeEventPartnership_0(
          this,
          Invocation.method(
            #updatePartnershipStatus,
            [],
            {
              #partnershipId: partnershipId,
              #status: status,
            },
          ),
        )),
      ) as _i8.Future<_i2.EventPartnership>);

  @override
  _i8.Future<_i2.EventPartnership> approvePartnership({
    required String? partnershipId,
    required String? approvedBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #approvePartnership,
          [],
          {
            #partnershipId: partnershipId,
            #approvedBy: approvedBy,
          },
        ),
        returnValue:
            _i8.Future<_i2.EventPartnership>.value(_FakeEventPartnership_0(
          this,
          Invocation.method(
            #approvePartnership,
            [],
            {
              #partnershipId: partnershipId,
              #approvedBy: approvedBy,
            },
          ),
        )),
      ) as _i8.Future<_i2.EventPartnership>);

  @override
  _i8.Future<bool> checkPartnershipEligibility({
    required String? userId,
    required String? businessId,
    required String? eventId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkPartnershipEligibility,
          [],
          {
            #userId: userId,
            #businessId: businessId,
            #eventId: eventId,
          },
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<double> calculateVibeCompatibility({
    required String? userId,
    required String? businessId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateVibeCompatibility,
          [],
          {
            #userId: userId,
            #businessId: businessId,
          },
        ),
        returnValue: _i8.Future<double>.value(0.0),
      ) as _i8.Future<double>);
}

/// A class which mocks [SponsorshipService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSponsorshipService extends _i1.Mock
    implements _i9.SponsorshipService {
  MockSponsorshipService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i3.Sponsorship> createSponsorship({
    required String? eventId,
    required String? brandId,
    required _i3.SponsorshipType? type,
    double? contributionAmount,
    double? productValue,
    Map<String, dynamic>? agreementTerms,
    double? vibeCompatibilityScore,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSponsorship,
          [],
          {
            #eventId: eventId,
            #brandId: brandId,
            #type: type,
            #contributionAmount: contributionAmount,
            #productValue: productValue,
            #agreementTerms: agreementTerms,
            #vibeCompatibilityScore: vibeCompatibilityScore,
          },
        ),
        returnValue: _i8.Future<_i3.Sponsorship>.value(_FakeSponsorship_1(
          this,
          Invocation.method(
            #createSponsorship,
            [],
            {
              #eventId: eventId,
              #brandId: brandId,
              #type: type,
              #contributionAmount: contributionAmount,
              #productValue: productValue,
              #agreementTerms: agreementTerms,
              #vibeCompatibilityScore: vibeCompatibilityScore,
            },
          ),
        )),
      ) as _i8.Future<_i3.Sponsorship>);

  @override
  _i8.Future<List<_i3.Sponsorship>> getSponsorshipsForEvent(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSponsorshipsForEvent,
          [eventId],
        ),
        returnValue:
            _i8.Future<List<_i3.Sponsorship>>.value(<_i3.Sponsorship>[]),
      ) as _i8.Future<List<_i3.Sponsorship>>);

  @override
  _i8.Future<List<_i3.Sponsorship>> getSponsorshipsForBrand(String? brandId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSponsorshipsForBrand,
          [brandId],
        ),
        returnValue:
            _i8.Future<List<_i3.Sponsorship>>.value(<_i3.Sponsorship>[]),
      ) as _i8.Future<List<_i3.Sponsorship>>);

  @override
  _i8.Future<_i3.Sponsorship?> getSponsorshipById(String? sponsorshipId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSponsorshipById,
          [sponsorshipId],
        ),
        returnValue: _i8.Future<_i3.Sponsorship?>.value(),
      ) as _i8.Future<_i3.Sponsorship?>);

  @override
  _i8.Future<_i3.Sponsorship> updateSponsorshipStatus({
    required String? sponsorshipId,
    required _i3.SponsorshipStatus? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSponsorshipStatus,
          [],
          {
            #sponsorshipId: sponsorshipId,
            #status: status,
          },
        ),
        returnValue: _i8.Future<_i3.Sponsorship>.value(_FakeSponsorship_1(
          this,
          Invocation.method(
            #updateSponsorshipStatus,
            [],
            {
              #sponsorshipId: sponsorshipId,
              #status: status,
            },
          ),
        )),
      ) as _i8.Future<_i3.Sponsorship>);

  @override
  _i8.Future<bool> checkSponsorshipEligibility({
    required String? eventId,
    required String? brandId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkSponsorshipEligibility,
          [],
          {
            #eventId: eventId,
            #brandId: brandId,
          },
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<double> calculateCompatibility({
    required String? eventId,
    required String? brandId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateCompatibility,
          [],
          {
            #eventId: eventId,
            #brandId: brandId,
          },
        ),
        returnValue: _i8.Future<double>.value(0.0),
      ) as _i8.Future<double>);

  @override
  _i8.Future<_i10.BrandAccount?> getBrandById(String? brandId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBrandById,
          [brandId],
        ),
        returnValue: _i8.Future<_i10.BrandAccount?>.value(),
      ) as _i8.Future<_i10.BrandAccount?>);

  @override
  _i8.Future<void> registerBrand(_i10.BrandAccount? brand) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerBrand,
          [brand],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [BusinessService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBusinessService extends _i1.Mock implements _i11.BusinessService {
  MockBusinessService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i4.BusinessAccount> createBusinessAccount({
    required String? name,
    required String? email,
    required String? businessType,
    required String? createdBy,
    String? description,
    String? website,
    String? location,
    String? phone,
    List<String>? categories,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBusinessAccount,
          [],
          {
            #name: name,
            #email: email,
            #businessType: businessType,
            #createdBy: createdBy,
            #description: description,
            #website: website,
            #location: location,
            #phone: phone,
            #categories: categories,
          },
        ),
        returnValue:
            _i8.Future<_i4.BusinessAccount>.value(_FakeBusinessAccount_2(
          this,
          Invocation.method(
            #createBusinessAccount,
            [],
            {
              #name: name,
              #email: email,
              #businessType: businessType,
              #createdBy: createdBy,
              #description: description,
              #website: website,
              #location: location,
              #phone: phone,
              #categories: categories,
            },
          ),
        )),
      ) as _i8.Future<_i4.BusinessAccount>);

  @override
  _i8.Future<_i5.BusinessVerification> verifyBusiness({
    required String? businessId,
    String? businessLicenseUrl,
    String? taxIdDocumentUrl,
    String? proofOfAddressUrl,
    String? websiteVerificationUrl,
    String? socialMediaVerificationUrl,
    String? legalBusinessName,
    String? taxId,
    String? businessAddress,
    String? phoneNumber,
    String? websiteUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyBusiness,
          [],
          {
            #businessId: businessId,
            #businessLicenseUrl: businessLicenseUrl,
            #taxIdDocumentUrl: taxIdDocumentUrl,
            #proofOfAddressUrl: proofOfAddressUrl,
            #websiteVerificationUrl: websiteVerificationUrl,
            #socialMediaVerificationUrl: socialMediaVerificationUrl,
            #legalBusinessName: legalBusinessName,
            #taxId: taxId,
            #businessAddress: businessAddress,
            #phoneNumber: phoneNumber,
            #websiteUrl: websiteUrl,
          },
        ),
        returnValue: _i8.Future<_i5.BusinessVerification>.value(
            _FakeBusinessVerification_3(
          this,
          Invocation.method(
            #verifyBusiness,
            [],
            {
              #businessId: businessId,
              #businessLicenseUrl: businessLicenseUrl,
              #taxIdDocumentUrl: taxIdDocumentUrl,
              #proofOfAddressUrl: proofOfAddressUrl,
              #websiteVerificationUrl: websiteVerificationUrl,
              #socialMediaVerificationUrl: socialMediaVerificationUrl,
              #legalBusinessName: legalBusinessName,
              #taxId: taxId,
              #businessAddress: businessAddress,
              #phoneNumber: phoneNumber,
              #websiteUrl: websiteUrl,
            },
          ),
        )),
      ) as _i8.Future<_i5.BusinessVerification>);

  @override
  _i8.Future<_i4.BusinessAccount> updateBusinessInfo({
    required String? businessId,
    String? name,
    String? description,
    String? website,
    String? location,
    String? phone,
    List<String>? categories,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBusinessInfo,
          [],
          {
            #businessId: businessId,
            #name: name,
            #description: description,
            #website: website,
            #location: location,
            #phone: phone,
            #categories: categories,
          },
        ),
        returnValue:
            _i8.Future<_i4.BusinessAccount>.value(_FakeBusinessAccount_2(
          this,
          Invocation.method(
            #updateBusinessInfo,
            [],
            {
              #businessId: businessId,
              #name: name,
              #description: description,
              #website: website,
              #location: location,
              #phone: phone,
              #categories: categories,
            },
          ),
        )),
      ) as _i8.Future<_i4.BusinessAccount>);

  @override
  _i8.Future<List<_i4.BusinessAccount>> findBusinesses({
    String? category,
    String? location,
    bool? verifiedOnly = false,
    int? maxResults = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findBusinesses,
          [],
          {
            #category: category,
            #location: location,
            #verifiedOnly: verifiedOnly,
            #maxResults: maxResults,
          },
        ),
        returnValue: _i8.Future<List<_i4.BusinessAccount>>.value(
            <_i4.BusinessAccount>[]),
      ) as _i8.Future<List<_i4.BusinessAccount>>);

  @override
  _i8.Future<bool> checkBusinessEligibility(String? businessId) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkBusinessEligibility,
          [businessId],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<_i4.BusinessAccount?> getBusinessById(String? businessId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBusinessById,
          [businessId],
        ),
        returnValue: _i8.Future<_i4.BusinessAccount?>.value(),
      ) as _i8.Future<_i4.BusinessAccount?>);

  @override
  _i8.Future<_i5.BusinessVerification?> getVerification(String? businessId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVerification,
          [businessId],
        ),
        returnValue: _i8.Future<_i5.BusinessVerification?>.value(),
      ) as _i8.Future<_i5.BusinessVerification?>);
}

/// A class which mocks [ExpertiseEventService].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpertiseEventService extends _i1.Mock
    implements _i12.ExpertiseEventService {
  MockExpertiseEventService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i6.ExpertiseEvent> createEvent({
    required _i13.UnifiedUser? host,
    required String? title,
    required String? description,
    required String? category,
    required _i6.ExpertiseEventType? eventType,
    required DateTime? startTime,
    required DateTime? endTime,
    List<_i14.Spot>? spots,
    String? location,
    double? latitude,
    double? longitude,
    int? maxAttendees = 20,
    double? price,
    bool? isPublic = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEvent,
          [],
          {
            #host: host,
            #title: title,
            #description: description,
            #category: category,
            #eventType: eventType,
            #startTime: startTime,
            #endTime: endTime,
            #spots: spots,
            #location: location,
            #latitude: latitude,
            #longitude: longitude,
            #maxAttendees: maxAttendees,
            #price: price,
            #isPublic: isPublic,
          },
        ),
        returnValue: _i8.Future<_i6.ExpertiseEvent>.value(_FakeExpertiseEvent_4(
          this,
          Invocation.method(
            #createEvent,
            [],
            {
              #host: host,
              #title: title,
              #description: description,
              #category: category,
              #eventType: eventType,
              #startTime: startTime,
              #endTime: endTime,
              #spots: spots,
              #location: location,
              #latitude: latitude,
              #longitude: longitude,
              #maxAttendees: maxAttendees,
              #price: price,
              #isPublic: isPublic,
            },
          ),
        )),
      ) as _i8.Future<_i6.ExpertiseEvent>);

  @override
  _i8.Future<_i6.ExpertiseEvent> duplicateEvent({
    required _i6.ExpertiseEvent? originalEvent,
    DateTime? newStartTime,
    bool? autoSuggestTime = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #duplicateEvent,
          [],
          {
            #originalEvent: originalEvent,
            #newStartTime: newStartTime,
            #autoSuggestTime: autoSuggestTime,
          },
        ),
        returnValue: _i8.Future<_i6.ExpertiseEvent>.value(_FakeExpertiseEvent_4(
          this,
          Invocation.method(
            #duplicateEvent,
            [],
            {
              #originalEvent: originalEvent,
              #newStartTime: newStartTime,
              #autoSuggestTime: autoSuggestTime,
            },
          ),
        )),
      ) as _i8.Future<_i6.ExpertiseEvent>);

  @override
  _i8.Future<void> registerForEvent(
    _i6.ExpertiseEvent? event,
    _i13.UnifiedUser? user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerForEvent,
          [
            event,
            user,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> cancelRegistration(
    _i6.ExpertiseEvent? event,
    _i13.UnifiedUser? user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelRegistration,
          [
            event,
            user,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i6.ExpertiseEvent>> getEventsByHost(
          _i13.UnifiedUser? host) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsByHost,
          [host],
        ),
        returnValue:
            _i8.Future<List<_i6.ExpertiseEvent>>.value(<_i6.ExpertiseEvent>[]),
      ) as _i8.Future<List<_i6.ExpertiseEvent>>);

  @override
  _i8.Future<List<_i6.ExpertiseEvent>> getEventsByAttendee(
          _i13.UnifiedUser? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsByAttendee,
          [user],
        ),
        returnValue:
            _i8.Future<List<_i6.ExpertiseEvent>>.value(<_i6.ExpertiseEvent>[]),
      ) as _i8.Future<List<_i6.ExpertiseEvent>>);

  @override
  _i8.Future<_i6.ExpertiseEvent?> getEventById(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventById,
          [eventId],
        ),
        returnValue: _i8.Future<_i6.ExpertiseEvent?>.value(),
      ) as _i8.Future<_i6.ExpertiseEvent?>);

  @override
  _i8.Future<List<_i6.ExpertiseEvent>> searchEvents({
    String? category,
    String? location,
    _i6.ExpertiseEventType? eventType,
    DateTime? startDate,
    DateTime? endDate,
    int? maxResults = 20,
    bool? includeCommunityEvents = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEvents,
          [],
          {
            #category: category,
            #location: location,
            #eventType: eventType,
            #startDate: startDate,
            #endDate: endDate,
            #maxResults: maxResults,
            #includeCommunityEvents: includeCommunityEvents,
          },
        ),
        returnValue:
            _i8.Future<List<_i6.ExpertiseEvent>>.value(<_i6.ExpertiseEvent>[]),
      ) as _i8.Future<List<_i6.ExpertiseEvent>>);

  @override
  _i8.Future<List<_i6.ExpertiseEvent>> getUpcomingEventsInCategory(
    String? category, {
    int? maxResults = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUpcomingEventsInCategory,
          [category],
          {#maxResults: maxResults},
        ),
        returnValue:
            _i8.Future<List<_i6.ExpertiseEvent>>.value(<_i6.ExpertiseEvent>[]),
      ) as _i8.Future<List<_i6.ExpertiseEvent>>);

  @override
  _i8.Future<List<_i6.ExpertiseEvent>> searchEventsWithConnectedLocalities({
    required _i13.UnifiedUser? user,
    String? category,
    String? location,
    _i6.ExpertiseEventType? eventType,
    DateTime? startDate,
    DateTime? endDate,
    int? maxResults = 20,
    bool? includeConnectedLocalities = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEventsWithConnectedLocalities,
          [],
          {
            #user: user,
            #category: category,
            #location: location,
            #eventType: eventType,
            #startDate: startDate,
            #endDate: endDate,
            #maxResults: maxResults,
            #includeConnectedLocalities: includeConnectedLocalities,
          },
        ),
        returnValue:
            _i8.Future<List<_i6.ExpertiseEvent>>.value(<_i6.ExpertiseEvent>[]),
      ) as _i8.Future<List<_i6.ExpertiseEvent>>);

  @override
  _i8.Future<void> updateEventStatus(
    _i6.ExpertiseEvent? event,
    _i6.EventStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEventStatus,
          [
            event,
            status,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}
