// Mocks generated by Mockito 5.4.6 from annotations
// in spots/test/unit/services/payout_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:spots/core/models/revenue_split.dart' as _i2;
import 'package:spots/core/services/revenue_split_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRevenueSplit_0 extends _i1.SmartFake implements _i2.RevenueSplit {
  _FakeRevenueSplit_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RevenueSplitService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRevenueSplitService extends _i1.Mock
    implements _i3.RevenueSplitService {
  MockRevenueSplitService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.RevenueSplit> calculateNWaySplit({
    required String? eventId,
    String? partnershipId,
    required double? totalAmount,
    required int? ticketsSold,
    required List<_i2.SplitParty>? parties,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateNWaySplit,
          [],
          {
            #eventId: eventId,
            #partnershipId: partnershipId,
            #totalAmount: totalAmount,
            #ticketsSold: ticketsSold,
            #parties: parties,
          },
        ),
        returnValue: _i4.Future<_i2.RevenueSplit>.value(_FakeRevenueSplit_0(
          this,
          Invocation.method(
            #calculateNWaySplit,
            [],
            {
              #eventId: eventId,
              #partnershipId: partnershipId,
              #totalAmount: totalAmount,
              #ticketsSold: ticketsSold,
              #parties: parties,
            },
          ),
        )),
      ) as _i4.Future<_i2.RevenueSplit>);

  @override
  _i4.Future<_i2.RevenueSplit> calculateFromPartnership({
    required String? partnershipId,
    required double? totalAmount,
    required int? ticketsSold,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateFromPartnership,
          [],
          {
            #partnershipId: partnershipId,
            #totalAmount: totalAmount,
            #ticketsSold: ticketsSold,
          },
        ),
        returnValue: _i4.Future<_i2.RevenueSplit>.value(_FakeRevenueSplit_0(
          this,
          Invocation.method(
            #calculateFromPartnership,
            [],
            {
              #partnershipId: partnershipId,
              #totalAmount: totalAmount,
              #ticketsSold: ticketsSold,
            },
          ),
        )),
      ) as _i4.Future<_i2.RevenueSplit>);

  @override
  _i4.Future<_i2.RevenueSplit> lockSplit({
    required String? revenueSplitId,
    required String? lockedBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #lockSplit,
          [],
          {
            #revenueSplitId: revenueSplitId,
            #lockedBy: lockedBy,
          },
        ),
        returnValue: _i4.Future<_i2.RevenueSplit>.value(_FakeRevenueSplit_0(
          this,
          Invocation.method(
            #lockSplit,
            [],
            {
              #revenueSplitId: revenueSplitId,
              #lockedBy: lockedBy,
            },
          ),
        )),
      ) as _i4.Future<_i2.RevenueSplit>);

  @override
  _i4.Future<Map<String, double>> distributePayments({
    required String? revenueSplitId,
    required DateTime? eventEndTime,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #distributePayments,
          [],
          {
            #revenueSplitId: revenueSplitId,
            #eventEndTime: eventEndTime,
          },
        ),
        returnValue: _i4.Future<Map<String, double>>.value(<String, double>{}),
      ) as _i4.Future<Map<String, double>>);

  @override
  _i4.Future<double> trackEarnings({
    required String? partyId,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackEarnings,
          [],
          {
            #partyId: partyId,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i4.Future<double>.value(0.0),
      ) as _i4.Future<double>);

  @override
  _i4.Future<_i2.RevenueSplit?> getRevenueSplit(String? revenueSplitId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRevenueSplit,
          [revenueSplitId],
        ),
        returnValue: _i4.Future<_i2.RevenueSplit?>.value(),
      ) as _i4.Future<_i2.RevenueSplit?>);

  @override
  _i4.Future<List<_i2.RevenueSplit>> getRevenueSplitsForEvent(
          String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRevenueSplitsForEvent,
          [eventId],
        ),
        returnValue:
            _i4.Future<List<_i2.RevenueSplit>>.value(<_i2.RevenueSplit>[]),
      ) as _i4.Future<List<_i2.RevenueSplit>>);

  @override
  _i4.Future<_i2.RevenueSplit> calculateNWayBrandSplit({
    required String? eventId,
    required double? totalAmount,
    required int? ticketsSold,
    Map<String, double>? brandPercentages,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateNWayBrandSplit,
          [],
          {
            #eventId: eventId,
            #totalAmount: totalAmount,
            #ticketsSold: ticketsSold,
            #brandPercentages: brandPercentages,
          },
        ),
        returnValue: _i4.Future<_i2.RevenueSplit>.value(_FakeRevenueSplit_0(
          this,
          Invocation.method(
            #calculateNWayBrandSplit,
            [],
            {
              #eventId: eventId,
              #totalAmount: totalAmount,
              #ticketsSold: ticketsSold,
              #brandPercentages: brandPercentages,
            },
          ),
        )),
      ) as _i4.Future<_i2.RevenueSplit>);

  @override
  _i4.Future<_i2.RevenueSplit> calculateProductSalesSplit({
    required String? productTrackingId,
    required double? totalSales,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateProductSalesSplit,
          [],
          {
            #productTrackingId: productTrackingId,
            #totalSales: totalSales,
          },
        ),
        returnValue: _i4.Future<_i2.RevenueSplit>.value(_FakeRevenueSplit_0(
          this,
          Invocation.method(
            #calculateProductSalesSplit,
            [],
            {
              #productTrackingId: productTrackingId,
              #totalSales: totalSales,
            },
          ),
        )),
      ) as _i4.Future<_i2.RevenueSplit>);

  @override
  _i4.Future<Map<String, _i2.RevenueSplit>> calculateHybridSplit({
    required String? eventId,
    required double? cashAmount,
    required double? productSalesAmount,
    required int? ticketsSold,
    required List<_i2.SplitParty>? parties,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateHybridSplit,
          [],
          {
            #eventId: eventId,
            #cashAmount: cashAmount,
            #productSalesAmount: productSalesAmount,
            #ticketsSold: ticketsSold,
            #parties: parties,
          },
        ),
        returnValue: _i4.Future<Map<String, _i2.RevenueSplit>>.value(
            <String, _i2.RevenueSplit>{}),
      ) as _i4.Future<Map<String, _i2.RevenueSplit>>);
}
