// Mocks generated by Mockito 5.4.6 from annotations
// in spots/test/unit/services/product_sales_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:spots/core/models/payment.dart' as _i7;
import 'package:spots/core/models/payment_intent.dart' as _i11;
import 'package:spots/core/models/payment_result.dart' as _i6;
import 'package:spots/core/models/product_tracking.dart' as _i2;
import 'package:spots/core/models/revenue_split.dart' as _i4;
import 'package:spots/core/services/payment_service.dart' as _i10;
import 'package:spots/core/services/product_tracking_service.dart' as _i3;
import 'package:spots/core/services/revenue_split_service.dart' as _i9;
import 'package:spots/core/services/stripe_service.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProductTracking_0 extends _i1.SmartFake
    implements _i2.ProductTracking {
  _FakeProductTracking_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductSalesReport_1 extends _i1.SmartFake
    implements _i3.ProductSalesReport {
  _FakeProductSalesReport_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRevenueSplit_2 extends _i1.SmartFake implements _i4.RevenueSplit {
  _FakeRevenueSplit_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStripeService_3 extends _i1.SmartFake implements _i5.StripeService {
  _FakeStripeService_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaymentResult_4 extends _i1.SmartFake implements _i6.PaymentResult {
  _FakePaymentResult_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePayment_5 extends _i1.SmartFake implements _i7.Payment {
  _FakePayment_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductTrackingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductTrackingService extends _i1.Mock
    implements _i3.ProductTrackingService {
  MockProductTrackingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.ProductTracking> recordProductContribution({
    required String? sponsorshipId,
    required String? productName,
    required int? quantityProvided,
    required double? unitPrice,
    String? sku,
    String? description,
    String? imageUrl,
    double? unitCostPrice,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordProductContribution,
          [],
          {
            #sponsorshipId: sponsorshipId,
            #productName: productName,
            #quantityProvided: quantityProvided,
            #unitPrice: unitPrice,
            #sku: sku,
            #description: description,
            #imageUrl: imageUrl,
            #unitCostPrice: unitCostPrice,
          },
        ),
        returnValue:
            _i8.Future<_i2.ProductTracking>.value(_FakeProductTracking_0(
          this,
          Invocation.method(
            #recordProductContribution,
            [],
            {
              #sponsorshipId: sponsorshipId,
              #productName: productName,
              #quantityProvided: quantityProvided,
              #unitPrice: unitPrice,
              #sku: sku,
              #description: description,
              #imageUrl: imageUrl,
              #unitCostPrice: unitCostPrice,
            },
          ),
        )),
      ) as _i8.Future<_i2.ProductTracking>);

  @override
  _i8.Future<_i2.ProductTracking> recordProductSale({
    required String? productTrackingId,
    required int? quantity,
    required String? buyerId,
    double? salePrice,
    String? paymentMethod,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordProductSale,
          [],
          {
            #productTrackingId: productTrackingId,
            #quantity: quantity,
            #buyerId: buyerId,
            #salePrice: salePrice,
            #paymentMethod: paymentMethod,
          },
        ),
        returnValue:
            _i8.Future<_i2.ProductTracking>.value(_FakeProductTracking_0(
          this,
          Invocation.method(
            #recordProductSale,
            [],
            {
              #productTrackingId: productTrackingId,
              #quantity: quantity,
              #buyerId: buyerId,
              #salePrice: salePrice,
              #paymentMethod: paymentMethod,
            },
          ),
        )),
      ) as _i8.Future<_i2.ProductTracking>);

  @override
  _i8.Future<Map<String, double>> calculateRevenueAttribution(
          {required String? productTrackingId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateRevenueAttribution,
          [],
          {#productTrackingId: productTrackingId},
        ),
        returnValue: _i8.Future<Map<String, double>>.value(<String, double>{}),
      ) as _i8.Future<Map<String, double>>);

  @override
  _i8.Future<_i2.ProductTracking> updateProductQuantity({
    required String? productTrackingId,
    int? quantitySold,
    int? quantityGivenAway,
    int? quantityUsedInEvent,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProductQuantity,
          [],
          {
            #productTrackingId: productTrackingId,
            #quantitySold: quantitySold,
            #quantityGivenAway: quantityGivenAway,
            #quantityUsedInEvent: quantityUsedInEvent,
          },
        ),
        returnValue:
            _i8.Future<_i2.ProductTracking>.value(_FakeProductTracking_0(
          this,
          Invocation.method(
            #updateProductQuantity,
            [],
            {
              #productTrackingId: productTrackingId,
              #quantitySold: quantitySold,
              #quantityGivenAway: quantityGivenAway,
              #quantityUsedInEvent: quantityUsedInEvent,
            },
          ),
        )),
      ) as _i8.Future<_i2.ProductTracking>);

  @override
  _i8.Future<_i2.ProductTracking?> getProductTrackingById(
          String? productTrackingId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductTrackingById,
          [productTrackingId],
        ),
        returnValue: _i8.Future<_i2.ProductTracking?>.value(),
      ) as _i8.Future<_i2.ProductTracking?>);

  @override
  _i8.Future<List<_i2.ProductTracking>> getProductTrackingForSponsorship(
          String? sponsorshipId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductTrackingForSponsorship,
          [sponsorshipId],
        ),
        returnValue: _i8.Future<List<_i2.ProductTracking>>.value(
            <_i2.ProductTracking>[]),
      ) as _i8.Future<List<_i2.ProductTracking>>);

  @override
  _i8.Future<_i3.ProductSalesReport> generateSalesReport({
    required String? sponsorshipId,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateSalesReport,
          [],
          {
            #sponsorshipId: sponsorshipId,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue:
            _i8.Future<_i3.ProductSalesReport>.value(_FakeProductSalesReport_1(
          this,
          Invocation.method(
            #generateSalesReport,
            [],
            {
              #sponsorshipId: sponsorshipId,
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i8.Future<_i3.ProductSalesReport>);
}

/// A class which mocks [RevenueSplitService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRevenueSplitService extends _i1.Mock
    implements _i9.RevenueSplitService {
  MockRevenueSplitService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i4.RevenueSplit> calculateNWaySplit({
    required String? eventId,
    String? partnershipId,
    required double? totalAmount,
    required int? ticketsSold,
    required List<_i4.SplitParty>? parties,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateNWaySplit,
          [],
          {
            #eventId: eventId,
            #partnershipId: partnershipId,
            #totalAmount: totalAmount,
            #ticketsSold: ticketsSold,
            #parties: parties,
          },
        ),
        returnValue: _i8.Future<_i4.RevenueSplit>.value(_FakeRevenueSplit_2(
          this,
          Invocation.method(
            #calculateNWaySplit,
            [],
            {
              #eventId: eventId,
              #partnershipId: partnershipId,
              #totalAmount: totalAmount,
              #ticketsSold: ticketsSold,
              #parties: parties,
            },
          ),
        )),
      ) as _i8.Future<_i4.RevenueSplit>);

  @override
  _i8.Future<_i4.RevenueSplit> calculateFromPartnership({
    required String? partnershipId,
    required double? totalAmount,
    required int? ticketsSold,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateFromPartnership,
          [],
          {
            #partnershipId: partnershipId,
            #totalAmount: totalAmount,
            #ticketsSold: ticketsSold,
          },
        ),
        returnValue: _i8.Future<_i4.RevenueSplit>.value(_FakeRevenueSplit_2(
          this,
          Invocation.method(
            #calculateFromPartnership,
            [],
            {
              #partnershipId: partnershipId,
              #totalAmount: totalAmount,
              #ticketsSold: ticketsSold,
            },
          ),
        )),
      ) as _i8.Future<_i4.RevenueSplit>);

  @override
  _i8.Future<_i4.RevenueSplit> lockSplit({
    required String? revenueSplitId,
    required String? lockedBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #lockSplit,
          [],
          {
            #revenueSplitId: revenueSplitId,
            #lockedBy: lockedBy,
          },
        ),
        returnValue: _i8.Future<_i4.RevenueSplit>.value(_FakeRevenueSplit_2(
          this,
          Invocation.method(
            #lockSplit,
            [],
            {
              #revenueSplitId: revenueSplitId,
              #lockedBy: lockedBy,
            },
          ),
        )),
      ) as _i8.Future<_i4.RevenueSplit>);

  @override
  _i8.Future<Map<String, double>> distributePayments({
    required String? revenueSplitId,
    required DateTime? eventEndTime,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #distributePayments,
          [],
          {
            #revenueSplitId: revenueSplitId,
            #eventEndTime: eventEndTime,
          },
        ),
        returnValue: _i8.Future<Map<String, double>>.value(<String, double>{}),
      ) as _i8.Future<Map<String, double>>);

  @override
  _i8.Future<double> trackEarnings({
    required String? partyId,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackEarnings,
          [],
          {
            #partyId: partyId,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i8.Future<double>.value(0.0),
      ) as _i8.Future<double>);

  @override
  _i8.Future<_i4.RevenueSplit?> getRevenueSplit(String? revenueSplitId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRevenueSplit,
          [revenueSplitId],
        ),
        returnValue: _i8.Future<_i4.RevenueSplit?>.value(),
      ) as _i8.Future<_i4.RevenueSplit?>);

  @override
  _i8.Future<List<_i4.RevenueSplit>> getRevenueSplitsForEvent(
          String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRevenueSplitsForEvent,
          [eventId],
        ),
        returnValue:
            _i8.Future<List<_i4.RevenueSplit>>.value(<_i4.RevenueSplit>[]),
      ) as _i8.Future<List<_i4.RevenueSplit>>);

  @override
  _i8.Future<_i4.RevenueSplit> calculateNWayBrandSplit({
    required String? eventId,
    required double? totalAmount,
    required int? ticketsSold,
    Map<String, double>? brandPercentages,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateNWayBrandSplit,
          [],
          {
            #eventId: eventId,
            #totalAmount: totalAmount,
            #ticketsSold: ticketsSold,
            #brandPercentages: brandPercentages,
          },
        ),
        returnValue: _i8.Future<_i4.RevenueSplit>.value(_FakeRevenueSplit_2(
          this,
          Invocation.method(
            #calculateNWayBrandSplit,
            [],
            {
              #eventId: eventId,
              #totalAmount: totalAmount,
              #ticketsSold: ticketsSold,
              #brandPercentages: brandPercentages,
            },
          ),
        )),
      ) as _i8.Future<_i4.RevenueSplit>);

  @override
  _i8.Future<_i4.RevenueSplit> calculateProductSalesSplit({
    required String? productTrackingId,
    required double? totalSales,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateProductSalesSplit,
          [],
          {
            #productTrackingId: productTrackingId,
            #totalSales: totalSales,
          },
        ),
        returnValue: _i8.Future<_i4.RevenueSplit>.value(_FakeRevenueSplit_2(
          this,
          Invocation.method(
            #calculateProductSalesSplit,
            [],
            {
              #productTrackingId: productTrackingId,
              #totalSales: totalSales,
            },
          ),
        )),
      ) as _i8.Future<_i4.RevenueSplit>);

  @override
  _i8.Future<Map<String, _i4.RevenueSplit>> calculateHybridSplit({
    required String? eventId,
    required double? cashAmount,
    required double? productSalesAmount,
    required int? ticketsSold,
    required List<_i4.SplitParty>? parties,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateHybridSplit,
          [],
          {
            #eventId: eventId,
            #cashAmount: cashAmount,
            #productSalesAmount: productSalesAmount,
            #ticketsSold: ticketsSold,
            #parties: parties,
          },
        ),
        returnValue: _i8.Future<Map<String, _i4.RevenueSplit>>.value(
            <String, _i4.RevenueSplit>{}),
      ) as _i8.Future<Map<String, _i4.RevenueSplit>>);
}

/// A class which mocks [PaymentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentService extends _i1.Mock implements _i10.PaymentService {
  MockPaymentService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i5.StripeService get stripeService => (super.noSuchMethod(
        Invocation.getter(#stripeService),
        returnValue: _FakeStripeService_3(
          this,
          Invocation.getter(#stripeService),
        ),
      ) as _i5.StripeService);

  @override
  _i8.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i6.PaymentResult> purchaseEventTicket({
    required String? eventId,
    required String? userId,
    required double? ticketPrice,
    required int? quantity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #purchaseEventTicket,
          [],
          {
            #eventId: eventId,
            #userId: userId,
            #ticketPrice: ticketPrice,
            #quantity: quantity,
          },
        ),
        returnValue: _i8.Future<_i6.PaymentResult>.value(_FakePaymentResult_4(
          this,
          Invocation.method(
            #purchaseEventTicket,
            [],
            {
              #eventId: eventId,
              #userId: userId,
              #ticketPrice: ticketPrice,
              #quantity: quantity,
            },
          ),
        )),
      ) as _i8.Future<_i6.PaymentResult>);

  @override
  _i4.RevenueSplit calculateRevenueSplit({
    required double? totalAmount,
    required int? ticketsSold,
    required String? eventId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateRevenueSplit,
          [],
          {
            #totalAmount: totalAmount,
            #ticketsSold: ticketsSold,
            #eventId: eventId,
          },
        ),
        returnValue: _FakeRevenueSplit_2(
          this,
          Invocation.method(
            #calculateRevenueSplit,
            [],
            {
              #totalAmount: totalAmount,
              #ticketsSold: ticketsSold,
              #eventId: eventId,
            },
          ),
        ),
      ) as _i4.RevenueSplit);

  @override
  _i8.Future<_i7.Payment> confirmPayment({
    required String? paymentId,
    required String? paymentIntentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmPayment,
          [],
          {
            #paymentId: paymentId,
            #paymentIntentId: paymentIntentId,
          },
        ),
        returnValue: _i8.Future<_i7.Payment>.value(_FakePayment_5(
          this,
          Invocation.method(
            #confirmPayment,
            [],
            {
              #paymentId: paymentId,
              #paymentIntentId: paymentIntentId,
            },
          ),
        )),
      ) as _i8.Future<_i7.Payment>);

  @override
  _i8.Future<void> handlePaymentFailure({
    required String? paymentId,
    required String? errorMessage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #handlePaymentFailure,
          [],
          {
            #paymentId: paymentId,
            #errorMessage: errorMessage,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i7.Payment? getPayment(String? paymentId) =>
      (super.noSuchMethod(Invocation.method(
        #getPayment,
        [paymentId],
      )) as _i7.Payment?);

  @override
  void upsertPaymentForTests(_i7.Payment? payment) => super.noSuchMethod(
        Invocation.method(
          #upsertPaymentForTests,
          [payment],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.PaymentIntent? getPaymentIntent(String? paymentIntentId) =>
      (super.noSuchMethod(Invocation.method(
        #getPaymentIntent,
        [paymentIntentId],
      )) as _i11.PaymentIntent?);

  @override
  List<_i7.Payment> getPaymentsForEvent(String? eventId) => (super.noSuchMethod(
        Invocation.method(
          #getPaymentsForEvent,
          [eventId],
        ),
        returnValue: <_i7.Payment>[],
      ) as List<_i7.Payment>);

  @override
  _i7.Payment? getPaymentForEventAndUser(
    String? eventId,
    String? userId,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getPaymentForEventAndUser,
        [
          eventId,
          userId,
        ],
      )) as _i7.Payment?);

  @override
  List<_i7.Payment> getPaymentsForUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getPaymentsForUser,
          [userId],
        ),
        returnValue: <_i7.Payment>[],
      ) as List<_i7.Payment>);

  @override
  List<_i7.Payment> getPaymentsForUserInYear(
    String? userId,
    int? year,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaymentsForUserInYear,
          [
            userId,
            year,
          ],
        ),
        returnValue: <_i7.Payment>[],
      ) as List<_i7.Payment>);

  @override
  _i8.Future<bool> hasPartnership(String? eventId) => (super.noSuchMethod(
        Invocation.method(
          #hasPartnership,
          [eventId],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<_i4.RevenueSplit> calculatePartnershipRevenueSplit({
    required String? eventId,
    required double? totalAmount,
    required int? ticketsSold,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculatePartnershipRevenueSplit,
          [],
          {
            #eventId: eventId,
            #totalAmount: totalAmount,
            #ticketsSold: ticketsSold,
          },
        ),
        returnValue: _i8.Future<_i4.RevenueSplit>.value(_FakeRevenueSplit_2(
          this,
          Invocation.method(
            #calculatePartnershipRevenueSplit,
            [],
            {
              #eventId: eventId,
              #totalAmount: totalAmount,
              #ticketsSold: ticketsSold,
            },
          ),
        )),
      ) as _i8.Future<_i4.RevenueSplit>);

  @override
  _i8.Future<Map<String, double>> distributePartnershipPayment({
    required String? paymentId,
    required String? partnershipId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #distributePartnershipPayment,
          [],
          {
            #paymentId: paymentId,
            #partnershipId: partnershipId,
          },
        ),
        returnValue: _i8.Future<Map<String, double>>.value(<String, double>{}),
      ) as _i8.Future<Map<String, double>>);
}
