// Mocks generated by Mockito 5.4.6 from annotations
// in spots/test/unit/services/quantum_satisfaction_enhancer_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:spots/core/ai/quantum/location_quantum_state.dart' as _i6;
import 'package:spots/core/ai/quantum/quantum_satisfaction_feature_extractor.dart'
    as _i3;
import 'package:spots/core/ai/quantum/quantum_temporal_state.dart' as _i5;
import 'package:spots/core/models/quantum_satisfaction_features.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeQuantumSatisfactionFeatures_0 extends _i1.SmartFake
    implements _i2.QuantumSatisfactionFeatures {
  _FakeQuantumSatisfactionFeatures_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [QuantumSatisfactionFeatureExtractor].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuantumSatisfactionFeatureExtractor extends _i1.Mock
    implements _i3.QuantumSatisfactionFeatureExtractor {
  MockQuantumSatisfactionFeatureExtractor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.QuantumSatisfactionFeatures> extractFeatures({
    required String? userId,
    required Map<String, double>? userVibeDimensions,
    required Map<String, double>? eventVibeDimensions,
    required _i5.QuantumTemporalState? userTemporalState,
    required _i5.QuantumTemporalState? eventTemporalState,
    _i6.LocationQuantumState? userLocationState,
    _i6.LocationQuantumState? eventLocationState,
    required double? contextMatch,
    required double? preferenceAlignment,
    required double? noveltyScore,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #extractFeatures,
          [],
          {
            #userId: userId,
            #userVibeDimensions: userVibeDimensions,
            #eventVibeDimensions: eventVibeDimensions,
            #userTemporalState: userTemporalState,
            #eventTemporalState: eventTemporalState,
            #userLocationState: userLocationState,
            #eventLocationState: eventLocationState,
            #contextMatch: contextMatch,
            #preferenceAlignment: preferenceAlignment,
            #noveltyScore: noveltyScore,
          },
        ),
        returnValue: _i4.Future<_i2.QuantumSatisfactionFeatures>.value(
            _FakeQuantumSatisfactionFeatures_0(
          this,
          Invocation.method(
            #extractFeatures,
            [],
            {
              #userId: userId,
              #userVibeDimensions: userVibeDimensions,
              #eventVibeDimensions: eventVibeDimensions,
              #userTemporalState: userTemporalState,
              #eventTemporalState: eventTemporalState,
              #userLocationState: userLocationState,
              #eventLocationState: eventLocationState,
              #contextMatch: contextMatch,
              #preferenceAlignment: preferenceAlignment,
              #noveltyScore: noveltyScore,
            },
          ),
        )),
      ) as _i4.Future<_i2.QuantumSatisfactionFeatures>);
}
