// Mocks generated by Mockito 5.4.6 from annotations
// in spots/test/unit/services/refund_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:flutter_stripe/flutter_stripe.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:spots/core/models/payment.dart' as _i6;
import 'package:spots/core/models/payment_intent.dart' as _i10;
import 'package:spots/core/models/payment_result.dart' as _i4;
import 'package:spots/core/models/revenue_split.dart' as _i5;
import 'package:spots/core/services/payment_service.dart' as _i9;
import 'package:spots/core/services/stripe_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePaymentIntent_0 extends _i1.SmartFake implements _i2.PaymentIntent {
  _FakePaymentIntent_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStripeService_1 extends _i1.SmartFake implements _i3.StripeService {
  _FakeStripeService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaymentResult_2 extends _i1.SmartFake implements _i4.PaymentResult {
  _FakePaymentResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRevenueSplit_3 extends _i1.SmartFake implements _i5.RevenueSplit {
  _FakeRevenueSplit_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePayment_4 extends _i1.SmartFake implements _i6.Payment {
  _FakePayment_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StripeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStripeService extends _i1.Mock implements _i3.StripeService {
  MockStripeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> initializeStripe() => (super.noSuchMethod(
        Invocation.method(
          #initializeStripe,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String> createPaymentIntent({
    required int? amount,
    String? currency = 'usd',
    Map<String, String>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPaymentIntent,
          [],
          {
            #amount: amount,
            #currency: currency,
            #metadata: metadata,
          },
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #createPaymentIntent,
            [],
            {
              #amount: amount,
              #currency: currency,
              #metadata: metadata,
            },
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<_i2.PaymentIntent> confirmPayment({
    required String? clientSecret,
    String? paymentMethodId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmPayment,
          [],
          {
            #clientSecret: clientSecret,
            #paymentMethodId: paymentMethodId,
          },
        ),
        returnValue: _i7.Future<_i2.PaymentIntent>.value(_FakePaymentIntent_0(
          this,
          Invocation.method(
            #confirmPayment,
            [],
            {
              #clientSecret: clientSecret,
              #paymentMethodId: paymentMethodId,
            },
          ),
        )),
      ) as _i7.Future<_i2.PaymentIntent>);

  @override
  _i7.Future<String> processRefund({
    required String? paymentIntentId,
    int? amount,
    String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #processRefund,
          [],
          {
            #paymentIntentId: paymentIntentId,
            #amount: amount,
            #reason: reason,
          },
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #processRefund,
            [],
            {
              #paymentIntentId: paymentIntentId,
              #amount: amount,
              #reason: reason,
            },
          ),
        )),
      ) as _i7.Future<String>);

  @override
  String handlePaymentError(dynamic error) => (super.noSuchMethod(
        Invocation.method(
          #handlePaymentError,
          [error],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #handlePaymentError,
            [error],
          ),
        ),
      ) as String);
}

/// A class which mocks [PaymentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentService extends _i1.Mock implements _i9.PaymentService {
  MockPaymentService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i3.StripeService get stripeService => (super.noSuchMethod(
        Invocation.getter(#stripeService),
        returnValue: _FakeStripeService_1(
          this,
          Invocation.getter(#stripeService),
        ),
      ) as _i3.StripeService);

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i4.PaymentResult> purchaseEventTicket({
    required String? eventId,
    required String? userId,
    required double? ticketPrice,
    required int? quantity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #purchaseEventTicket,
          [],
          {
            #eventId: eventId,
            #userId: userId,
            #ticketPrice: ticketPrice,
            #quantity: quantity,
          },
        ),
        returnValue: _i7.Future<_i4.PaymentResult>.value(_FakePaymentResult_2(
          this,
          Invocation.method(
            #purchaseEventTicket,
            [],
            {
              #eventId: eventId,
              #userId: userId,
              #ticketPrice: ticketPrice,
              #quantity: quantity,
            },
          ),
        )),
      ) as _i7.Future<_i4.PaymentResult>);

  @override
  _i5.RevenueSplit calculateRevenueSplit({
    required double? totalAmount,
    required int? ticketsSold,
    required String? eventId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateRevenueSplit,
          [],
          {
            #totalAmount: totalAmount,
            #ticketsSold: ticketsSold,
            #eventId: eventId,
          },
        ),
        returnValue: _FakeRevenueSplit_3(
          this,
          Invocation.method(
            #calculateRevenueSplit,
            [],
            {
              #totalAmount: totalAmount,
              #ticketsSold: ticketsSold,
              #eventId: eventId,
            },
          ),
        ),
      ) as _i5.RevenueSplit);

  @override
  _i7.Future<_i6.Payment> confirmPayment({
    required String? paymentId,
    required String? paymentIntentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmPayment,
          [],
          {
            #paymentId: paymentId,
            #paymentIntentId: paymentIntentId,
          },
        ),
        returnValue: _i7.Future<_i6.Payment>.value(_FakePayment_4(
          this,
          Invocation.method(
            #confirmPayment,
            [],
            {
              #paymentId: paymentId,
              #paymentIntentId: paymentIntentId,
            },
          ),
        )),
      ) as _i7.Future<_i6.Payment>);

  @override
  _i7.Future<void> handlePaymentFailure({
    required String? paymentId,
    required String? errorMessage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #handlePaymentFailure,
          [],
          {
            #paymentId: paymentId,
            #errorMessage: errorMessage,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i6.Payment? getPayment(String? paymentId) =>
      (super.noSuchMethod(Invocation.method(
        #getPayment,
        [paymentId],
      )) as _i6.Payment?);

  @override
  void upsertPaymentForTests(_i6.Payment? payment) => super.noSuchMethod(
        Invocation.method(
          #upsertPaymentForTests,
          [payment],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.PaymentIntent? getPaymentIntent(String? paymentIntentId) =>
      (super.noSuchMethod(Invocation.method(
        #getPaymentIntent,
        [paymentIntentId],
      )) as _i10.PaymentIntent?);

  @override
  List<_i6.Payment> getPaymentsForEvent(String? eventId) => (super.noSuchMethod(
        Invocation.method(
          #getPaymentsForEvent,
          [eventId],
        ),
        returnValue: <_i6.Payment>[],
      ) as List<_i6.Payment>);

  @override
  _i6.Payment? getPaymentForEventAndUser(
    String? eventId,
    String? userId,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getPaymentForEventAndUser,
        [
          eventId,
          userId,
        ],
      )) as _i6.Payment?);

  @override
  List<_i6.Payment> getPaymentsForUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getPaymentsForUser,
          [userId],
        ),
        returnValue: <_i6.Payment>[],
      ) as List<_i6.Payment>);

  @override
  List<_i6.Payment> getPaymentsForUserInYear(
    String? userId,
    int? year,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaymentsForUserInYear,
          [
            userId,
            year,
          ],
        ),
        returnValue: <_i6.Payment>[],
      ) as List<_i6.Payment>);

  @override
  _i7.Future<bool> hasPartnership(String? eventId) => (super.noSuchMethod(
        Invocation.method(
          #hasPartnership,
          [eventId],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<_i5.RevenueSplit> calculatePartnershipRevenueSplit({
    required String? eventId,
    required double? totalAmount,
    required int? ticketsSold,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculatePartnershipRevenueSplit,
          [],
          {
            #eventId: eventId,
            #totalAmount: totalAmount,
            #ticketsSold: ticketsSold,
          },
        ),
        returnValue: _i7.Future<_i5.RevenueSplit>.value(_FakeRevenueSplit_3(
          this,
          Invocation.method(
            #calculatePartnershipRevenueSplit,
            [],
            {
              #eventId: eventId,
              #totalAmount: totalAmount,
              #ticketsSold: ticketsSold,
            },
          ),
        )),
      ) as _i7.Future<_i5.RevenueSplit>);

  @override
  _i7.Future<Map<String, double>> distributePartnershipPayment({
    required String? paymentId,
    required String? partnershipId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #distributePartnershipPayment,
          [],
          {
            #paymentId: paymentId,
            #partnershipId: partnershipId,
          },
        ),
        returnValue: _i7.Future<Map<String, double>>.value(<String, double>{}),
      ) as _i7.Future<Map<String, double>>);
}
