// Mocks generated by Mockito 5.4.6 from annotations
// in avrai/test/unit/services/sponsorship_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:avrai/core/models/event_partnership.dart' as _i3;
import 'package:avrai/core/models/expertise_event.dart' as _i2;
import 'package:avrai/core/models/spot.dart' as _i7;
import 'package:avrai/core/models/unified_user.dart' as _i6;
import 'package:avrai/core/services/expertise_event_service.dart' as _i4;
import 'package:avrai/core/services/partnership_service.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeExpertiseEvent_0 extends _i1.SmartFake
    implements _i2.ExpertiseEvent {
  _FakeExpertiseEvent_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEventPartnership_1 extends _i1.SmartFake
    implements _i3.EventPartnership {
  _FakeEventPartnership_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ExpertiseEventService].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpertiseEventService extends _i1.Mock
    implements _i4.ExpertiseEventService {
  MockExpertiseEventService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ExpertiseEvent> createEvent({
    required _i6.UnifiedUser? host,
    required String? title,
    required String? description,
    required String? category,
    required _i2.ExpertiseEventType? eventType,
    required DateTime? startTime,
    required DateTime? endTime,
    List<_i7.Spot>? spots,
    String? location,
    double? latitude,
    double? longitude,
    String? cityCode,
    String? localityCode,
    int? maxAttendees = 20,
    double? price,
    bool? isPublic = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEvent,
          [],
          {
            #host: host,
            #title: title,
            #description: description,
            #category: category,
            #eventType: eventType,
            #startTime: startTime,
            #endTime: endTime,
            #spots: spots,
            #location: location,
            #latitude: latitude,
            #longitude: longitude,
            #cityCode: cityCode,
            #localityCode: localityCode,
            #maxAttendees: maxAttendees,
            #price: price,
            #isPublic: isPublic,
          },
        ),
        returnValue: _i5.Future<_i2.ExpertiseEvent>.value(_FakeExpertiseEvent_0(
          this,
          Invocation.method(
            #createEvent,
            [],
            {
              #host: host,
              #title: title,
              #description: description,
              #category: category,
              #eventType: eventType,
              #startTime: startTime,
              #endTime: endTime,
              #spots: spots,
              #location: location,
              #latitude: latitude,
              #longitude: longitude,
              #cityCode: cityCode,
              #localityCode: localityCode,
              #maxAttendees: maxAttendees,
              #price: price,
              #isPublic: isPublic,
            },
          ),
        )),
      ) as _i5.Future<_i2.ExpertiseEvent>);

  @override
  _i5.Future<_i2.ExpertiseEvent> duplicateEvent({
    required _i2.ExpertiseEvent? originalEvent,
    DateTime? newStartTime,
    bool? autoSuggestTime = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #duplicateEvent,
          [],
          {
            #originalEvent: originalEvent,
            #newStartTime: newStartTime,
            #autoSuggestTime: autoSuggestTime,
          },
        ),
        returnValue: _i5.Future<_i2.ExpertiseEvent>.value(_FakeExpertiseEvent_0(
          this,
          Invocation.method(
            #duplicateEvent,
            [],
            {
              #originalEvent: originalEvent,
              #newStartTime: newStartTime,
              #autoSuggestTime: autoSuggestTime,
            },
          ),
        )),
      ) as _i5.Future<_i2.ExpertiseEvent>);

  @override
  _i5.Future<void> registerForEvent(
    _i2.ExpertiseEvent? event,
    _i6.UnifiedUser? user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerForEvent,
          [
            event,
            user,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cancelRegistration(
    _i2.ExpertiseEvent? event,
    _i6.UnifiedUser? user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelRegistration,
          [
            event,
            user,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.ExpertiseEvent>> getEventsByHost(_i6.UnifiedUser? host) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsByHost,
          [host],
        ),
        returnValue:
            _i5.Future<List<_i2.ExpertiseEvent>>.value(<_i2.ExpertiseEvent>[]),
      ) as _i5.Future<List<_i2.ExpertiseEvent>>);

  @override
  _i5.Future<List<_i2.ExpertiseEvent>> getEventsByAttendee(
          _i6.UnifiedUser? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsByAttendee,
          [user],
        ),
        returnValue:
            _i5.Future<List<_i2.ExpertiseEvent>>.value(<_i2.ExpertiseEvent>[]),
      ) as _i5.Future<List<_i2.ExpertiseEvent>>);

  @override
  _i5.Future<_i2.ExpertiseEvent?> getEventById(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventById,
          [eventId],
        ),
        returnValue: _i5.Future<_i2.ExpertiseEvent?>.value(),
      ) as _i5.Future<_i2.ExpertiseEvent?>);

  @override
  _i5.Future<List<_i2.ExpertiseEvent>> searchEvents({
    String? category,
    String? location,
    _i2.ExpertiseEventType? eventType,
    DateTime? startDate,
    DateTime? endDate,
    int? maxResults = 20,
    bool? includeCommunityEvents = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEvents,
          [],
          {
            #category: category,
            #location: location,
            #eventType: eventType,
            #startDate: startDate,
            #endDate: endDate,
            #maxResults: maxResults,
            #includeCommunityEvents: includeCommunityEvents,
          },
        ),
        returnValue:
            _i5.Future<List<_i2.ExpertiseEvent>>.value(<_i2.ExpertiseEvent>[]),
      ) as _i5.Future<List<_i2.ExpertiseEvent>>);

  @override
  _i5.Future<List<_i2.ExpertiseEvent>> getUpcomingEventsInCategory(
    String? category, {
    int? maxResults = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUpcomingEventsInCategory,
          [category],
          {#maxResults: maxResults},
        ),
        returnValue:
            _i5.Future<List<_i2.ExpertiseEvent>>.value(<_i2.ExpertiseEvent>[]),
      ) as _i5.Future<List<_i2.ExpertiseEvent>>);

  @override
  _i5.Future<List<_i2.ExpertiseEvent>> searchEventsWithConnectedLocalities({
    required _i6.UnifiedUser? user,
    String? category,
    String? location,
    _i2.ExpertiseEventType? eventType,
    DateTime? startDate,
    DateTime? endDate,
    int? maxResults = 20,
    bool? includeConnectedLocalities = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEventsWithConnectedLocalities,
          [],
          {
            #user: user,
            #category: category,
            #location: location,
            #eventType: eventType,
            #startDate: startDate,
            #endDate: endDate,
            #maxResults: maxResults,
            #includeConnectedLocalities: includeConnectedLocalities,
          },
        ),
        returnValue:
            _i5.Future<List<_i2.ExpertiseEvent>>.value(<_i2.ExpertiseEvent>[]),
      ) as _i5.Future<List<_i2.ExpertiseEvent>>);

  @override
  _i5.Future<void> updateEventStatus(
    _i2.ExpertiseEvent? event,
    _i2.EventStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEventStatus,
          [
            event,
            status,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [PartnershipService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPartnershipService extends _i1.Mock
    implements _i8.PartnershipService {
  MockPartnershipService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.EventPartnership> createPartnership({
    required String? eventId,
    required String? userId,
    required String? businessId,
    _i3.PartnershipAgreement? agreement,
    _i3.PartnershipType? type = _i3.PartnershipType.eventBased,
    List<String>? sharedResponsibilities,
    String? venueLocation,
    double? vibeCompatibilityScore,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPartnership,
          [],
          {
            #eventId: eventId,
            #userId: userId,
            #businessId: businessId,
            #agreement: agreement,
            #type: type,
            #sharedResponsibilities: sharedResponsibilities,
            #venueLocation: venueLocation,
            #vibeCompatibilityScore: vibeCompatibilityScore,
          },
        ),
        returnValue:
            _i5.Future<_i3.EventPartnership>.value(_FakeEventPartnership_1(
          this,
          Invocation.method(
            #createPartnership,
            [],
            {
              #eventId: eventId,
              #userId: userId,
              #businessId: businessId,
              #agreement: agreement,
              #type: type,
              #sharedResponsibilities: sharedResponsibilities,
              #venueLocation: venueLocation,
              #vibeCompatibilityScore: vibeCompatibilityScore,
            },
          ),
        )),
      ) as _i5.Future<_i3.EventPartnership>);

  @override
  _i5.Future<List<_i3.EventPartnership>> getPartnershipsForEvent(
          String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPartnershipsForEvent,
          [eventId],
        ),
        returnValue: _i5.Future<List<_i3.EventPartnership>>.value(
            <_i3.EventPartnership>[]),
      ) as _i5.Future<List<_i3.EventPartnership>>);

  @override
  _i5.Future<_i3.EventPartnership?> getPartnershipById(String? partnershipId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPartnershipById,
          [partnershipId],
        ),
        returnValue: _i5.Future<_i3.EventPartnership?>.value(),
      ) as _i5.Future<_i3.EventPartnership?>);

  @override
  _i5.Future<_i3.EventPartnership> updatePartnershipStatus({
    required String? partnershipId,
    required _i3.PartnershipStatus? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePartnershipStatus,
          [],
          {
            #partnershipId: partnershipId,
            #status: status,
          },
        ),
        returnValue:
            _i5.Future<_i3.EventPartnership>.value(_FakeEventPartnership_1(
          this,
          Invocation.method(
            #updatePartnershipStatus,
            [],
            {
              #partnershipId: partnershipId,
              #status: status,
            },
          ),
        )),
      ) as _i5.Future<_i3.EventPartnership>);

  @override
  _i5.Future<_i3.EventPartnership> approvePartnership({
    required String? partnershipId,
    required String? approvedBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #approvePartnership,
          [],
          {
            #partnershipId: partnershipId,
            #approvedBy: approvedBy,
          },
        ),
        returnValue:
            _i5.Future<_i3.EventPartnership>.value(_FakeEventPartnership_1(
          this,
          Invocation.method(
            #approvePartnership,
            [],
            {
              #partnershipId: partnershipId,
              #approvedBy: approvedBy,
            },
          ),
        )),
      ) as _i5.Future<_i3.EventPartnership>);

  @override
  _i5.Future<bool> checkPartnershipEligibility({
    required String? userId,
    required String? businessId,
    required String? eventId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkPartnershipEligibility,
          [],
          {
            #userId: userId,
            #businessId: businessId,
            #eventId: eventId,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<double> calculateVibeCompatibility({
    required String? userId,
    required String? businessId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateVibeCompatibility,
          [],
          {
            #userId: userId,
            #businessId: businessId,
          },
        ),
        returnValue: _i5.Future<double>.value(0.0),
      ) as _i5.Future<double>);
}
