// Mocks generated by Mockito 5.4.6 from annotations
// in spots/test/unit/controllers/event_cancellation_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:spots/core/models/cancellation.dart' as _i2;
import 'package:spots/core/models/expertise_event.dart' as _i3;
import 'package:spots/core/models/payment.dart' as _i7;
import 'package:spots/core/models/payment_intent.dart' as _i14;
import 'package:spots/core/models/payment_result.dart' as _i5;
import 'package:spots/core/models/revenue_split.dart' as _i6;
import 'package:spots/core/models/spot.dart' as _i12;
import 'package:spots/core/models/unified_user.dart' as _i11;
import 'package:spots/core/services/cancellation_service.dart' as _i8;
import 'package:spots/core/services/expertise_event_service.dart' as _i10;
import 'package:spots/core/services/payment_service.dart' as _i13;
import 'package:spots/core/services/stripe_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCancellation_0 extends _i1.SmartFake implements _i2.Cancellation {
  _FakeCancellation_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExpertiseEvent_1 extends _i1.SmartFake
    implements _i3.ExpertiseEvent {
  _FakeExpertiseEvent_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStripeService_2 extends _i1.SmartFake implements _i4.StripeService {
  _FakeStripeService_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaymentResult_3 extends _i1.SmartFake implements _i5.PaymentResult {
  _FakePaymentResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRevenueSplit_4 extends _i1.SmartFake implements _i6.RevenueSplit {
  _FakeRevenueSplit_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePayment_5 extends _i1.SmartFake implements _i7.Payment {
  _FakePayment_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CancellationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCancellationService extends _i1.Mock
    implements _i8.CancellationService {
  MockCancellationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.Cancellation> attendeeCancelTicket({
    required String? eventId,
    required String? attendeeId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #attendeeCancelTicket,
          [],
          {
            #eventId: eventId,
            #attendeeId: attendeeId,
          },
        ),
        returnValue: _i9.Future<_i2.Cancellation>.value(_FakeCancellation_0(
          this,
          Invocation.method(
            #attendeeCancelTicket,
            [],
            {
              #eventId: eventId,
              #attendeeId: attendeeId,
            },
          ),
        )),
      ) as _i9.Future<_i2.Cancellation>);

  @override
  _i9.Future<_i2.Cancellation> hostCancelEvent({
    required String? eventId,
    required String? hostId,
    required String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #hostCancelEvent,
          [],
          {
            #eventId: eventId,
            #hostId: hostId,
            #reason: reason,
          },
        ),
        returnValue: _i9.Future<_i2.Cancellation>.value(_FakeCancellation_0(
          this,
          Invocation.method(
            #hostCancelEvent,
            [],
            {
              #eventId: eventId,
              #hostId: hostId,
              #reason: reason,
            },
          ),
        )),
      ) as _i9.Future<_i2.Cancellation>);

  @override
  _i9.Future<_i2.Cancellation> emergencyCancelEvent({
    required String? eventId,
    required String? reason,
    required bool? weatherRelated,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #emergencyCancelEvent,
          [],
          {
            #eventId: eventId,
            #reason: reason,
            #weatherRelated: weatherRelated,
          },
        ),
        returnValue: _i9.Future<_i2.Cancellation>.value(_FakeCancellation_0(
          this,
          Invocation.method(
            #emergencyCancelEvent,
            [],
            {
              #eventId: eventId,
              #reason: reason,
              #weatherRelated: weatherRelated,
            },
          ),
        )),
      ) as _i9.Future<_i2.Cancellation>);

  @override
  _i9.Future<_i2.Cancellation?> getCancellation(String? cancellationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCancellation,
          [cancellationId],
        ),
        returnValue: _i9.Future<_i2.Cancellation?>.value(),
      ) as _i9.Future<_i2.Cancellation?>);

  @override
  _i9.Future<List<_i2.Cancellation>> getCancellationsForEvent(
          String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCancellationsForEvent,
          [eventId],
        ),
        returnValue:
            _i9.Future<List<_i2.Cancellation>>.value(<_i2.Cancellation>[]),
      ) as _i9.Future<List<_i2.Cancellation>>);
}

/// A class which mocks [ExpertiseEventService].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpertiseEventService extends _i1.Mock
    implements _i10.ExpertiseEventService {
  MockExpertiseEventService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i3.ExpertiseEvent> createEvent({
    required _i11.UnifiedUser? host,
    required String? title,
    required String? description,
    required String? category,
    required _i3.ExpertiseEventType? eventType,
    required DateTime? startTime,
    required DateTime? endTime,
    List<_i12.Spot>? spots,
    String? location,
    double? latitude,
    double? longitude,
    int? maxAttendees = 20,
    double? price,
    bool? isPublic = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEvent,
          [],
          {
            #host: host,
            #title: title,
            #description: description,
            #category: category,
            #eventType: eventType,
            #startTime: startTime,
            #endTime: endTime,
            #spots: spots,
            #location: location,
            #latitude: latitude,
            #longitude: longitude,
            #maxAttendees: maxAttendees,
            #price: price,
            #isPublic: isPublic,
          },
        ),
        returnValue: _i9.Future<_i3.ExpertiseEvent>.value(_FakeExpertiseEvent_1(
          this,
          Invocation.method(
            #createEvent,
            [],
            {
              #host: host,
              #title: title,
              #description: description,
              #category: category,
              #eventType: eventType,
              #startTime: startTime,
              #endTime: endTime,
              #spots: spots,
              #location: location,
              #latitude: latitude,
              #longitude: longitude,
              #maxAttendees: maxAttendees,
              #price: price,
              #isPublic: isPublic,
            },
          ),
        )),
      ) as _i9.Future<_i3.ExpertiseEvent>);

  @override
  _i9.Future<_i3.ExpertiseEvent> duplicateEvent({
    required _i3.ExpertiseEvent? originalEvent,
    DateTime? newStartTime,
    bool? autoSuggestTime = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #duplicateEvent,
          [],
          {
            #originalEvent: originalEvent,
            #newStartTime: newStartTime,
            #autoSuggestTime: autoSuggestTime,
          },
        ),
        returnValue: _i9.Future<_i3.ExpertiseEvent>.value(_FakeExpertiseEvent_1(
          this,
          Invocation.method(
            #duplicateEvent,
            [],
            {
              #originalEvent: originalEvent,
              #newStartTime: newStartTime,
              #autoSuggestTime: autoSuggestTime,
            },
          ),
        )),
      ) as _i9.Future<_i3.ExpertiseEvent>);

  @override
  _i9.Future<void> registerForEvent(
    _i3.ExpertiseEvent? event,
    _i11.UnifiedUser? user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerForEvent,
          [
            event,
            user,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> cancelRegistration(
    _i3.ExpertiseEvent? event,
    _i11.UnifiedUser? user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelRegistration,
          [
            event,
            user,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<List<_i3.ExpertiseEvent>> getEventsByHost(
          _i11.UnifiedUser? host) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsByHost,
          [host],
        ),
        returnValue:
            _i9.Future<List<_i3.ExpertiseEvent>>.value(<_i3.ExpertiseEvent>[]),
      ) as _i9.Future<List<_i3.ExpertiseEvent>>);

  @override
  _i9.Future<List<_i3.ExpertiseEvent>> getEventsByAttendee(
          _i11.UnifiedUser? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsByAttendee,
          [user],
        ),
        returnValue:
            _i9.Future<List<_i3.ExpertiseEvent>>.value(<_i3.ExpertiseEvent>[]),
      ) as _i9.Future<List<_i3.ExpertiseEvent>>);

  @override
  _i9.Future<_i3.ExpertiseEvent?> getEventById(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventById,
          [eventId],
        ),
        returnValue: _i9.Future<_i3.ExpertiseEvent?>.value(),
      ) as _i9.Future<_i3.ExpertiseEvent?>);

  @override
  _i9.Future<List<_i3.ExpertiseEvent>> searchEvents({
    String? category,
    String? location,
    _i3.ExpertiseEventType? eventType,
    DateTime? startDate,
    DateTime? endDate,
    int? maxResults = 20,
    bool? includeCommunityEvents = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEvents,
          [],
          {
            #category: category,
            #location: location,
            #eventType: eventType,
            #startDate: startDate,
            #endDate: endDate,
            #maxResults: maxResults,
            #includeCommunityEvents: includeCommunityEvents,
          },
        ),
        returnValue:
            _i9.Future<List<_i3.ExpertiseEvent>>.value(<_i3.ExpertiseEvent>[]),
      ) as _i9.Future<List<_i3.ExpertiseEvent>>);

  @override
  _i9.Future<List<_i3.ExpertiseEvent>> getUpcomingEventsInCategory(
    String? category, {
    int? maxResults = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUpcomingEventsInCategory,
          [category],
          {#maxResults: maxResults},
        ),
        returnValue:
            _i9.Future<List<_i3.ExpertiseEvent>>.value(<_i3.ExpertiseEvent>[]),
      ) as _i9.Future<List<_i3.ExpertiseEvent>>);

  @override
  _i9.Future<List<_i3.ExpertiseEvent>> searchEventsWithConnectedLocalities({
    required _i11.UnifiedUser? user,
    String? category,
    String? location,
    _i3.ExpertiseEventType? eventType,
    DateTime? startDate,
    DateTime? endDate,
    int? maxResults = 20,
    bool? includeConnectedLocalities = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEventsWithConnectedLocalities,
          [],
          {
            #user: user,
            #category: category,
            #location: location,
            #eventType: eventType,
            #startDate: startDate,
            #endDate: endDate,
            #maxResults: maxResults,
            #includeConnectedLocalities: includeConnectedLocalities,
          },
        ),
        returnValue:
            _i9.Future<List<_i3.ExpertiseEvent>>.value(<_i3.ExpertiseEvent>[]),
      ) as _i9.Future<List<_i3.ExpertiseEvent>>);

  @override
  _i9.Future<void> updateEventStatus(
    _i3.ExpertiseEvent? event,
    _i3.EventStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEventStatus,
          [
            event,
            status,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [PaymentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentService extends _i1.Mock implements _i13.PaymentService {
  MockPaymentService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i4.StripeService get stripeService => (super.noSuchMethod(
        Invocation.getter(#stripeService),
        returnValue: _FakeStripeService_2(
          this,
          Invocation.getter(#stripeService),
        ),
      ) as _i4.StripeService);

  @override
  _i9.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i5.PaymentResult> purchaseEventTicket({
    required String? eventId,
    required String? userId,
    required double? ticketPrice,
    required int? quantity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #purchaseEventTicket,
          [],
          {
            #eventId: eventId,
            #userId: userId,
            #ticketPrice: ticketPrice,
            #quantity: quantity,
          },
        ),
        returnValue: _i9.Future<_i5.PaymentResult>.value(_FakePaymentResult_3(
          this,
          Invocation.method(
            #purchaseEventTicket,
            [],
            {
              #eventId: eventId,
              #userId: userId,
              #ticketPrice: ticketPrice,
              #quantity: quantity,
            },
          ),
        )),
      ) as _i9.Future<_i5.PaymentResult>);

  @override
  _i6.RevenueSplit calculateRevenueSplit({
    required double? totalAmount,
    required int? ticketsSold,
    required String? eventId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateRevenueSplit,
          [],
          {
            #totalAmount: totalAmount,
            #ticketsSold: ticketsSold,
            #eventId: eventId,
          },
        ),
        returnValue: _FakeRevenueSplit_4(
          this,
          Invocation.method(
            #calculateRevenueSplit,
            [],
            {
              #totalAmount: totalAmount,
              #ticketsSold: ticketsSold,
              #eventId: eventId,
            },
          ),
        ),
      ) as _i6.RevenueSplit);

  @override
  _i9.Future<_i7.Payment> confirmPayment({
    required String? paymentId,
    required String? paymentIntentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmPayment,
          [],
          {
            #paymentId: paymentId,
            #paymentIntentId: paymentIntentId,
          },
        ),
        returnValue: _i9.Future<_i7.Payment>.value(_FakePayment_5(
          this,
          Invocation.method(
            #confirmPayment,
            [],
            {
              #paymentId: paymentId,
              #paymentIntentId: paymentIntentId,
            },
          ),
        )),
      ) as _i9.Future<_i7.Payment>);

  @override
  _i9.Future<void> handlePaymentFailure({
    required String? paymentId,
    required String? errorMessage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #handlePaymentFailure,
          [],
          {
            #paymentId: paymentId,
            #errorMessage: errorMessage,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i7.Payment? getPayment(String? paymentId) =>
      (super.noSuchMethod(Invocation.method(
        #getPayment,
        [paymentId],
      )) as _i7.Payment?);

  @override
  void upsertPaymentForTests(_i7.Payment? payment) => super.noSuchMethod(
        Invocation.method(
          #upsertPaymentForTests,
          [payment],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i14.PaymentIntent? getPaymentIntent(String? paymentIntentId) =>
      (super.noSuchMethod(Invocation.method(
        #getPaymentIntent,
        [paymentIntentId],
      )) as _i14.PaymentIntent?);

  @override
  List<_i7.Payment> getPaymentsForEvent(String? eventId) => (super.noSuchMethod(
        Invocation.method(
          #getPaymentsForEvent,
          [eventId],
        ),
        returnValue: <_i7.Payment>[],
      ) as List<_i7.Payment>);

  @override
  _i7.Payment? getPaymentForEventAndUser(
    String? eventId,
    String? userId,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getPaymentForEventAndUser,
        [
          eventId,
          userId,
        ],
      )) as _i7.Payment?);

  @override
  List<_i7.Payment> getPaymentsForUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getPaymentsForUser,
          [userId],
        ),
        returnValue: <_i7.Payment>[],
      ) as List<_i7.Payment>);

  @override
  List<_i7.Payment> getPaymentsForUserInYear(
    String? userId,
    int? year,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaymentsForUserInYear,
          [
            userId,
            year,
          ],
        ),
        returnValue: <_i7.Payment>[],
      ) as List<_i7.Payment>);

  @override
  _i9.Future<bool> hasPartnership(String? eventId) => (super.noSuchMethod(
        Invocation.method(
          #hasPartnership,
          [eventId],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<_i6.RevenueSplit> calculatePartnershipRevenueSplit({
    required String? eventId,
    required double? totalAmount,
    required int? ticketsSold,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculatePartnershipRevenueSplit,
          [],
          {
            #eventId: eventId,
            #totalAmount: totalAmount,
            #ticketsSold: ticketsSold,
          },
        ),
        returnValue: _i9.Future<_i6.RevenueSplit>.value(_FakeRevenueSplit_4(
          this,
          Invocation.method(
            #calculatePartnershipRevenueSplit,
            [],
            {
              #eventId: eventId,
              #totalAmount: totalAmount,
              #ticketsSold: ticketsSold,
            },
          ),
        )),
      ) as _i9.Future<_i6.RevenueSplit>);

  @override
  _i9.Future<Map<String, double>> distributePartnershipPayment({
    required String? paymentId,
    required String? partnershipId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #distributePartnershipPayment,
          [],
          {
            #paymentId: paymentId,
            #partnershipId: partnershipId,
          },
        ),
        returnValue: _i9.Future<Map<String, double>>.value(<String, double>{}),
      ) as _i9.Future<Map<String, double>>);
}
