// Mocks generated by Mockito 5.4.6 from annotations
// in spots/test/unit/controllers/onboarding_flow_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:spots/core/models/onboarding_data.dart' as _i5;
import 'package:spots/core/models/user_agreement.dart' as _i2;
import 'package:spots/core/services/agent_id_service.dart' as _i6;
import 'package:spots/core/services/legal_document_service.dart' as _i8;
import 'package:spots/core/services/onboarding_data_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserAgreement_0 extends _i1.SmartFake implements _i2.UserAgreement {
  _FakeUserAgreement_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OnboardingDataService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnboardingDataService extends _i1.Mock
    implements _i3.OnboardingDataService {
  MockOnboardingDataService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveOnboardingData(
    String? userId,
    _i5.OnboardingData? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveOnboardingData,
          [
            userId,
            data,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.OnboardingData?> getOnboardingData(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOnboardingData,
          [userId],
        ),
        returnValue: _i4.Future<_i5.OnboardingData?>.value(),
      ) as _i4.Future<_i5.OnboardingData?>);

  @override
  _i4.Future<void> deleteOnboardingData(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #deleteOnboardingData,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> hasOnboardingData(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #hasOnboardingData,
          [userId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [AgentIdService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAgentIdService extends _i1.Mock implements _i6.AgentIdService {
  MockAgentIdService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> getUserAgentId(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getUserAgentId,
          [userId],
        ),
        returnValue: _i4.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #getUserAgentId,
            [userId],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> rotateMappingEncryptionKey(
    String? userId, {
    _i6.EncryptedMapping? existingEncryptedMapping,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rotateMappingEncryptionKey,
          [userId],
          {#existingEncryptedMapping: existingEncryptedMapping},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> flushAuditLogs() => (super.noSuchMethod(
        Invocation.method(
          #flushAuditLogs,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> getBusinessAgentId(String? businessId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBusinessAgentId,
          [businessId],
        ),
        returnValue: _i4.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #getBusinessAgentId,
            [businessId],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> getExpertAgentId(String? expertId) => (super.noSuchMethod(
        Invocation.method(
          #getExpertAgentId,
          [expertId],
        ),
        returnValue: _i4.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #getExpertAgentId,
            [expertId],
          ),
        )),
      ) as _i4.Future<String>);
}

/// A class which mocks [LegalDocumentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLegalDocumentService extends _i1.Mock
    implements _i8.LegalDocumentService {
  MockLegalDocumentService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> hasAcceptedTerms(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #hasAcceptedTerms,
          [userId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> hasAcceptedPrivacyPolicy(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasAcceptedPrivacyPolicy,
          [userId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> hasAcceptedEventWaiver(
    String? userId,
    String? eventId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasAcceptedEventWaiver,
          [
            userId,
            eventId,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i2.UserAgreement> acceptTermsOfService({
    required String? userId,
    String? ipAddress,
    String? userAgent,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptTermsOfService,
          [],
          {
            #userId: userId,
            #ipAddress: ipAddress,
            #userAgent: userAgent,
          },
        ),
        returnValue: _i4.Future<_i2.UserAgreement>.value(_FakeUserAgreement_0(
          this,
          Invocation.method(
            #acceptTermsOfService,
            [],
            {
              #userId: userId,
              #ipAddress: ipAddress,
              #userAgent: userAgent,
            },
          ),
        )),
      ) as _i4.Future<_i2.UserAgreement>);

  @override
  _i4.Future<_i2.UserAgreement> acceptPrivacyPolicy({
    required String? userId,
    String? ipAddress,
    String? userAgent,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptPrivacyPolicy,
          [],
          {
            #userId: userId,
            #ipAddress: ipAddress,
            #userAgent: userAgent,
          },
        ),
        returnValue: _i4.Future<_i2.UserAgreement>.value(_FakeUserAgreement_0(
          this,
          Invocation.method(
            #acceptPrivacyPolicy,
            [],
            {
              #userId: userId,
              #ipAddress: ipAddress,
              #userAgent: userAgent,
            },
          ),
        )),
      ) as _i4.Future<_i2.UserAgreement>);

  @override
  _i4.Future<_i2.UserAgreement> acceptEventWaiver({
    required String? userId,
    required String? eventId,
    String? ipAddress,
    String? userAgent,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptEventWaiver,
          [],
          {
            #userId: userId,
            #eventId: eventId,
            #ipAddress: ipAddress,
            #userAgent: userAgent,
          },
        ),
        returnValue: _i4.Future<_i2.UserAgreement>.value(_FakeUserAgreement_0(
          this,
          Invocation.method(
            #acceptEventWaiver,
            [],
            {
              #userId: userId,
              #eventId: eventId,
              #ipAddress: ipAddress,
              #userAgent: userAgent,
            },
          ),
        )),
      ) as _i4.Future<_i2.UserAgreement>);

  @override
  _i4.Future<String> generateEventWaiver(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateEventWaiver,
          [eventId],
        ),
        returnValue: _i4.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #generateEventWaiver,
            [eventId],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<bool> needsTermsUpdate(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #needsTermsUpdate,
          [userId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> needsPrivacyUpdate(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #needsPrivacyUpdate,
          [userId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<_i2.UserAgreement>> getUserAgreements(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserAgreements,
          [userId],
        ),
        returnValue:
            _i4.Future<List<_i2.UserAgreement>>.value(<_i2.UserAgreement>[]),
      ) as _i4.Future<List<_i2.UserAgreement>>);

  @override
  _i4.Future<_i2.UserAgreement?> getAgreement(String? agreementId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAgreement,
          [agreementId],
        ),
        returnValue: _i4.Future<_i2.UserAgreement?>.value(),
      ) as _i4.Future<_i2.UserAgreement?>);

  @override
  _i4.Future<_i2.UserAgreement> revokeAgreement({
    required String userId,
    required String agreementId,
    String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #revokeAgreement,
          [],
          {
            #userId: userId,
            #agreementId: agreementId,
            #reason: reason,
          },
        ),
        returnValue: _i4.Future<_i2.UserAgreement>.value(_FakeUserAgreement_0(
          this,
          Invocation.method(
            #revokeAgreement,
            [],
            {
              #userId: userId,
              #agreementId: agreementId,
              #reason: reason,
            },
          ),
        )),
      ) as _i4.Future<_i2.UserAgreement>);
}
