// Mocks generated by Mockito 5.4.6 from annotations
// in spots/test/unit/controllers/partnership_proposal_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:spots/core/models/business_account.dart' as _i3;
import 'package:spots/core/models/business_verification.dart' as _i4;
import 'package:spots/core/models/event_partnership.dart' as _i2;
import 'package:spots/core/services/business_service.dart' as _i7;
import 'package:spots/core/services/partnership_service.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEventPartnership_0 extends _i1.SmartFake
    implements _i2.EventPartnership {
  _FakeEventPartnership_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBusinessAccount_1 extends _i1.SmartFake
    implements _i3.BusinessAccount {
  _FakeBusinessAccount_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBusinessVerification_2 extends _i1.SmartFake
    implements _i4.BusinessVerification {
  _FakeBusinessVerification_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PartnershipService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPartnershipService extends _i1.Mock
    implements _i5.PartnershipService {
  MockPartnershipService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.EventPartnership> createPartnership({
    required String? eventId,
    required String? userId,
    required String? businessId,
    _i2.PartnershipAgreement? agreement,
    _i2.PartnershipType? type = _i2.PartnershipType.eventBased,
    List<String>? sharedResponsibilities,
    String? venueLocation,
    double? vibeCompatibilityScore,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPartnership,
          [],
          {
            #eventId: eventId,
            #userId: userId,
            #businessId: businessId,
            #agreement: agreement,
            #type: type,
            #sharedResponsibilities: sharedResponsibilities,
            #venueLocation: venueLocation,
            #vibeCompatibilityScore: vibeCompatibilityScore,
          },
        ),
        returnValue:
            _i6.Future<_i2.EventPartnership>.value(_FakeEventPartnership_0(
          this,
          Invocation.method(
            #createPartnership,
            [],
            {
              #eventId: eventId,
              #userId: userId,
              #businessId: businessId,
              #agreement: agreement,
              #type: type,
              #sharedResponsibilities: sharedResponsibilities,
              #venueLocation: venueLocation,
              #vibeCompatibilityScore: vibeCompatibilityScore,
            },
          ),
        )),
      ) as _i6.Future<_i2.EventPartnership>);

  @override
  _i6.Future<List<_i2.EventPartnership>> getPartnershipsForEvent(
          String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPartnershipsForEvent,
          [eventId],
        ),
        returnValue: _i6.Future<List<_i2.EventPartnership>>.value(
            <_i2.EventPartnership>[]),
      ) as _i6.Future<List<_i2.EventPartnership>>);

  @override
  _i6.Future<_i2.EventPartnership?> getPartnershipById(String? partnershipId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPartnershipById,
          [partnershipId],
        ),
        returnValue: _i6.Future<_i2.EventPartnership?>.value(),
      ) as _i6.Future<_i2.EventPartnership?>);

  @override
  _i6.Future<_i2.EventPartnership> updatePartnershipStatus({
    required String? partnershipId,
    required _i2.PartnershipStatus? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePartnershipStatus,
          [],
          {
            #partnershipId: partnershipId,
            #status: status,
          },
        ),
        returnValue:
            _i6.Future<_i2.EventPartnership>.value(_FakeEventPartnership_0(
          this,
          Invocation.method(
            #updatePartnershipStatus,
            [],
            {
              #partnershipId: partnershipId,
              #status: status,
            },
          ),
        )),
      ) as _i6.Future<_i2.EventPartnership>);

  @override
  _i6.Future<_i2.EventPartnership> approvePartnership({
    required String? partnershipId,
    required String? approvedBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #approvePartnership,
          [],
          {
            #partnershipId: partnershipId,
            #approvedBy: approvedBy,
          },
        ),
        returnValue:
            _i6.Future<_i2.EventPartnership>.value(_FakeEventPartnership_0(
          this,
          Invocation.method(
            #approvePartnership,
            [],
            {
              #partnershipId: partnershipId,
              #approvedBy: approvedBy,
            },
          ),
        )),
      ) as _i6.Future<_i2.EventPartnership>);

  @override
  _i6.Future<bool> checkPartnershipEligibility({
    required String? userId,
    required String? businessId,
    required String? eventId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkPartnershipEligibility,
          [],
          {
            #userId: userId,
            #businessId: businessId,
            #eventId: eventId,
          },
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<double> calculateVibeCompatibility({
    required String? userId,
    required String? businessId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateVibeCompatibility,
          [],
          {
            #userId: userId,
            #businessId: businessId,
          },
        ),
        returnValue: _i6.Future<double>.value(0.0),
      ) as _i6.Future<double>);
}

/// A class which mocks [BusinessService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBusinessService extends _i1.Mock implements _i7.BusinessService {
  MockBusinessService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.BusinessAccount> createBusinessAccount({
    required String? name,
    required String? email,
    required String? businessType,
    required String? createdBy,
    String? description,
    String? website,
    String? location,
    String? phone,
    List<String>? categories,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBusinessAccount,
          [],
          {
            #name: name,
            #email: email,
            #businessType: businessType,
            #createdBy: createdBy,
            #description: description,
            #website: website,
            #location: location,
            #phone: phone,
            #categories: categories,
          },
        ),
        returnValue:
            _i6.Future<_i3.BusinessAccount>.value(_FakeBusinessAccount_1(
          this,
          Invocation.method(
            #createBusinessAccount,
            [],
            {
              #name: name,
              #email: email,
              #businessType: businessType,
              #createdBy: createdBy,
              #description: description,
              #website: website,
              #location: location,
              #phone: phone,
              #categories: categories,
            },
          ),
        )),
      ) as _i6.Future<_i3.BusinessAccount>);

  @override
  _i6.Future<_i4.BusinessVerification> verifyBusiness({
    required String? businessId,
    String? businessLicenseUrl,
    String? taxIdDocumentUrl,
    String? proofOfAddressUrl,
    String? websiteVerificationUrl,
    String? socialMediaVerificationUrl,
    String? legalBusinessName,
    String? taxId,
    String? businessAddress,
    String? phoneNumber,
    String? websiteUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyBusiness,
          [],
          {
            #businessId: businessId,
            #businessLicenseUrl: businessLicenseUrl,
            #taxIdDocumentUrl: taxIdDocumentUrl,
            #proofOfAddressUrl: proofOfAddressUrl,
            #websiteVerificationUrl: websiteVerificationUrl,
            #socialMediaVerificationUrl: socialMediaVerificationUrl,
            #legalBusinessName: legalBusinessName,
            #taxId: taxId,
            #businessAddress: businessAddress,
            #phoneNumber: phoneNumber,
            #websiteUrl: websiteUrl,
          },
        ),
        returnValue: _i6.Future<_i4.BusinessVerification>.value(
            _FakeBusinessVerification_2(
          this,
          Invocation.method(
            #verifyBusiness,
            [],
            {
              #businessId: businessId,
              #businessLicenseUrl: businessLicenseUrl,
              #taxIdDocumentUrl: taxIdDocumentUrl,
              #proofOfAddressUrl: proofOfAddressUrl,
              #websiteVerificationUrl: websiteVerificationUrl,
              #socialMediaVerificationUrl: socialMediaVerificationUrl,
              #legalBusinessName: legalBusinessName,
              #taxId: taxId,
              #businessAddress: businessAddress,
              #phoneNumber: phoneNumber,
              #websiteUrl: websiteUrl,
            },
          ),
        )),
      ) as _i6.Future<_i4.BusinessVerification>);

  @override
  _i6.Future<_i3.BusinessAccount> updateBusinessInfo({
    required String? businessId,
    String? name,
    String? description,
    String? website,
    String? location,
    String? phone,
    List<String>? categories,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBusinessInfo,
          [],
          {
            #businessId: businessId,
            #name: name,
            #description: description,
            #website: website,
            #location: location,
            #phone: phone,
            #categories: categories,
          },
        ),
        returnValue:
            _i6.Future<_i3.BusinessAccount>.value(_FakeBusinessAccount_1(
          this,
          Invocation.method(
            #updateBusinessInfo,
            [],
            {
              #businessId: businessId,
              #name: name,
              #description: description,
              #website: website,
              #location: location,
              #phone: phone,
              #categories: categories,
            },
          ),
        )),
      ) as _i6.Future<_i3.BusinessAccount>);

  @override
  _i6.Future<List<_i3.BusinessAccount>> findBusinesses({
    String? category,
    String? location,
    bool? verifiedOnly = false,
    int? maxResults = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findBusinesses,
          [],
          {
            #category: category,
            #location: location,
            #verifiedOnly: verifiedOnly,
            #maxResults: maxResults,
          },
        ),
        returnValue: _i6.Future<List<_i3.BusinessAccount>>.value(
            <_i3.BusinessAccount>[]),
      ) as _i6.Future<List<_i3.BusinessAccount>>);

  @override
  _i6.Future<bool> checkBusinessEligibility(String? businessId) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkBusinessEligibility,
          [businessId],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i3.BusinessAccount?> getBusinessById(String? businessId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBusinessById,
          [businessId],
        ),
        returnValue: _i6.Future<_i3.BusinessAccount?>.value(),
      ) as _i6.Future<_i3.BusinessAccount?>);

  @override
  _i6.Future<_i4.BusinessVerification?> getVerification(String? businessId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVerification,
          [businessId],
        ),
        returnValue: _i6.Future<_i4.BusinessVerification?>.value(),
      ) as _i6.Future<_i4.BusinessVerification?>);
}
