// Mocks generated by Mockito 5.4.6 from annotations
// in avrai/test/unit/controllers/payment_processing_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:avrai/core/models/expertise_event.dart' as _i5;
import 'package:avrai/core/models/unified_user.dart' as _i7;
import 'package:avrai/core/services/payment_event_service.dart' as _i3;
import 'package:avrai/core/services/sales_tax_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSalesTaxCalculation_0 extends _i1.SmartFake
    implements _i2.SalesTaxCalculation {
  _FakeSalesTaxCalculation_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaymentEventResult_1 extends _i1.SmartFake
    implements _i3.PaymentEventResult {
  _FakePaymentEventResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRefundResult_2 extends _i1.SmartFake implements _i3.RefundResult {
  _FakeRefundResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SalesTaxService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSalesTaxService extends _i1.Mock implements _i2.SalesTaxService {
  MockSalesTaxService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.SalesTaxCalculation> calculateSalesTax({
    required String? eventId,
    required double? ticketPrice,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateSalesTax,
          [],
          {
            #eventId: eventId,
            #ticketPrice: ticketPrice,
          },
        ),
        returnValue: _i4.Future<_i2.SalesTaxCalculation>.value(
            _FakeSalesTaxCalculation_0(
          this,
          Invocation.method(
            #calculateSalesTax,
            [],
            {
              #eventId: eventId,
              #ticketPrice: ticketPrice,
            },
          ),
        )),
      ) as _i4.Future<_i2.SalesTaxCalculation>);

  @override
  _i4.Future<_i2.SalesTaxCalculation> calculateSalesTaxFromDetails({
    required double? ticketPrice,
    required _i5.ExpertiseEventType? eventType,
    required String? location,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateSalesTaxFromDetails,
          [],
          {
            #ticketPrice: ticketPrice,
            #eventType: eventType,
            #location: location,
          },
        ),
        returnValue: _i4.Future<_i2.SalesTaxCalculation>.value(
            _FakeSalesTaxCalculation_0(
          this,
          Invocation.method(
            #calculateSalesTaxFromDetails,
            [],
            {
              #ticketPrice: ticketPrice,
              #eventType: eventType,
              #location: location,
            },
          ),
        )),
      ) as _i4.Future<_i2.SalesTaxCalculation>);

  @override
  _i4.Future<double> getTaxRateForLocation({
    String? state,
    String? city,
    String? zipCode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTaxRateForLocation,
          [],
          {
            #state: state,
            #city: city,
            #zipCode: zipCode,
          },
        ),
        returnValue: _i4.Future<double>.value(0.0),
      ) as _i4.Future<double>);

  @override
  _i4.Future<String> fileSalesTaxReturn({
    required String? state,
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fileSalesTaxReturn,
          [],
          {
            #state: state,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #fileSalesTaxReturn,
            [],
            {
              #state: state,
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i4.Future<String>);

  @override
  bool isEventTypeTaxable(_i5.ExpertiseEventType? eventType) =>
      (super.noSuchMethod(
        Invocation.method(
          #isEventTypeTaxable,
          [eventType],
        ),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [PaymentEventService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentEventService extends _i1.Mock
    implements _i3.PaymentEventService {
  MockPaymentEventService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i3.PaymentEventResult> processEventPayment({
    required _i5.ExpertiseEvent? event,
    required _i7.UnifiedUser? user,
    int? quantity = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #processEventPayment,
          [],
          {
            #event: event,
            #user: user,
            #quantity: quantity,
          },
        ),
        returnValue:
            _i4.Future<_i3.PaymentEventResult>.value(_FakePaymentEventResult_1(
          this,
          Invocation.method(
            #processEventPayment,
            [],
            {
              #event: event,
              #user: user,
              #quantity: quantity,
            },
          ),
        )),
      ) as _i4.Future<_i3.PaymentEventResult>);

  @override
  _i4.Future<_i3.RefundResult> refundEventPayment({
    required String? paymentId,
    required String? eventId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #refundEventPayment,
          [],
          {
            #paymentId: paymentId,
            #eventId: eventId,
            #userId: userId,
          },
        ),
        returnValue: _i4.Future<_i3.RefundResult>.value(_FakeRefundResult_2(
          this,
          Invocation.method(
            #refundEventPayment,
            [],
            {
              #paymentId: paymentId,
              #eventId: eventId,
              #userId: userId,
            },
          ),
        )),
      ) as _i4.Future<_i3.RefundResult>);
}
