// Mocks generated by Mockito 5.4.6 from annotations
// in avrai/test/unit/controllers/quantum_matching_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;

import 'package:avrai/core/ai/personality_learning.dart' as _i6;
import 'package:avrai/core/ai/vibe_analysis_engine.dart' as _i8;
import 'package:avrai/core/models/multi_path_expertise.dart' as _i15;
import 'package:avrai/core/models/onboarding_data.dart' as _i21;
import 'package:avrai/core/models/outcome_result.dart' as _i16;
import 'package:avrai/core/models/preferences_profile.dart' as _i9;
import 'package:avrai/core/models/unified_user.dart' as _i17;
import 'package:avrai/core/models/user_vibe.dart' as _i7;
import 'package:avrai/core/services/agent_id_service.dart' as _i18;
import 'package:avrai/core/services/preferences_profile_service.dart' as _i20;
import 'package:avrai_core/models/atomic_timestamp.dart' as _i2;
import 'package:avrai_core/models/personality_knot.dart' as _i23;
import 'package:avrai_core/models/personality_profile.dart' as _i5;
import 'package:avrai_core/models/quantum_entity_state.dart' as _i4;
import 'package:avrai_core/models/unified_location_data.dart' as _i14;
import 'package:avrai_core/services/atomic_clock_service.dart' as _i11;
import 'package:avrai_knot/models/entity_knot.dart' as _i25;
import 'package:avrai_knot/models/knot/compatibility_score.dart' as _i10;
import 'package:avrai_knot/services/knot/cross_entity_compatibility_service.dart'
    as _i24;
import 'package:avrai_knot/services/knot/integrated_knot_recommendation_engine.dart'
    as _i22;
import 'package:avrai_quantum/services/quantum/location_timing_quantum_state_service.dart'
    as _i13;
import 'package:avrai_quantum/services/quantum/quantum_entanglement_service.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i19;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAtomicTimestamp_0 extends _i1.SmartFake
    implements _i2.AtomicTimestamp {
  _FakeAtomicTimestamp_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_1 extends _i1.SmartFake implements Duration {
  _FakeDuration_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEntangledQuantumState_2 extends _i1.SmartFake
    implements _i3.EntangledQuantumState {
  _FakeEntangledQuantumState_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEntityLocationQuantumState_3 extends _i1.SmartFake
    implements _i4.EntityLocationQuantumState {
  _FakeEntityLocationQuantumState_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEntityTimingQuantumState_4 extends _i1.SmartFake
    implements _i4.EntityTimingQuantumState {
  _FakeEntityTimingQuantumState_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePersonalityProfile_5 extends _i1.SmartFake
    implements _i5.PersonalityProfile {
  _FakePersonalityProfile_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePersonalityReadiness_6 extends _i1.SmartFake
    implements _i6.PersonalityReadiness {
  _FakePersonalityReadiness_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAnonymizedPersonalityData_7 extends _i1.SmartFake
    implements _i6.AnonymizedPersonalityData {
  _FakeAnonymizedPersonalityData_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserVibe_8 extends _i1.SmartFake implements _i7.UserVibe {
  _FakeUserVibe_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVibeCompatibilityResult_9 extends _i1.SmartFake
    implements _i8.VibeCompatibilityResult {
  _FakeVibeCompatibilityResult_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCommunityVibeInsights_10 extends _i1.SmartFake
    implements _i8.CommunityVibeInsights {
  _FakeCommunityVibeInsights_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVibeAuthenticityResult_11 extends _i1.SmartFake
    implements _i8.VibeAuthenticityResult {
  _FakeVibeAuthenticityResult_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePreferencesProfile_12 extends _i1.SmartFake
    implements _i9.PreferencesProfile {
  _FakePreferencesProfile_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCompatibilityScore_13 extends _i1.SmartFake
    implements _i10.CompatibilityScore {
  _FakeCompatibilityScore_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AtomicClockService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAtomicClockService extends _i1.Mock
    implements _i11.AtomicClockService {
  MockAtomicClockService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void configure({_i12.Future<DateTime> Function()? serverTimeProvider}) =>
      super.noSuchMethod(
        Invocation.method(
          #configure,
          [],
          {#serverTimeProvider: serverTimeProvider},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> syncWithServer() => (super.noSuchMethod(
        Invocation.method(
          #syncWithServer,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<_i2.AtomicTimestamp> getAtomicTimestamp() => (super.noSuchMethod(
        Invocation.method(
          #getAtomicTimestamp,
          [],
        ),
        returnValue:
            _i12.Future<_i2.AtomicTimestamp>.value(_FakeAtomicTimestamp_0(
          this,
          Invocation.method(
            #getAtomicTimestamp,
            [],
          ),
        )),
      ) as _i12.Future<_i2.AtomicTimestamp>);

  @override
  Duration getTimeOffset() => (super.noSuchMethod(
        Invocation.method(
          #getTimeOffset,
          [],
        ),
        returnValue: _FakeDuration_1(
          this,
          Invocation.method(
            #getTimeOffset,
            [],
          ),
        ),
      ) as Duration);

  @override
  bool isSynchronized() => (super.noSuchMethod(
        Invocation.method(
          #isSynchronized,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i2.TimePrecision getPrecision() => (super.noSuchMethod(
        Invocation.method(
          #getPrecision,
          [],
        ),
        returnValue: _i2.TimePrecision.nanosecond,
      ) as _i2.TimePrecision);

  @override
  _i12.Future<_i2.AtomicTimestamp> getTicketPurchaseTimestamp() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTicketPurchaseTimestamp,
          [],
        ),
        returnValue:
            _i12.Future<_i2.AtomicTimestamp>.value(_FakeAtomicTimestamp_0(
          this,
          Invocation.method(
            #getTicketPurchaseTimestamp,
            [],
          ),
        )),
      ) as _i12.Future<_i2.AtomicTimestamp>);

  @override
  _i12.Future<_i2.AtomicTimestamp> getAI2AIConnectionTimestamp() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAI2AIConnectionTimestamp,
          [],
        ),
        returnValue:
            _i12.Future<_i2.AtomicTimestamp>.value(_FakeAtomicTimestamp_0(
          this,
          Invocation.method(
            #getAI2AIConnectionTimestamp,
            [],
          ),
        )),
      ) as _i12.Future<_i2.AtomicTimestamp>);

  @override
  _i12.Future<_i2.AtomicTimestamp> getLiveTrackingTimestamp() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLiveTrackingTimestamp,
          [],
        ),
        returnValue:
            _i12.Future<_i2.AtomicTimestamp>.value(_FakeAtomicTimestamp_0(
          this,
          Invocation.method(
            #getLiveTrackingTimestamp,
            [],
          ),
        )),
      ) as _i12.Future<_i2.AtomicTimestamp>);

  @override
  _i12.Future<_i2.AtomicTimestamp> getAdminOperationTimestamp() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAdminOperationTimestamp,
          [],
        ),
        returnValue:
            _i12.Future<_i2.AtomicTimestamp>.value(_FakeAtomicTimestamp_0(
          this,
          Invocation.method(
            #getAdminOperationTimestamp,
            [],
          ),
        )),
      ) as _i12.Future<_i2.AtomicTimestamp>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [QuantumEntanglementService].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuantumEntanglementService extends _i1.Mock
    implements _i3.QuantumEntanglementService {
  MockQuantumEntanglementService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i3.EntangledQuantumState> createEntangledState({
    required List<_i4.QuantumEntityState>? entityStates,
    List<double>? coefficients,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEntangledState,
          [],
          {
            #entityStates: entityStates,
            #coefficients: coefficients,
          },
        ),
        returnValue: _i12.Future<_i3.EntangledQuantumState>.value(
            _FakeEntangledQuantumState_2(
          this,
          Invocation.method(
            #createEntangledState,
            [],
            {
              #entityStates: entityStates,
              #coefficients: coefficients,
            },
          ),
        )),
      ) as _i12.Future<_i3.EntangledQuantumState>);

  @override
  _i12.Future<double> calculateFidelity(
    _i3.EntangledQuantumState? state1,
    _i3.EntangledQuantumState? state2,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateFidelity,
          [
            state1,
            state2,
          ],
        ),
        returnValue: _i12.Future<double>.value(0.0),
      ) as _i12.Future<double>);

  @override
  _i12.Future<double> calculateKnotCompatibilityBonus(
    List<_i4.QuantumEntityState>? entityStates, {
    DateTime? targetTime,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateKnotCompatibilityBonus,
          [entityStates],
          {#targetTime: targetTime},
        ),
        returnValue: _i12.Future<double>.value(0.0),
      ) as _i12.Future<double>);

  @override
  _i12.Future<bool> shareEntanglementInsightsViaMesh({
    required _i3.EntangledQuantumState? entangledState,
    double? fidelity,
    double? knotCompatibility,
    required String? sourceAgentId,
    required List<String>? entityTypes,
    required dynamic messageType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #shareEntanglementInsightsViaMesh,
          [],
          {
            #entangledState: entangledState,
            #fidelity: fidelity,
            #knotCompatibility: knotCompatibility,
            #sourceAgentId: sourceAgentId,
            #entityTypes: entityTypes,
            #messageType: messageType,
          },
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);
}

/// A class which mocks [LocationTimingQuantumStateService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationTimingQuantumStateService extends _i1.Mock
    implements _i13.LocationTimingQuantumStateService {
  MockLocationTimingQuantumStateService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i4.EntityLocationQuantumState> createLocationQuantumState({
    required _i14.UnifiedLocationData? location,
    double? locationType,
    double? accessibilityScore,
    double? vibeLocationMatch,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLocationQuantumState,
          [],
          {
            #location: location,
            #locationType: locationType,
            #accessibilityScore: accessibilityScore,
            #vibeLocationMatch: vibeLocationMatch,
          },
        ),
        returnValue: _i12.Future<_i4.EntityLocationQuantumState>.value(
            _FakeEntityLocationQuantumState_3(
          this,
          Invocation.method(
            #createLocationQuantumState,
            [],
            {
              #location: location,
              #locationType: locationType,
              #accessibilityScore: accessibilityScore,
              #vibeLocationMatch: vibeLocationMatch,
            },
          ),
        )),
      ) as _i12.Future<_i4.EntityLocationQuantumState>);

  @override
  _i12.Future<_i4.EntityTimingQuantumState> createTimingQuantumState({
    required double? timeOfDayPreference,
    required double? dayOfWeekPreference,
    required double? frequencyPreference,
    required double? durationPreference,
    double? timingVibeMatch,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTimingQuantumState,
          [],
          {
            #timeOfDayPreference: timeOfDayPreference,
            #dayOfWeekPreference: dayOfWeekPreference,
            #frequencyPreference: frequencyPreference,
            #durationPreference: durationPreference,
            #timingVibeMatch: timingVibeMatch,
          },
        ),
        returnValue: _i12.Future<_i4.EntityTimingQuantumState>.value(
            _FakeEntityTimingQuantumState_4(
          this,
          Invocation.method(
            #createTimingQuantumState,
            [],
            {
              #timeOfDayPreference: timeOfDayPreference,
              #dayOfWeekPreference: dayOfWeekPreference,
              #frequencyPreference: frequencyPreference,
              #durationPreference: durationPreference,
              #timingVibeMatch: timingVibeMatch,
            },
          ),
        )),
      ) as _i12.Future<_i4.EntityTimingQuantumState>);

  @override
  _i12.Future<_i4.EntityTimingQuantumState>
      createTimingQuantumStateFromIntuitive({
    required int? timeOfDayHour,
    required int? dayOfWeek,
    required double? frequencyPreference,
    required double? durationPreference,
    double? timingVibeMatch,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #createTimingQuantumStateFromIntuitive,
              [],
              {
                #timeOfDayHour: timeOfDayHour,
                #dayOfWeek: dayOfWeek,
                #frequencyPreference: frequencyPreference,
                #durationPreference: durationPreference,
                #timingVibeMatch: timingVibeMatch,
              },
            ),
            returnValue: _i12.Future<_i4.EntityTimingQuantumState>.value(
                _FakeEntityTimingQuantumState_4(
              this,
              Invocation.method(
                #createTimingQuantumStateFromIntuitive,
                [],
                {
                  #timeOfDayHour: timeOfDayHour,
                  #dayOfWeek: dayOfWeek,
                  #frequencyPreference: frequencyPreference,
                  #durationPreference: durationPreference,
                  #timingVibeMatch: timingVibeMatch,
                },
              ),
            )),
          ) as _i12.Future<_i4.EntityTimingQuantumState>);

  @override
  _i12.Future<_i4.EntityTimingQuantumState>
      createTimingQuantumStateWithPreferredDays({
    required int? timeOfDayHour,
    required List<int>? preferredDays,
    required double? frequencyPreference,
    required double? durationPreference,
    double? timingVibeMatch,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #createTimingQuantumStateWithPreferredDays,
              [],
              {
                #timeOfDayHour: timeOfDayHour,
                #preferredDays: preferredDays,
                #frequencyPreference: frequencyPreference,
                #durationPreference: durationPreference,
                #timingVibeMatch: timingVibeMatch,
              },
            ),
            returnValue: _i12.Future<_i4.EntityTimingQuantumState>.value(
                _FakeEntityTimingQuantumState_4(
              this,
              Invocation.method(
                #createTimingQuantumStateWithPreferredDays,
                [],
                {
                  #timeOfDayHour: timeOfDayHour,
                  #preferredDays: preferredDays,
                  #frequencyPreference: frequencyPreference,
                  #durationPreference: durationPreference,
                  #timingVibeMatch: timingVibeMatch,
                },
              ),
            )),
          ) as _i12.Future<_i4.EntityTimingQuantumState>);

  @override
  _i12.Future<_i4.EntityTimingQuantumState>
      createTimingQuantumStateFromDateTime({
    required DateTime? preferredTime,
    required double? frequencyPreference,
    required double? durationPreference,
    double? timingVibeMatch,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #createTimingQuantumStateFromDateTime,
              [],
              {
                #preferredTime: preferredTime,
                #frequencyPreference: frequencyPreference,
                #durationPreference: durationPreference,
                #timingVibeMatch: timingVibeMatch,
              },
            ),
            returnValue: _i12.Future<_i4.EntityTimingQuantumState>.value(
                _FakeEntityTimingQuantumState_4(
              this,
              Invocation.method(
                #createTimingQuantumStateFromDateTime,
                [],
                {
                  #preferredTime: preferredTime,
                  #frequencyPreference: frequencyPreference,
                  #durationPreference: durationPreference,
                  #timingVibeMatch: timingVibeMatch,
                },
              ),
            )),
          ) as _i12.Future<_i4.EntityTimingQuantumState>);
}

/// A class which mocks [PersonalityLearning].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonalityLearning extends _i1.Mock
    implements _i6.PersonalityLearning {
  MockPersonalityLearning() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onPersonalityEvolved(
          dynamic Function(
            String,
            _i5.PersonalityProfile,
          )? _onPersonalityEvolved) =>
      super.noSuchMethod(
        Invocation.setter(
          #onPersonalityEvolved,
          _onPersonalityEvolved,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> migrateProfilesToAgentId() => (super.noSuchMethod(
        Invocation.method(
          #migrateProfilesToAgentId,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void setEvolutionCallback(
          dynamic Function(
            String,
            _i5.PersonalityProfile,
          )? callback) =>
      super.noSuchMethod(
        Invocation.method(
          #setEvolutionCallback,
          [callback],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<_i5.PersonalityProfile> initializePersonality(
    String? userId, {
    String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initializePersonality,
          [userId],
          {#password: password},
        ),
        returnValue:
            _i12.Future<_i5.PersonalityProfile>.value(_FakePersonalityProfile_5(
          this,
          Invocation.method(
            #initializePersonality,
            [userId],
            {#password: password},
          ),
        )),
      ) as _i12.Future<_i5.PersonalityProfile>);

  @override
  _i12.Future<_i5.PersonalityProfile> initializePersonalityFromOnboarding(
    String? userId, {
    Map<String, dynamic>? onboardingData,
    Map<String, dynamic>? socialMediaData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initializePersonalityFromOnboarding,
          [userId],
          {
            #onboardingData: onboardingData,
            #socialMediaData: socialMediaData,
          },
        ),
        returnValue:
            _i12.Future<_i5.PersonalityProfile>.value(_FakePersonalityProfile_5(
          this,
          Invocation.method(
            #initializePersonalityFromOnboarding,
            [userId],
            {
              #onboardingData: onboardingData,
              #socialMediaData: socialMediaData,
            },
          ),
        )),
      ) as _i12.Future<_i5.PersonalityProfile>);

  @override
  _i12.Future<_i5.PersonalityProfile> evolveFromUserAction(
    String? userId,
    _i6.UserAction? action, {
    _i15.LocalExpertise? localExpertise,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #evolveFromUserAction,
          [
            userId,
            action,
          ],
          {#localExpertise: localExpertise},
        ),
        returnValue:
            _i12.Future<_i5.PersonalityProfile>.value(_FakePersonalityProfile_5(
          this,
          Invocation.method(
            #evolveFromUserAction,
            [
              userId,
              action,
            ],
            {#localExpertise: localExpertise},
          ),
        )),
      ) as _i12.Future<_i5.PersonalityProfile>);

  @override
  _i12.Future<_i5.PersonalityProfile> evolveFromAI2AILearning(
    String? userId,
    _i6.AI2AILearningInsight? insight, {
    _i16.OutcomeResult? outcome,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #evolveFromAI2AILearning,
          [
            userId,
            insight,
          ],
          {#outcome: outcome},
        ),
        returnValue:
            _i12.Future<_i5.PersonalityProfile>.value(_FakePersonalityProfile_5(
          this,
          Invocation.method(
            #evolveFromAI2AILearning,
            [
              userId,
              insight,
            ],
            {#outcome: outcome},
          ),
        )),
      ) as _i12.Future<_i5.PersonalityProfile>);

  @override
  _i12.Future<_i5.PersonalityProfile?> getCurrentPersonality(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentPersonality,
          [userId],
        ),
        returnValue: _i12.Future<_i5.PersonalityProfile?>.value(),
      ) as _i12.Future<_i5.PersonalityProfile?>);

  @override
  _i12.Future<List<_i6.PersonalityEvolutionEvent>> getEvolutionHistory(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEvolutionHistory,
          [userId],
        ),
        returnValue: _i12.Future<List<_i6.PersonalityEvolutionEvent>>.value(
            <_i6.PersonalityEvolutionEvent>[]),
      ) as _i12.Future<List<_i6.PersonalityEvolutionEvent>>);

  @override
  _i12.Future<_i6.PersonalityReadiness> calculateAI2AIReadiness(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateAI2AIReadiness,
          [userId],
        ),
        returnValue: _i12.Future<_i6.PersonalityReadiness>.value(
            _FakePersonalityReadiness_6(
          this,
          Invocation.method(
            #calculateAI2AIReadiness,
            [userId],
          ),
        )),
      ) as _i12.Future<_i6.PersonalityReadiness>);

  @override
  _i12.Future<void> resetPersonality(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #resetPersonality,
          [userId],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<double> calculatePersonalityReadiness() => (super.noSuchMethod(
        Invocation.method(
          #calculatePersonalityReadiness,
          [],
        ),
        returnValue: _i12.Future<double>.value(0.0),
      ) as _i12.Future<double>);

  @override
  _i12.Future<Map<String, dynamic>> calculatePersonalityEvolution({
    Map<String, dynamic>? current,
    Map<String, dynamic>? currentProfile,
    List<Map<String, dynamic>>? actions = const [],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculatePersonalityEvolution,
          [],
          {
            #current: current,
            #currentProfile: currentProfile,
            #actions: actions,
          },
        ),
        returnValue:
            _i12.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i12.Future<Map<String, dynamic>>);

  @override
  _i12.Future<_i5.PersonalityProfile> evolvePersonality(
          _i6.UserAction? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #evolvePersonality,
          [action],
        ),
        returnValue:
            _i12.Future<_i5.PersonalityProfile>.value(_FakePersonalityProfile_5(
          this,
          Invocation.method(
            #evolvePersonality,
            [action],
          ),
        )),
      ) as _i12.Future<_i5.PersonalityProfile>);

  @override
  _i12.Future<List<_i6.BehavioralPattern>> recognizeBehavioralPatterns(
          List<_i6.UserAction>? actions) =>
      (super.noSuchMethod(
        Invocation.method(
          #recognizeBehavioralPatterns,
          [actions],
        ),
        returnValue: _i12.Future<List<_i6.BehavioralPattern>>.value(
            <_i6.BehavioralPattern>[]),
      ) as _i12.Future<List<_i6.BehavioralPattern>>);

  @override
  _i12.Future<Map<String, double>> predictFuturePreferences() =>
      (super.noSuchMethod(
        Invocation.method(
          #predictFuturePreferences,
          [],
        ),
        returnValue: _i12.Future<Map<String, double>>.value(<String, double>{}),
      ) as _i12.Future<Map<String, double>>);

  @override
  _i12.Future<void> updatePersonalityProfile(
          Map<String, dynamic>? personalityData) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePersonalityProfile,
          [personalityData],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<double> calculatePersonalityCompatibility(
    Map<String, dynamic>? a,
    Map<String, dynamic>? b,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculatePersonalityCompatibility,
          [
            a,
            b,
          ],
        ),
        returnValue: _i12.Future<double>.value(0.0),
      ) as _i12.Future<double>);

  @override
  _i12.Future<_i6.AnonymizedPersonalityData> anonymizePersonality() =>
      (super.noSuchMethod(
        Invocation.method(
          #anonymizePersonality,
          [],
        ),
        returnValue: _i12.Future<_i6.AnonymizedPersonalityData>.value(
            _FakeAnonymizedPersonalityData_7(
          this,
          Invocation.method(
            #anonymizePersonality,
            [],
          ),
        )),
      ) as _i12.Future<_i6.AnonymizedPersonalityData>);
}

/// A class which mocks [UserVibeAnalyzer].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserVibeAnalyzer extends _i1.Mock implements _i8.UserVibeAnalyzer {
  MockUserVibeAnalyzer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i7.UserVibe> compileUserVibe(
    String? userId,
    _i5.PersonalityProfile? personality,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #compileUserVibe,
          [
            userId,
            personality,
          ],
        ),
        returnValue: _i12.Future<_i7.UserVibe>.value(_FakeUserVibe_8(
          this,
          Invocation.method(
            #compileUserVibe,
            [
              userId,
              personality,
            ],
          ),
        )),
      ) as _i12.Future<_i7.UserVibe>);

  @override
  _i12.Future<_i8.VibeCompatibilityResult> analyzeVibeCompatibility(
    _i7.UserVibe? localVibe,
    _i7.UserVibe? remoteVibe, {
    _i17.UnifiedUser? localUser,
    _i17.UnifiedUser? remoteUser,
    List<String>? recentActions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #analyzeVibeCompatibility,
          [
            localVibe,
            remoteVibe,
          ],
          {
            #localUser: localUser,
            #remoteUser: remoteUser,
            #recentActions: recentActions,
          },
        ),
        returnValue: _i12.Future<_i8.VibeCompatibilityResult>.value(
            _FakeVibeCompatibilityResult_9(
          this,
          Invocation.method(
            #analyzeVibeCompatibility,
            [
              localVibe,
              remoteVibe,
            ],
            {
              #localUser: localUser,
              #remoteUser: remoteUser,
              #recentActions: recentActions,
            },
          ),
        )),
      ) as _i12.Future<_i8.VibeCompatibilityResult>);

  @override
  _i12.Future<_i7.UserVibe> refreshUserVibe(
    String? userId,
    _i5.PersonalityProfile? updatedPersonality,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshUserVibe,
          [
            userId,
            updatedPersonality,
          ],
        ),
        returnValue: _i12.Future<_i7.UserVibe>.value(_FakeUserVibe_8(
          this,
          Invocation.method(
            #refreshUserVibe,
            [
              userId,
              updatedPersonality,
            ],
          ),
        )),
      ) as _i12.Future<_i7.UserVibe>);

  @override
  _i12.Future<List<_i8.VibeEvolutionEvent>> getVibeEvolutionHistory(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVibeEvolutionHistory,
          [userId],
        ),
        returnValue: _i12.Future<List<_i8.VibeEvolutionEvent>>.value(
            <_i8.VibeEvolutionEvent>[]),
      ) as _i12.Future<List<_i8.VibeEvolutionEvent>>);

  @override
  _i12.Future<_i8.CommunityVibeInsights> analyzeCommunityVibePatterns() =>
      (super.noSuchMethod(
        Invocation.method(
          #analyzeCommunityVibePatterns,
          [],
        ),
        returnValue: _i12.Future<_i8.CommunityVibeInsights>.value(
            _FakeCommunityVibeInsights_10(
          this,
          Invocation.method(
            #analyzeCommunityVibePatterns,
            [],
          ),
        )),
      ) as _i12.Future<_i8.CommunityVibeInsights>);

  @override
  _i12.Future<_i8.VibeAuthenticityResult> validateVibeAuthenticity(
    _i7.UserVibe? vibe,
    _i5.PersonalityProfile? personality,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateVibeAuthenticity,
          [
            vibe,
            personality,
          ],
        ),
        returnValue: _i12.Future<_i8.VibeAuthenticityResult>.value(
            _FakeVibeAuthenticityResult_11(
          this,
          Invocation.method(
            #validateVibeAuthenticity,
            [
              vibe,
              personality,
            ],
          ),
        )),
      ) as _i12.Future<_i8.VibeAuthenticityResult>);
}

/// A class which mocks [AgentIdService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAgentIdService extends _i1.Mock implements _i18.AgentIdService {
  MockAgentIdService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<String> getUserAgentId(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getUserAgentId,
          [userId],
        ),
        returnValue: _i12.Future<String>.value(_i19.dummyValue<String>(
          this,
          Invocation.method(
            #getUserAgentId,
            [userId],
          ),
        )),
      ) as _i12.Future<String>);

  @override
  _i12.Future<void> rotateMappingEncryptionKey(
    String? userId, {
    _i18.EncryptedMapping? existingEncryptedMapping,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rotateMappingEncryptionKey,
          [userId],
          {#existingEncryptedMapping: existingEncryptedMapping},
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> flushAuditLogs() => (super.noSuchMethod(
        Invocation.method(
          #flushAuditLogs,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<String> getBusinessAgentId(String? businessId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBusinessAgentId,
          [businessId],
        ),
        returnValue: _i12.Future<String>.value(_i19.dummyValue<String>(
          this,
          Invocation.method(
            #getBusinessAgentId,
            [businessId],
          ),
        )),
      ) as _i12.Future<String>);

  @override
  _i12.Future<String> getExpertAgentId(String? expertId) => (super.noSuchMethod(
        Invocation.method(
          #getExpertAgentId,
          [expertId],
        ),
        returnValue: _i12.Future<String>.value(_i19.dummyValue<String>(
          this,
          Invocation.method(
            #getExpertAgentId,
            [expertId],
          ),
        )),
      ) as _i12.Future<String>);
}

/// A class which mocks [PreferencesProfileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreferencesProfileService extends _i1.Mock
    implements _i20.PreferencesProfileService {
  MockPreferencesProfileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i9.PreferencesProfile> initializeFromOnboarding(
          _i21.OnboardingData? onboardingData) =>
      (super.noSuchMethod(
        Invocation.method(
          #initializeFromOnboarding,
          [onboardingData],
        ),
        returnValue: _i12.Future<_i9.PreferencesProfile>.value(
            _FakePreferencesProfile_12(
          this,
          Invocation.method(
            #initializeFromOnboarding,
            [onboardingData],
          ),
        )),
      ) as _i12.Future<_i9.PreferencesProfile>);

  @override
  _i12.Future<_i9.PreferencesProfile?> getPreferencesProfile(String? agentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPreferencesProfile,
          [agentId],
        ),
        returnValue: _i12.Future<_i9.PreferencesProfile?>.value(),
      ) as _i12.Future<_i9.PreferencesProfile?>);

  @override
  _i12.Future<void> savePreferencesProfile(_i9.PreferencesProfile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePreferencesProfile,
          [profile],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> updatePreferencesProfile(_i9.PreferencesProfile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePreferencesProfile,
          [profile],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);
}

/// A class which mocks [IntegratedKnotRecommendationEngine].
///
/// See the documentation for Mockito's code generation for more information.
class MockIntegratedKnotRecommendationEngine extends _i1.Mock
    implements _i22.IntegratedKnotRecommendationEngine {
  MockIntegratedKnotRecommendationEngine() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i10.CompatibilityScore> calculateIntegratedCompatibility({
    required _i5.PersonalityProfile? profileA,
    required _i5.PersonalityProfile? profileB,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateIntegratedCompatibility,
          [],
          {
            #profileA: profileA,
            #profileB: profileB,
          },
        ),
        returnValue: _i12.Future<_i10.CompatibilityScore>.value(
            _FakeCompatibilityScore_13(
          this,
          Invocation.method(
            #calculateIntegratedCompatibility,
            [],
            {
              #profileA: profileA,
              #profileB: profileB,
            },
          ),
        )),
      ) as _i12.Future<_i10.CompatibilityScore>);

  @override
  double calculateKnotBonus({
    required _i23.PersonalityKnot? userKnot,
    required _i23.PersonalityKnot? targetKnot,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateKnotBonus,
          [],
          {
            #userKnot: userKnot,
            #targetKnot: targetKnot,
          },
        ),
        returnValue: 0.0,
      ) as double);

  @override
  String generateKnotInsight({
    required _i23.PersonalityKnot? knotA,
    required _i23.PersonalityKnot? knotB,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateKnotInsight,
          [],
          {
            #knotA: knotA,
            #knotB: knotB,
          },
        ),
        returnValue: _i19.dummyValue<String>(
          this,
          Invocation.method(
            #generateKnotInsight,
            [],
            {
              #knotA: knotA,
              #knotB: knotB,
            },
          ),
        ),
      ) as String);
}

/// A class which mocks [CrossEntityCompatibilityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCrossEntityCompatibilityService extends _i1.Mock
    implements _i24.CrossEntityCompatibilityService {
  MockCrossEntityCompatibilityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<double> calculateIntegratedCompatibility({
    required _i25.EntityKnot? entityA,
    required _i25.EntityKnot? entityB,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateIntegratedCompatibility,
          [],
          {
            #entityA: entityA,
            #entityB: entityB,
          },
        ),
        returnValue: _i12.Future<double>.value(0.0),
      ) as _i12.Future<double>);

  @override
  _i12.Future<double> calculateKnotOnlyCompatibility({
    required _i25.EntityKnot? entityA,
    required _i25.EntityKnot? entityB,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateKnotOnlyCompatibility,
          [],
          {
            #entityA: entityA,
            #entityB: entityB,
          },
        ),
        returnValue: _i12.Future<double>.value(0.0),
      ) as _i12.Future<double>);

  @override
  _i12.Future<double> calculateMultiEntityWeaveCompatibility(
          {required List<_i25.EntityKnot>? entities}) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateMultiEntityWeaveCompatibility,
          [],
          {#entities: entities},
        ),
        returnValue: _i12.Future<double>.value(0.0),
      ) as _i12.Future<double>);
}
