// Mocks generated by Mockito 5.4.6 from annotations
// in spots/test/unit/controllers/sponsorship_checkout_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:spots/core/models/brand_account.dart' as _i9;
import 'package:spots/core/models/expertise_event.dart' as _i4;
import 'package:spots/core/models/product_tracking.dart' as _i5;
import 'package:spots/core/models/sponsorship.dart' as _i2;
import 'package:spots/core/models/spot.dart' as _i12;
import 'package:spots/core/models/unified_user.dart' as _i11;
import 'package:spots/core/services/expertise_event_service.dart' as _i10;
import 'package:spots/core/services/product_tracking_service.dart' as _i6;
import 'package:spots/core/services/sponsorship_service.dart' as _i7;
import 'package:spots/core/services/vibe_compatibility_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSponsorship_0 extends _i1.SmartFake implements _i2.Sponsorship {
  _FakeSponsorship_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVibeScore_1 extends _i1.SmartFake implements _i3.VibeScore {
  _FakeVibeScore_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExpertiseEvent_2 extends _i1.SmartFake
    implements _i4.ExpertiseEvent {
  _FakeExpertiseEvent_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductTracking_3 extends _i1.SmartFake
    implements _i5.ProductTracking {
  _FakeProductTracking_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductSalesReport_4 extends _i1.SmartFake
    implements _i6.ProductSalesReport {
  _FakeProductSalesReport_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SponsorshipService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSponsorshipService extends _i1.Mock
    implements _i7.SponsorshipService {
  MockSponsorshipService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.Sponsorship> createSponsorship({
    required String? eventId,
    required String? brandId,
    required _i2.SponsorshipType? type,
    double? contributionAmount,
    double? productValue,
    Map<String, dynamic>? agreementTerms,
    double? vibeCompatibilityScore,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSponsorship,
          [],
          {
            #eventId: eventId,
            #brandId: brandId,
            #type: type,
            #contributionAmount: contributionAmount,
            #productValue: productValue,
            #agreementTerms: agreementTerms,
            #vibeCompatibilityScore: vibeCompatibilityScore,
          },
        ),
        returnValue: _i8.Future<_i2.Sponsorship>.value(_FakeSponsorship_0(
          this,
          Invocation.method(
            #createSponsorship,
            [],
            {
              #eventId: eventId,
              #brandId: brandId,
              #type: type,
              #contributionAmount: contributionAmount,
              #productValue: productValue,
              #agreementTerms: agreementTerms,
              #vibeCompatibilityScore: vibeCompatibilityScore,
            },
          ),
        )),
      ) as _i8.Future<_i2.Sponsorship>);

  @override
  _i8.Future<List<_i2.Sponsorship>> getSponsorshipsForEvent(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSponsorshipsForEvent,
          [eventId],
        ),
        returnValue:
            _i8.Future<List<_i2.Sponsorship>>.value(<_i2.Sponsorship>[]),
      ) as _i8.Future<List<_i2.Sponsorship>>);

  @override
  _i8.Future<List<_i2.Sponsorship>> getSponsorshipsForBrand(String? brandId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSponsorshipsForBrand,
          [brandId],
        ),
        returnValue:
            _i8.Future<List<_i2.Sponsorship>>.value(<_i2.Sponsorship>[]),
      ) as _i8.Future<List<_i2.Sponsorship>>);

  @override
  _i8.Future<_i2.Sponsorship?> getSponsorshipById(String? sponsorshipId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSponsorshipById,
          [sponsorshipId],
        ),
        returnValue: _i8.Future<_i2.Sponsorship?>.value(),
      ) as _i8.Future<_i2.Sponsorship?>);

  @override
  _i8.Future<_i2.Sponsorship> updateSponsorshipStatus({
    required String? sponsorshipId,
    required _i2.SponsorshipStatus? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSponsorshipStatus,
          [],
          {
            #sponsorshipId: sponsorshipId,
            #status: status,
          },
        ),
        returnValue: _i8.Future<_i2.Sponsorship>.value(_FakeSponsorship_0(
          this,
          Invocation.method(
            #updateSponsorshipStatus,
            [],
            {
              #sponsorshipId: sponsorshipId,
              #status: status,
            },
          ),
        )),
      ) as _i8.Future<_i2.Sponsorship>);

  @override
  _i8.Future<bool> checkSponsorshipEligibility({
    required String? eventId,
    required String? brandId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkSponsorshipEligibility,
          [],
          {
            #eventId: eventId,
            #brandId: brandId,
          },
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<double> calculateCompatibility({
    required String? eventId,
    required String? brandId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateCompatibility,
          [],
          {
            #eventId: eventId,
            #brandId: brandId,
          },
        ),
        returnValue: _i8.Future<double>.value(0.0),
      ) as _i8.Future<double>);

  @override
  _i8.Future<_i3.VibeScore> calculateVibeScore({
    required String? eventId,
    required String? brandId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateVibeScore,
          [],
          {
            #eventId: eventId,
            #brandId: brandId,
          },
        ),
        returnValue: _i8.Future<_i3.VibeScore>.value(_FakeVibeScore_1(
          this,
          Invocation.method(
            #calculateVibeScore,
            [],
            {
              #eventId: eventId,
              #brandId: brandId,
            },
          ),
        )),
      ) as _i8.Future<_i3.VibeScore>);

  @override
  _i8.Future<_i9.BrandAccount?> getBrandById(String? brandId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBrandById,
          [brandId],
        ),
        returnValue: _i8.Future<_i9.BrandAccount?>.value(),
      ) as _i8.Future<_i9.BrandAccount?>);

  @override
  _i8.Future<void> registerBrand(_i9.BrandAccount? brand) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerBrand,
          [brand],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [ExpertiseEventService].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpertiseEventService extends _i1.Mock
    implements _i10.ExpertiseEventService {
  MockExpertiseEventService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i4.ExpertiseEvent> createEvent({
    required _i11.UnifiedUser? host,
    required String? title,
    required String? description,
    required String? category,
    required _i4.ExpertiseEventType? eventType,
    required DateTime? startTime,
    required DateTime? endTime,
    List<_i12.Spot>? spots,
    String? location,
    double? latitude,
    double? longitude,
    String? cityCode,
    String? localityCode,
    int? maxAttendees = 20,
    double? price,
    bool? isPublic = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEvent,
          [],
          {
            #host: host,
            #title: title,
            #description: description,
            #category: category,
            #eventType: eventType,
            #startTime: startTime,
            #endTime: endTime,
            #spots: spots,
            #location: location,
            #latitude: latitude,
            #longitude: longitude,
            #cityCode: cityCode,
            #localityCode: localityCode,
            #maxAttendees: maxAttendees,
            #price: price,
            #isPublic: isPublic,
          },
        ),
        returnValue: _i8.Future<_i4.ExpertiseEvent>.value(_FakeExpertiseEvent_2(
          this,
          Invocation.method(
            #createEvent,
            [],
            {
              #host: host,
              #title: title,
              #description: description,
              #category: category,
              #eventType: eventType,
              #startTime: startTime,
              #endTime: endTime,
              #spots: spots,
              #location: location,
              #latitude: latitude,
              #longitude: longitude,
              #cityCode: cityCode,
              #localityCode: localityCode,
              #maxAttendees: maxAttendees,
              #price: price,
              #isPublic: isPublic,
            },
          ),
        )),
      ) as _i8.Future<_i4.ExpertiseEvent>);

  @override
  _i8.Future<_i4.ExpertiseEvent> duplicateEvent({
    required _i4.ExpertiseEvent? originalEvent,
    DateTime? newStartTime,
    bool? autoSuggestTime = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #duplicateEvent,
          [],
          {
            #originalEvent: originalEvent,
            #newStartTime: newStartTime,
            #autoSuggestTime: autoSuggestTime,
          },
        ),
        returnValue: _i8.Future<_i4.ExpertiseEvent>.value(_FakeExpertiseEvent_2(
          this,
          Invocation.method(
            #duplicateEvent,
            [],
            {
              #originalEvent: originalEvent,
              #newStartTime: newStartTime,
              #autoSuggestTime: autoSuggestTime,
            },
          ),
        )),
      ) as _i8.Future<_i4.ExpertiseEvent>);

  @override
  _i8.Future<void> registerForEvent(
    _i4.ExpertiseEvent? event,
    _i11.UnifiedUser? user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerForEvent,
          [
            event,
            user,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> cancelRegistration(
    _i4.ExpertiseEvent? event,
    _i11.UnifiedUser? user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelRegistration,
          [
            event,
            user,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i4.ExpertiseEvent>> getEventsByHost(
          _i11.UnifiedUser? host) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsByHost,
          [host],
        ),
        returnValue:
            _i8.Future<List<_i4.ExpertiseEvent>>.value(<_i4.ExpertiseEvent>[]),
      ) as _i8.Future<List<_i4.ExpertiseEvent>>);

  @override
  _i8.Future<List<_i4.ExpertiseEvent>> getEventsByAttendee(
          _i11.UnifiedUser? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsByAttendee,
          [user],
        ),
        returnValue:
            _i8.Future<List<_i4.ExpertiseEvent>>.value(<_i4.ExpertiseEvent>[]),
      ) as _i8.Future<List<_i4.ExpertiseEvent>>);

  @override
  _i8.Future<_i4.ExpertiseEvent?> getEventById(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventById,
          [eventId],
        ),
        returnValue: _i8.Future<_i4.ExpertiseEvent?>.value(),
      ) as _i8.Future<_i4.ExpertiseEvent?>);

  @override
  _i8.Future<List<_i4.ExpertiseEvent>> searchEvents({
    String? category,
    String? location,
    _i4.ExpertiseEventType? eventType,
    DateTime? startDate,
    DateTime? endDate,
    int? maxResults = 20,
    bool? includeCommunityEvents = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEvents,
          [],
          {
            #category: category,
            #location: location,
            #eventType: eventType,
            #startDate: startDate,
            #endDate: endDate,
            #maxResults: maxResults,
            #includeCommunityEvents: includeCommunityEvents,
          },
        ),
        returnValue:
            _i8.Future<List<_i4.ExpertiseEvent>>.value(<_i4.ExpertiseEvent>[]),
      ) as _i8.Future<List<_i4.ExpertiseEvent>>);

  @override
  _i8.Future<List<_i4.ExpertiseEvent>> getUpcomingEventsInCategory(
    String? category, {
    int? maxResults = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUpcomingEventsInCategory,
          [category],
          {#maxResults: maxResults},
        ),
        returnValue:
            _i8.Future<List<_i4.ExpertiseEvent>>.value(<_i4.ExpertiseEvent>[]),
      ) as _i8.Future<List<_i4.ExpertiseEvent>>);

  @override
  _i8.Future<List<_i4.ExpertiseEvent>> searchEventsWithConnectedLocalities({
    required _i11.UnifiedUser? user,
    String? category,
    String? location,
    _i4.ExpertiseEventType? eventType,
    DateTime? startDate,
    DateTime? endDate,
    int? maxResults = 20,
    bool? includeConnectedLocalities = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEventsWithConnectedLocalities,
          [],
          {
            #user: user,
            #category: category,
            #location: location,
            #eventType: eventType,
            #startDate: startDate,
            #endDate: endDate,
            #maxResults: maxResults,
            #includeConnectedLocalities: includeConnectedLocalities,
          },
        ),
        returnValue:
            _i8.Future<List<_i4.ExpertiseEvent>>.value(<_i4.ExpertiseEvent>[]),
      ) as _i8.Future<List<_i4.ExpertiseEvent>>);

  @override
  _i8.Future<void> updateEventStatus(
    _i4.ExpertiseEvent? event,
    _i4.EventStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEventStatus,
          [
            event,
            status,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [ProductTrackingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductTrackingService extends _i1.Mock
    implements _i6.ProductTrackingService {
  MockProductTrackingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i5.ProductTracking> recordProductContribution({
    required String? sponsorshipId,
    required String? productName,
    required int? quantityProvided,
    required double? unitPrice,
    String? sku,
    String? description,
    String? imageUrl,
    double? unitCostPrice,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordProductContribution,
          [],
          {
            #sponsorshipId: sponsorshipId,
            #productName: productName,
            #quantityProvided: quantityProvided,
            #unitPrice: unitPrice,
            #sku: sku,
            #description: description,
            #imageUrl: imageUrl,
            #unitCostPrice: unitCostPrice,
          },
        ),
        returnValue:
            _i8.Future<_i5.ProductTracking>.value(_FakeProductTracking_3(
          this,
          Invocation.method(
            #recordProductContribution,
            [],
            {
              #sponsorshipId: sponsorshipId,
              #productName: productName,
              #quantityProvided: quantityProvided,
              #unitPrice: unitPrice,
              #sku: sku,
              #description: description,
              #imageUrl: imageUrl,
              #unitCostPrice: unitCostPrice,
            },
          ),
        )),
      ) as _i8.Future<_i5.ProductTracking>);

  @override
  _i8.Future<_i5.ProductTracking> recordProductSale({
    required String? productTrackingId,
    required int? quantity,
    required String? buyerId,
    double? salePrice,
    String? paymentMethod,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordProductSale,
          [],
          {
            #productTrackingId: productTrackingId,
            #quantity: quantity,
            #buyerId: buyerId,
            #salePrice: salePrice,
            #paymentMethod: paymentMethod,
          },
        ),
        returnValue:
            _i8.Future<_i5.ProductTracking>.value(_FakeProductTracking_3(
          this,
          Invocation.method(
            #recordProductSale,
            [],
            {
              #productTrackingId: productTrackingId,
              #quantity: quantity,
              #buyerId: buyerId,
              #salePrice: salePrice,
              #paymentMethod: paymentMethod,
            },
          ),
        )),
      ) as _i8.Future<_i5.ProductTracking>);

  @override
  _i8.Future<Map<String, double>> calculateRevenueAttribution(
          {required String? productTrackingId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateRevenueAttribution,
          [],
          {#productTrackingId: productTrackingId},
        ),
        returnValue: _i8.Future<Map<String, double>>.value(<String, double>{}),
      ) as _i8.Future<Map<String, double>>);

  @override
  _i8.Future<_i5.ProductTracking> updateProductQuantity({
    required String? productTrackingId,
    int? quantitySold,
    int? quantityGivenAway,
    int? quantityUsedInEvent,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProductQuantity,
          [],
          {
            #productTrackingId: productTrackingId,
            #quantitySold: quantitySold,
            #quantityGivenAway: quantityGivenAway,
            #quantityUsedInEvent: quantityUsedInEvent,
          },
        ),
        returnValue:
            _i8.Future<_i5.ProductTracking>.value(_FakeProductTracking_3(
          this,
          Invocation.method(
            #updateProductQuantity,
            [],
            {
              #productTrackingId: productTrackingId,
              #quantitySold: quantitySold,
              #quantityGivenAway: quantityGivenAway,
              #quantityUsedInEvent: quantityUsedInEvent,
            },
          ),
        )),
      ) as _i8.Future<_i5.ProductTracking>);

  @override
  _i8.Future<_i5.ProductTracking?> getProductTrackingById(
          String? productTrackingId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductTrackingById,
          [productTrackingId],
        ),
        returnValue: _i8.Future<_i5.ProductTracking?>.value(),
      ) as _i8.Future<_i5.ProductTracking?>);

  @override
  _i8.Future<List<_i5.ProductTracking>> getProductTrackingForSponsorship(
          String? sponsorshipId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductTrackingForSponsorship,
          [sponsorshipId],
        ),
        returnValue: _i8.Future<List<_i5.ProductTracking>>.value(
            <_i5.ProductTracking>[]),
      ) as _i8.Future<List<_i5.ProductTracking>>);

  @override
  _i8.Future<_i6.ProductSalesReport> generateSalesReport({
    required String? sponsorshipId,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateSalesReport,
          [],
          {
            #sponsorshipId: sponsorshipId,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue:
            _i8.Future<_i6.ProductSalesReport>.value(_FakeProductSalesReport_4(
          this,
          Invocation.method(
            #generateSalesReport,
            [],
            {
              #sponsorshipId: sponsorshipId,
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i8.Future<_i6.ProductSalesReport>);
}
