// Mocks generated by Mockito 5.4.6 from annotations
// in spots/test/unit/data/repositories/offline_mode_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:connectivity_plus/connectivity_plus.dart' as _i13;
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart'
    as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:spots/core/models/list.dart' as _i3;
import 'package:spots/core/models/spot.dart' as _i2;
import 'package:spots/core/models/user.dart' as _i11;
import 'package:spots/data/datasources/local/auth_local_datasource.dart'
    as _i10;
import 'package:spots/data/datasources/local/lists_local_datasource.dart'
    as _i8;
import 'package:spots/data/datasources/local/spots_local_datasource.dart'
    as _i4;
import 'package:spots/data/datasources/remote/auth_remote_datasource.dart'
    as _i12;
import 'package:spots/data/datasources/remote/lists_remote_datasource.dart'
    as _i9;
import 'package:spots/data/datasources/remote/spots_remote_datasource.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSpot_0 extends _i1.SmartFake implements _i2.Spot {
  _FakeSpot_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSpotList_1 extends _i1.SmartFake implements _i3.SpotList {
  _FakeSpotList_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SpotsLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpotsLocalDataSource extends _i1.Mock
    implements _i4.SpotsLocalDataSource {
  MockSpotsLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.Spot>> getAllSpots() => (super.noSuchMethod(
        Invocation.method(
          #getAllSpots,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Spot>>.value(<_i2.Spot>[]),
      ) as _i5.Future<List<_i2.Spot>>);

  @override
  _i5.Future<_i2.Spot?> getSpotById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getSpotById,
          [id],
        ),
        returnValue: _i5.Future<_i2.Spot?>.value(),
      ) as _i5.Future<_i2.Spot?>);

  @override
  _i5.Future<String> createSpot(_i2.Spot? spot) => (super.noSuchMethod(
        Invocation.method(
          #createSpot,
          [spot],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #createSpot,
            [spot],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<_i2.Spot> updateSpot(_i2.Spot? spot) => (super.noSuchMethod(
        Invocation.method(
          #updateSpot,
          [spot],
        ),
        returnValue: _i5.Future<_i2.Spot>.value(_FakeSpot_0(
          this,
          Invocation.method(
            #updateSpot,
            [spot],
          ),
        )),
      ) as _i5.Future<_i2.Spot>);

  @override
  _i5.Future<void> deleteSpot(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteSpot,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.Spot>> getSpotsByCategory(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSpotsByCategory,
          [category],
        ),
        returnValue: _i5.Future<List<_i2.Spot>>.value(<_i2.Spot>[]),
      ) as _i5.Future<List<_i2.Spot>>);

  @override
  _i5.Future<List<_i2.Spot>> getSpotsFromRespectedLists() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSpotsFromRespectedLists,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Spot>>.value(<_i2.Spot>[]),
      ) as _i5.Future<List<_i2.Spot>>);

  @override
  _i5.Future<List<_i2.Spot>> searchSpots(String? query) => (super.noSuchMethod(
        Invocation.method(
          #searchSpots,
          [query],
        ),
        returnValue: _i5.Future<List<_i2.Spot>>.value(<_i2.Spot>[]),
      ) as _i5.Future<List<_i2.Spot>>);
}

/// A class which mocks [SpotsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpotsRemoteDataSource extends _i1.Mock
    implements _i7.SpotsRemoteDataSource {
  MockSpotsRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.Spot>> getSpots() => (super.noSuchMethod(
        Invocation.method(
          #getSpots,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Spot>>.value(<_i2.Spot>[]),
      ) as _i5.Future<List<_i2.Spot>>);

  @override
  _i5.Future<_i2.Spot> createSpot(_i2.Spot? spot) => (super.noSuchMethod(
        Invocation.method(
          #createSpot,
          [spot],
        ),
        returnValue: _i5.Future<_i2.Spot>.value(_FakeSpot_0(
          this,
          Invocation.method(
            #createSpot,
            [spot],
          ),
        )),
      ) as _i5.Future<_i2.Spot>);

  @override
  _i5.Future<_i2.Spot> updateSpot(_i2.Spot? spot) => (super.noSuchMethod(
        Invocation.method(
          #updateSpot,
          [spot],
        ),
        returnValue: _i5.Future<_i2.Spot>.value(_FakeSpot_0(
          this,
          Invocation.method(
            #updateSpot,
            [spot],
          ),
        )),
      ) as _i5.Future<_i2.Spot>);

  @override
  _i5.Future<void> deleteSpot(String? spotId) => (super.noSuchMethod(
        Invocation.method(
          #deleteSpot,
          [spotId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [ListsLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockListsLocalDataSource extends _i1.Mock
    implements _i8.ListsLocalDataSource {
  MockListsLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.SpotList>> getLists() => (super.noSuchMethod(
        Invocation.method(
          #getLists,
          [],
        ),
        returnValue: _i5.Future<List<_i3.SpotList>>.value(<_i3.SpotList>[]),
      ) as _i5.Future<List<_i3.SpotList>>);

  @override
  _i5.Future<_i3.SpotList?> saveList(_i3.SpotList? list) => (super.noSuchMethod(
        Invocation.method(
          #saveList,
          [list],
        ),
        returnValue: _i5.Future<_i3.SpotList?>.value(),
      ) as _i5.Future<_i3.SpotList?>);

  @override
  _i5.Future<void> deleteList(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteList,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [ListsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockListsRemoteDataSource extends _i1.Mock
    implements _i9.ListsRemoteDataSource {
  MockListsRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.SpotList>> getLists() => (super.noSuchMethod(
        Invocation.method(
          #getLists,
          [],
        ),
        returnValue: _i5.Future<List<_i3.SpotList>>.value(<_i3.SpotList>[]),
      ) as _i5.Future<List<_i3.SpotList>>);

  @override
  _i5.Future<List<_i3.SpotList>> getPublicLists({int? limit}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPublicLists,
          [],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<_i3.SpotList>>.value(<_i3.SpotList>[]),
      ) as _i5.Future<List<_i3.SpotList>>);

  @override
  _i5.Future<_i3.SpotList> createList(_i3.SpotList? list) =>
      (super.noSuchMethod(
        Invocation.method(
          #createList,
          [list],
        ),
        returnValue: _i5.Future<_i3.SpotList>.value(_FakeSpotList_1(
          this,
          Invocation.method(
            #createList,
            [list],
          ),
        )),
      ) as _i5.Future<_i3.SpotList>);

  @override
  _i5.Future<_i3.SpotList> updateList(_i3.SpotList? list) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateList,
          [list],
        ),
        returnValue: _i5.Future<_i3.SpotList>.value(_FakeSpotList_1(
          this,
          Invocation.method(
            #updateList,
            [list],
          ),
        )),
      ) as _i5.Future<_i3.SpotList>);

  @override
  _i5.Future<void> deleteList(String? listId) => (super.noSuchMethod(
        Invocation.method(
          #deleteList,
          [listId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i10.AuthLocalDataSource {
  MockAuthLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i11.User?> signIn(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [
            email,
            password,
          ],
        ),
        returnValue: _i5.Future<_i11.User?>.value(),
      ) as _i5.Future<_i11.User?>);

  @override
  _i5.Future<_i11.User?> signUp(
    String? email,
    String? password,
    _i11.User? user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [
            email,
            password,
            user,
          ],
        ),
        returnValue: _i5.Future<_i11.User?>.value(),
      ) as _i5.Future<_i11.User?>);

  @override
  _i5.Future<void> saveUser(_i11.User? user) => (super.noSuchMethod(
        Invocation.method(
          #saveUser,
          [user],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i11.User?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i5.Future<_i11.User?>.value(),
      ) as _i5.Future<_i11.User?>);

  @override
  _i5.Future<void> clearUser() => (super.noSuchMethod(
        Invocation.method(
          #clearUser,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isOnboardingCompleted() => (super.noSuchMethod(
        Invocation.method(
          #isOnboardingCompleted,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> markOnboardingCompleted() => (super.noSuchMethod(
        Invocation.method(
          #markOnboardingCompleted,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i12.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i11.User?> signIn(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [
            email,
            password,
          ],
        ),
        returnValue: _i5.Future<_i11.User?>.value(),
      ) as _i5.Future<_i11.User?>);

  @override
  _i5.Future<_i11.User?> signUp(
    String? email,
    String? password,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [
            email,
            password,
            name,
          ],
        ),
        returnValue: _i5.Future<_i11.User?>.value(),
      ) as _i5.Future<_i11.User?>);

  @override
  _i5.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i11.User?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i5.Future<_i11.User?>.value(),
      ) as _i5.Future<_i11.User?>);

  @override
  _i5.Future<_i11.User?> updateUser(_i11.User? user) => (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [user],
        ),
        returnValue: _i5.Future<_i11.User?>.value(),
      ) as _i5.Future<_i11.User?>);
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i13.Connectivity {
  MockConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i14.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onConnectivityChanged),
        returnValue: _i5.Stream<List<_i14.ConnectivityResult>>.empty(),
      ) as _i5.Stream<List<_i14.ConnectivityResult>>);

  @override
  _i5.Future<List<_i14.ConnectivityResult>> checkConnectivity() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkConnectivity,
          [],
        ),
        returnValue: _i5.Future<List<_i14.ConnectivityResult>>.value(
            <_i14.ConnectivityResult>[]),
      ) as _i5.Future<List<_i14.ConnectivityResult>>);
}
