// Mocks generated by Mockito 5.4.6 from annotations
// in spots/test/unit/ai/action_executor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:spots/core/models/list.dart' as _i5;
import 'package:spots/core/models/spot.dart' as _i3;
import 'package:spots/domain/repositories/lists_repository.dart' as _i4;
import 'package:spots/domain/repositories/spots_repository.dart' as _i2;
import 'package:spots/domain/usecases/lists/create_list_usecase.dart' as _i8;
import 'package:spots/domain/usecases/lists/update_list_usecase.dart' as _i9;
import 'package:spots/domain/usecases/spots/create_spot_usecase.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSpotsRepository_0 extends _i1.SmartFake
    implements _i2.SpotsRepository {
  _FakeSpotsRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSpot_1 extends _i1.SmartFake implements _i3.Spot {
  _FakeSpot_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeListsRepository_2 extends _i1.SmartFake
    implements _i4.ListsRepository {
  _FakeListsRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSpotList_3 extends _i1.SmartFake implements _i5.SpotList {
  _FakeSpotList_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CreateSpotUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateSpotUseCase extends _i1.Mock implements _i6.CreateSpotUseCase {
  MockCreateSpotUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SpotsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeSpotsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.SpotsRepository);

  @override
  _i7.Future<_i3.Spot> call(_i3.Spot? spot) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [spot],
        ),
        returnValue: _i7.Future<_i3.Spot>.value(_FakeSpot_1(
          this,
          Invocation.method(
            #call,
            [spot],
          ),
        )),
      ) as _i7.Future<_i3.Spot>);
}

/// A class which mocks [CreateListUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateListUseCase extends _i1.Mock implements _i8.CreateListUseCase {
  MockCreateListUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ListsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeListsRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.ListsRepository);

  @override
  _i7.Future<_i5.SpotList> call(_i5.SpotList? list) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [list],
        ),
        returnValue: _i7.Future<_i5.SpotList>.value(_FakeSpotList_3(
          this,
          Invocation.method(
            #call,
            [list],
          ),
        )),
      ) as _i7.Future<_i5.SpotList>);
}

/// A class which mocks [UpdateListUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateListUseCase extends _i1.Mock implements _i9.UpdateListUseCase {
  MockUpdateListUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ListsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeListsRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.ListsRepository);

  @override
  _i7.Future<_i5.SpotList> call(_i5.SpotList? list) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [list],
        ),
        returnValue: _i7.Future<_i5.SpotList>.value(_FakeSpotList_3(
          this,
          Invocation.method(
            #call,
            [list],
          ),
        )),
      ) as _i7.Future<_i5.SpotList>);
}

/// A class which mocks [SpotsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpotsRepository extends _i1.Mock implements _i2.SpotsRepository {
  MockSpotsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i3.Spot>> getSpots() => (super.noSuchMethod(
        Invocation.method(
          #getSpots,
          [],
        ),
        returnValue: _i7.Future<List<_i3.Spot>>.value(<_i3.Spot>[]),
      ) as _i7.Future<List<_i3.Spot>>);

  @override
  _i7.Future<List<_i3.Spot>> getSpotsFromRespectedLists() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSpotsFromRespectedLists,
          [],
        ),
        returnValue: _i7.Future<List<_i3.Spot>>.value(<_i3.Spot>[]),
      ) as _i7.Future<List<_i3.Spot>>);

  @override
  _i7.Future<_i3.Spot> createSpot(_i3.Spot? spot) => (super.noSuchMethod(
        Invocation.method(
          #createSpot,
          [spot],
        ),
        returnValue: _i7.Future<_i3.Spot>.value(_FakeSpot_1(
          this,
          Invocation.method(
            #createSpot,
            [spot],
          ),
        )),
      ) as _i7.Future<_i3.Spot>);

  @override
  _i7.Future<_i3.Spot> updateSpot(_i3.Spot? spot) => (super.noSuchMethod(
        Invocation.method(
          #updateSpot,
          [spot],
        ),
        returnValue: _i7.Future<_i3.Spot>.value(_FakeSpot_1(
          this,
          Invocation.method(
            #updateSpot,
            [spot],
          ),
        )),
      ) as _i7.Future<_i3.Spot>);

  @override
  _i7.Future<void> deleteSpot(String? spotId) => (super.noSuchMethod(
        Invocation.method(
          #deleteSpot,
          [spotId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [ListsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockListsRepository extends _i1.Mock implements _i4.ListsRepository {
  MockListsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i5.SpotList>> getLists() => (super.noSuchMethod(
        Invocation.method(
          #getLists,
          [],
        ),
        returnValue: _i7.Future<List<_i5.SpotList>>.value(<_i5.SpotList>[]),
      ) as _i7.Future<List<_i5.SpotList>>);

  @override
  _i7.Future<List<_i5.SpotList>> getPublicLists() => (super.noSuchMethod(
        Invocation.method(
          #getPublicLists,
          [],
        ),
        returnValue: _i7.Future<List<_i5.SpotList>>.value(<_i5.SpotList>[]),
      ) as _i7.Future<List<_i5.SpotList>>);

  @override
  _i7.Future<_i5.SpotList> createList(_i5.SpotList? list) =>
      (super.noSuchMethod(
        Invocation.method(
          #createList,
          [list],
        ),
        returnValue: _i7.Future<_i5.SpotList>.value(_FakeSpotList_3(
          this,
          Invocation.method(
            #createList,
            [list],
          ),
        )),
      ) as _i7.Future<_i5.SpotList>);

  @override
  _i7.Future<_i5.SpotList> updateList(_i5.SpotList? list) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateList,
          [list],
        ),
        returnValue: _i7.Future<_i5.SpotList>.value(_FakeSpotList_3(
          this,
          Invocation.method(
            #updateList,
            [list],
          ),
        )),
      ) as _i7.Future<_i5.SpotList>);

  @override
  _i7.Future<void> deleteList(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteList,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> canUserCreateList(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #canUserCreateList,
          [userId],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> canUserDeleteList(
    String? userId,
    String? listId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #canUserDeleteList,
          [
            userId,
            listId,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> canUserManageCollaborators(
    String? userId,
    String? listId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #canUserManageCollaborators,
          [
            userId,
            listId,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> canUserAddSpotToList(
    String? userId,
    String? listId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #canUserAddSpotToList,
          [
            userId,
            listId,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> createStarterListsForUser({required String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStarterListsForUser,
          [],
          {#userId: userId},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> createPersonalizedListsForUser({
    required String? userId,
    required Map<String, dynamic>? userPreferences,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPersonalizedListsForUser,
          [],
          {
            #userId: userId,
            #userPreferences: userPreferences,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}
